### ISSUE TITLE
Multiple entries in Org Agenda shown for one TODO item in org journal

### ISSUE THREAD

**Issue by phye** [bastibe/org-journal#100]
If I create one org-journal entry via `calendar` -> `i j` and create a new TODO item, the same TODO item will be shown in Org Agenda if I enabled Org Mode integration with org-calendar. However, each time I check my Org Agenda (`c-c a a`, `org-agenda`),  a new line of the same TODO item will be shown in Org Agenda.

**Comment by bastibe** [comment]
Interesting! Can you tell me the contents of your `org-agenda-files` before and after one of these duplications?

**Comment by phye** [comment]
I have ran `c-c a a` two (or three times, can't remember), and here's the value of `org-agenda-files`: 

```
("~/ws/OrgNotes/gtd.org" "~/ws/OrgNotes/PlanLearning.org" "~/ws/OrgNotes/PlanLife.org" "~/ws/OrgNotes/life/Birthday.org" "~/ws/OrgNotes/Work@xxx.org" "/Users/phye/ws/OrgNotes/journals/20180418" "/Users/phye/ws/OrgNotes/journals/20180430" "/Users/phye/ws/OrgNotes/journals/20180501" "/Users/phye/ws/OrgNotes/journals/20180511" "/Users/phye/ws/OrgNotes/journals/20180518" "/Users/phye/ws/OrgNotes/journals/20180521" "/Users/phye/ws/OrgNotes/journals/20180526" "/Users/phye/ws/OrgNotes/journals/20180418" "/Users/phye/ws/OrgNotes/journals/20180430" "/Users/phye/ws/OrgNotes/journals/20180501" "/Users/phye/ws/OrgNotes/journals/20180511" "/Users/phye/ws/OrgNotes/journals/20180518" "/Users/phye/ws/OrgNotes/journals/20180521" "/Users/phye/ws/OrgNotes/journals/20180526")
```

There're indeed two duplications...

**Comment by bastibe** [comment]
There is a bug in org-journal if `org-journal-dir` does not end in "`/`". The bugfix has been uploaded, and will be picked up by Melpa and Melpa Stable, soon. If you don't want to wait for the bug fix, make sure [your `org-journal-dir`](https://github.com/phye/emacs.d/blob/master/defuns/phye.el#L86) ends in "`/`", e.g. `(setq org-journal-dir "~/ws/OrgNotes/journals/")`.

Please let me know if this fixes your issue.

**Comment by phye** [comment]
Cool!
I've changed my `org-journal-dir` and indeed the issue got fixed!
Thanks for your effort!
