### ISSUE TITLE
org-show-subtree command creates issues with non-standard file header

### ISSUE THREAD

**Issue by ary15** [bastibe/org-journal#101]
org-journal has the option to change the preamble of the file from the standard format to whatever the user wants. I.e. the standard format is:
* Tuesday, 9/5/18
** Entry 1 of the day

However, I might want this to be a title. This then allows me to have all entries on a date as individual trees, not subtrees:
#+TITLE: Tuesday, 9/5/18
* Entry 1 of the day

Unfortunately, this causes some problems with these calendar display functions:
org-journal-read-or-display-entry
org-journal-next-entry
org-journal-previous-entry

The problem is that they all contain an org-show-subtree function. For the last two, it is the last part of the defun statement, so just throws an error message, but works as expected. The display entry function doesn't work though, as the org-show-subtree is in the middle.

I have fixed this by commenting out the (org-show-subtree). 

The most complete way to fix this would be to conditionally switch off the org-show-subtree, if the user changes the default look of the file. I can see that this would be clunky and complicated in a way that isn't really necessary. 

The easiest way to fix this would be to remove this function permanently from the view functions. Having an open or closed tree could then be achieved through normal org-folding settings, either local or global.

**Comment by bastibe** [comment]
Thank you for this bug report. It should be fixed in the latest commit. Can you check that the latest commit works for you?

**Comment by ary15** [comment]
I just updated my setup and this bug no longer pops up. Awesome, thank you!

Just for reference, I use org-journal through MELPA & cask and have just updated to:  
org-journal-20180502.636
