### ISSUE TITLE
Errors seen after package update on 2018-05-31 (Spacemacs)

### ISSUE THREAD

**Issue by jackbaty** [bastibe/org-journal#103]
After updating all Spacemacs packages and also pulling latest Spacemacs "develop" branch, I was seeing the following when opening any .org files:

`File mode specification error: (invalid-read-syntax ))`

This happens when reloading my spacemacs init, triggering a capture template, or when opening any .org file. 

Looking at the debug output (via debug-on-error) I saw a few references to org-journal (sorry I did not save them). I rolled back all packages, then froze org-journal (org-journal-20180528.1118) and re-updated the other packages. I'm no longer seeing the error, which makes me think it's related to the latest org-journal updates.

I'm not experienced debugging emacs issues, so let me know what else I can provide that might help.

#### System Info :computer:
- OS: darwin
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 390462e36)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(org :variables org-want-todo-bindings t org-enable-org-journal-support t org-enable-reveal-js-support t org-journal-dir "~/org/journal/" org-journal-file-format "%Y-%m-%d.org" org-journal-find-file #'find-file org-journal-enable-agenda-integration t org-journal-time-format "" org-journal-date-format "%A, %B %d %Y")
```

**Comment by bastibe** [comment]
This has already been fixed. I am just waiting for melpa to pick up the changes.

If you don't want to experience this in the future, use melpa-stable instead of melpa.

**Comment by jackbaty** [comment]
Fantastic, thank you. Org-journal has become indispensable so you're right I should probably stick with stable!

**Comment by bastibe** [comment]
Melpa just came around, though, and the current version on Melpa should work again. I'll try to be more careful next time I push to github (melpa picked a very inconvenient time this time).
