### ISSUE TITLE
org-journal-carryover-items multiple TODOs

### ISSUE THREAD

**Issue by sfranky** [bastibe/org-journal#105]
Hello!

I can't figure out how to add multiple TODO keywords. 
I'm Emacs-illiterate, so that might be the reason! Could you please give an example with two keywords? e.g. this doesn't work:
``(setq org-journal-carryover-items "TODO=\"+TODO|+HOLD\""``
I've also tried escaping + and |, and also putting everything in its own escaped quotes, but nothing worked..

thanks very much and thanks for your excellent piece of work!

**Comment by bastibe** [comment]
I think it should be `"TODO=\"TODO\"|TODO=\"HOLD\""`.

Does that work for you?

**Comment by sfranky** [comment]
yes! Thanks a ton !!
