### ISSUE TITLE
Noisy `DEBUG` messages

### ISSUE THREAD

**Issue by akirak** [bastibe/org-journal#106]
Hello,

When `org-journal-enable-agenda-integration` is turned on, org-journal logs a number of `DEBUG: ...` messages into `*Messages*` buffer, but this is noisy. I suppose you added it for development. Have you ever considered suppressing these messages in normal use?

**Comment by bastibe** [comment]
Thank you for the bug report!

I'm sorry, I forgot a debug message in the last release! I just fixed it in 1.14.3, which should hit melpa and melpa stable in a few minutes. Again, sorry.

**Comment by cslux** [comment]
@bastibe This issue looks like that can be closed.
