### ISSUE TITLE
Can I carry-over parent headings for TODO items?

### ISSUE THREAD

**Issue by DesiQuintans** [bastibe/org-journal#107]
Hi bastibe, I love org-journal and I've been using it as a digital replacement for Bullet Journal with great success. I would like to know if this is possible. I want to organise multi-step tasks in their own tree, and have org-journal preserve the tree's structure after carry-over. 

**Original tree:**
```
** Project headline
*** Milestone 1
**** DONE Task A
**** TODO Task B
**** TODO Task C
*** Milestone 2
**** DONE Task D
**** TODO Task E
**** TODO Task F
```

**New journal entry after carry-over**
```
** Project headline
*** Milestone 1
**** TODO Task B
**** TODO Task C
*** Milestone 2
**** TODO Task E
**** TODO Task F
```

**Old journal entry after carry-over**
```
** Project headline
*** Milestone 1
**** DONE Task A
*** Milestone 2
**** DONE Task D
```

---

But when I do the carry-over, the TODO items are transferred to the new entry without the parent tree:

```
**** TODO Task B
**** TODO Task C
**** TODO Task E
**** TODO Task F
```

I have tried marking the parent tree headings with TODO tags to ensure they carry over, but this just makes the entire *Project headline* heading carry over, including the items marked DONE.

Is there a way to tell org-journal to do this? Thanks!

**Comment by bastibe** [comment]
org-journal carries over anything that matches `org-journal-carryover-items`. Have a look at https://orgmode.org/manual/Matching-tags-and-properties.html for options on this string.

**Comment by DesiQuintans** [comment]
I didn't explain the problem very well! I can ask it a different way:

Can I mark an item to be **copied** over, instead of **carried** over? The reason is that I would like to organise my todo list in a tree so that yesterday's journal page contains

```
** Project headline
*** Milestone 1
**** DONE Task A
*** Milestone 2
**** DONE Task D
```

And today's journal page contains

```
** Project headline
*** Milestone 1
**** TODO Task B
**** TODO Task C
*** Milestone 2
**** TODO Task E
**** TODO Task F
```

With the 'project headline' and 'milestone' headings preserved in both files. 

If I mark the whole tree so that it carries over, it carries-over both the TODO and DONE items, so that yesterday's entry looks like:

```
(the whole tree is moved)
```

and today's entry looks like:

```
** TODO Project headline
*** TODO Milestone 1
**** DONE Task A
**** TODO Task B
**** TODO Task C
*** TODO Milestone 2
**** DONE Task D
**** TODO Task E
**** TODO Task F
```

**Comment by bastibe** [comment]
I see what you mean now. Thank you for the clarification.

This is not currently possible. But it looks very useful. One would have to look into `org-journal-carryover` and `org-journal-extract-current-subtree` to get this to work. I believe there are some org-mode functions to get the current context (headline-path).

Would you like to take a stab at this?

**Comment by DesiQuintans** [comment]
I don't know Emacs Lisp but I am open to learning. It may take a while, so I would be happy if someone else swooped in and solved the problem in the meantime!

**Comment by bastibe** [comment]
If you need any help, feel free to ask!

**Comment by cslux** [comment]
@DesiQuintans The parents are now carried-over as well! Please test and report, if you think it should behaviour differently.
