### ISSUE TITLE
Set default tags for journal entries? (like with org-tag-alist)

### ISSUE THREAD

**Issue by TinaRussell** [bastibe/org-journal#109]
You know how with org-tag-alist, you can [establish a default set of tags](http://orgmode.org/manual/Setting-tags.html#Setting-tags), and then insert them easily with org-set-tags-command? I’m wondering how to do that in a way that’s specific to org-journal. (I’m guessing you could find some hack-y way to add a “#+TAGS:” buffer-local variable before or after the datestamp of every entry, but I’d like to look for a more elegant solution that doesn’t clutter up my entries, first.) Thanks!

**Comment by TinaRussell** [comment]
I tried using “setq-mode-local” (part of the CEDET package in standard GNU Emacs), like this:

`(setq-mode-local org-journal-mode org-tag-alist '(("@work" . ?w) ("@home" . ?h) ("laptop" . ?l)))`

…sadly, it doesn’t work. After evaluating that line, opening a new org-journal entry, and using “org-set-tags-command,” I get the normal completion interface instead of the fast tag selection interface.

**Comment by TinaRussell** [comment]
I think you misunderstand; I’m not wanting to have the tag selection come up when I create a new entry, like in #75 (though I might do that later). I want to be able to call org-set-tags-command myself and have a default selection of tags ready to use, one that is different from the tags set globally in org-tag-alist.

(Normally, when org-tag-alist is unset—like it is in my Emacs—org-set-tags-command will show a completion interface that tries to match previous tags in the file. When it is set, org-set-tags-command will show a fast tag selection interface, like the one used for TODO keywords. That’s what I meant by “I get the normal completion interface instead of the fast tag selection interface” as a failure state—it meant that Org or org-journal wasn’t seeing the value set by setq-mode-local.)

**Comment by bastibe** [comment]
I think I understand what you mean, now. Would [file-local variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Specifying-File-Variables.html) help with this?

You could set `org-tag-alist` in a file-local variable, and auto-insert the variable comment by modifying `org-journal-date-format`.

**Comment by TinaRussell** [comment]
So, I created a branch, “journal-tags,” to create something like this: it adds two new user options, `org-journal-tag-alist' and `org-journal-tag-persistent-alist,' which when set are used instead of `org-tag-alist' `org-tag-persistent-alist' for journal entries. The code’s been sitting in my config for a while and works quite well. Assuming it looks good to y’alls, um, how do I merge it with the master branch? :sweat_smile:

**Comment by cslux** [comment]
@TinaRussell Well, try it locally you can always go back ;-) using git-reset, git-branch and git-checkout

I would suggest to squash 51bdb34 into 82cabaf, as it belongs to the org-journal-tags implementation. For that use the interactive rebase git facility.
```bash
git checkout journal-tags
git rebase --interactive @~2
```

Now merge it into master
``` bash
git checkout master
git merge --no-ff journal-tags
# Resolve the conflicts
```
But you could also create a linear history using `rebase`.
``` bash
git checkout master
git rebase journal-tags
# Again you would need to resolve the same conflicts
```
I would do the squash, followed by the rebase, but if you want it to be reviewed, I would create a PR. In that case you need to rebase master into journal-tags. So bastibe can than merge it into master. 
``` bash
git checkout journal-tags
git rebase journal-tags
```

Cheers,
Christian

**Comment by bastibe** [comment]
@TinaRussell cool, that's a nice feature! As @cslux said, create a PR and we'll have a look!

**Comment by TinaRussell** [comment]
@cslux I’ve been trying to learn Magit… I think I succeeded in squashing the two commits together on my local `journal-tags` branch, doing an interactive rebase like you said, but I couldn’t push the changes to `origin\journal-tags` because…
```
 ! [rejected]        journal-tags -> journal-tags (non-fast-forward)
error: failed to push some refs to 'https://github.com/bastibe/org-journal.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
…and now I’m lost, because if I try to git pull it wants me to do a merge, with its own commit, and I thought the point of squashing was to consolidate commits… I should probably just make a pull request at this point like you and @bastibe suggested, I’m just curious to know what’s going on for my future knowledge. Thanks!

**Comment by cslux** [comment]
@TinaRussell Magit is worth learning it, it's truly a master peace.

Well, after your squash you have rewritten the history, your two commits have become one commit with a different hash number. Git is rejecting your push because you would overwrite the two commits on the remote branch with your single new one squashed commit on your local branch. But since that is what you want, use the flag `--force-with-lease` to overrule this massage, see also https://blog.carbonfive.com/2017/08/28/always-squash-and-rebase-your-git-commits/

The `--force|--force-with-lease` option should be taken with care.
