### ISSUE TITLE
Can add an interface to change the function org-journal-update-org-agenda-files () ?

### ISSUE THREAD

**Issue by wareslacker** [bastibe/org-journal#111]
I like org-journal , thanks for your great work .

sometimes i want to add the journal files to agenda , but current org-journal only "Adds the current and future journal files to org-agenda-files". 

Journal files before current day are not in agenda , and i set `org-journal-carryover-items` to `nil`。

Can add an interface to change the value ?

![orgjournal](https://user-images.githubusercontent.com/34468133/45138868-7a9ea800-b19d-11e8-8264-15445f9ddee5.JPG)

e.g. :
change (days-to-time 1) to (days-to-time 7) or (days-to-time 14) or (current-time) and so on.

**Comment by bastibe** [comment]
Cool idea! If you want to add a customization variable to this effect, I'd be grateful for a pull request.

**Comment by wareslacker** [comment]
I'm so sorry , I use Emacs, but i don't understand elisp,and i'm not a programer.so i hope to get your help.
Thanks you very much !

**Comment by bastibe** [comment]
I don't currently have time to do this. Since you found the place in the code that is the issue, you will no doubt be able to figure out how to add a customization variable.

Or maybe someone else is interested in helping?
