### ISSUE TITLE
Invoking org-journal from within org-mode doesn't work

### ISSUE THREAD

**Issue by dhruvparamhans** [bastibe/org-journal#113]
As the title suggests, invoking org-journal via `C-c C-j` doesn't open the current day's journal but opens a new window. 

Checking within org-mode, I found that `C-c C-j` is a key-binding to navigate within the org-file. 
[Relevant page here](https://orgmode.org/manual/Motion.html)

Is there a way around this?

**Comment by bastibe** [comment]
https://github.com/bastibe/org-journal#some-key-bindings-in-org-journal-overwrite-org-mode-key-bindings

**Comment by dhruvparamhans** [comment]
Oh okay. I should have looked there earlier. Apologies.
