### ISSUE TITLE
Agenda integration fails when org-agenda-files is set to a string

### ISSUE THREAD

**Issue by dds** [bastibe/org-journal#117]
Hi, 
In the function `org-journal-update-org-agenda-files`, it attempts to evaluate `org-agenda-files` expecting it to be a list. But I have `org-agenda-files` set to a string containing a filename with my agenda files. Simply replacing the direct access with `org-agenda-files` with a function with the same name fixes it. PR incoming.

**Comment by bastibe** [comment]
Cool, thank you very much! I didn't know `org-agenda-files` was available both as a variable and as a function.
