### ISSUE TITLE
C-c C-j conflicts with org-goto ?

### ISSUE THREAD

**Issue by kevzettler** [bastibe/org-journal#120]
I have just installed `org-journal` and seems `C-c C-j` is bound to `org-goto`?

```
C-c C-j runs the command org-goto (found in org-mode-map), which is an
interactive compiled Lisp function in ‘org.el’.

It is bound to C-c C-j, <menu-bar> <Org> <Navigate Headings> <Jump>.

(org-goto &optional ALTERNATIVE-INTERFACE)
```

**Comment by LifeWorks** [comment]
Is there any way to work around the conflict?

**Comment by bastibe** [comment]
You can switch from org-journal-mode to org-mode when editing. Apart from the missing keyboard shortcuts, this doesn't change anything.
