### ISSUE TITLE
How to open journal files without adding entry?

### ISSUE THREAD

**Issue by kevzettler** [bastibe/org-journal#121]
I am looking for a way to just open today's journal entry and not add a timestamp entry...

The documentation on `org-journal-new-entry` is confusing
https://github.com/bastibe/org-journal/blob/master/org-journal.el#L289-L298  

> "Open today's journal file and start a new entry.
> Giving the command a PREFIX arg will just open a today's file,
> without adding an entry. If given a TIME, create an entry for the
> time's day. If no TIME was given, use the current time (which is
> interpreted as belonging to yesterday if smaller than
> `org-extend-today-until`).

The documentation makes it sound like want to invoke it with a PREFIX

> Giving the command a PREFIX arg will just open a today's file,
> without adding an entry.

Great that's what I want.

I am invoking `C-u 0 M-x org-journal-new-entry` 
This still adds a new time stamp header entry to the file

**Comment by bastibe** [comment]
`C-u M-x org-journal-new-entry` should do the trick.

**Comment by kevzettler** [comment]
Thanks @bastibe that worked
