### ISSUE TITLE
saving a org journal file is very slow when having many org journal files in same dir 

### ISSUE THREAD

**Issue by vicky08** [bastibe/org-journal#122]
0.200.13@26.1 (spacemacs)
GNU Emacs 26.1 (build 1, x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 
 of 2018-05-31
Mac OS-X Mojave

Saving a daily journal in a directory with more than 180 days of daily journal is very slow. Have to wait for 8-10 seconds for emacs to become responsive. The cursor is just stuck.

Profiler results - 
- command-execute                                         486,269,578  85%
 - call-interactively                                     486,269,578  85%
  - funcall-interactively                                 486,269,578  85%
   - save-buffer                                          469,175,471  82%
    - basic-save-buffer                                   469,172,559  82%
     - run-hooks                                          468,569,401  82%
      - org-journal-redraw-calendar                       468,484,329  82%
       - org-journal-mark-entries                         343,341,067  60%
        - org-journal-list-dates                          343,308,939  60%
         - org-journal-list-files                         343,136,735  60%
          - seq-filter                                    333,684,747  59%
           - seq-map                                      333,684,747  59%
            - apply                                       333,684,747  59%
             + #<compiled 0x4142f905>                     333,684,747  59%
          - directory-files-recursively                     9,444,300   1%
           - directory-files-recursively                    9,317,116   1%
            + directory-files-recursively                   9,312,080   1%
            + file-name-all-completions                         2,112   0%
           + file-name-all-completions                         27,456   0%
          + file-truename                                       6,440   0%
            org-journal-dir-check-or-create                       200   0%
         + mapcar                                             172,204   0%
        + calendar-mark-visible-date                           30,016   0%
       - calendar-basic-setup                             125,140,556  22%
        - calendar-generate-window                        124,521,616  22%
         + #<compiled 0x40933a07>                         124,298,232  21%
         + calendar-generate                                  190,768   0%
         + calendar-update-mode-line                           29,328   0%
           calendar-cursor-to-visible-date                        160   0%
        + calendar-mode                                       618,940   0%
         #<compiled 0x40e2e5a1>                                 1,658   0%
       + calendar-exit                                          1,048   0%
      - flycheck-handle-save                                   83,024   0%
       + flycheck-buffer-automatically                         83,024   0%
        toc-org-insert-toc                                      2,048   0%
     + basic-save-buffer-1                                    403,214   0%
     + verify-visited-file-modtime                            187,712   0%
     + run-hook-with-args-until-success                        11,288   0%
       vc-before-save                                             248   0%
   + spacemacs/smex                                        16,495,537   2%
   + evil-next-line                                           564,858   0%
   + file-notify-handle-event                                  20,568   0%
   + evil-previous-line                                        13,144   0%
+ timer-event-handler                                      43,327,396   7%
+ redisplay_internal (C function)                          35,089,666   6%
+ ucs-normalize-hfs-nfd-post-read-conversion                  470,912   0%
+ ucs-normalize-hfs-nfd-pre-write-conversion                  190,960   0%
+ flyspell-post-command-hook                                   60,564   0%
+ which-key--hide-popup                                        20,805   0%
+ evil-normal-post-command                                     19,720   0%
+ evil-escape-pre-command-hook                                  6,144   0%
+ evil-repeat-post-hook                                         5,192   0%
+ eldoc-schedule-timer                                          2,112   0%
+ global-eldoc-mode-check-buffers                               1,056   0%
+ evil-mode-check-buffers                                       1,056   0%
+ global-evil-surround-mode-check-buffers                       1,056   0%
+ show-smartparens-global-mode-check-buffers                    1,056   0%
+ global-font-lock-mode-check-buffers                           1,056   0%
+ global-undo-tree-mode-check-buffers                           1,056   0%
+ global-evil-search-highlight-persist-check-buffers            1,056   0%
+ global-page-break-lines-mode-check-buffers                    1,056   0%
+ winner-save-old-configurations                                1,056   0%
+ flycheck-display-error-at-point-soon                            480   0%
  ...                                                               0   0%

**Comment by bastibe** [comment]
This is strange, my journal has almost 1000 files, and saving is instantaneous for me.

What version of org-journal are you running? SSD or HDD?

**Comment by vicky08** [comment]
Few things that might help - 
- I am using it with spacemacs.
- I am using it together with [spacemacs-journal](https://github.com/borgnix/spacemacs-journal.git), which just adds keybindings AFAIK.
- version of org-journal -  20181025.615

**Comment by bastibe** [comment]
Do you have any other files in your org-journal directory? Org-journal looks at the file names of all files in the org-journal directory and all its subdirectories.

**Comment by vicky08** [comment]
I do have other files in the org journal directory. Like images used in the journal etc...

More observations - When I change the mode to "Org" and save, it is very fast. If the mode is "Journal", then there is a huge delay.

**Comment by bastibe** [comment]
Org-journal needs to crawl all files in org-journal-dir and all its subdirectories, in order to find the journal files. This happens when saving, to update the calendar, and the agenda. A thousand or so journal files are no problem, but I would imagine it becoming a problem for very large numbers of files. Also, Emacs' functions for walking a directory tree might be slower on macOS.

**Comment by bastibe** [comment]
How many files are there, recursively, in your org-journal-dir? (including hidden files and directories)

**Comment by vicky08** [comment]
You are right. I had some folders which I was unaware of and they recursively added around 5000 files. When I removed the folder, it was fast. 

Thank you for your help! This is an awesome project. 
Closing this issue
