### ISSUE TITLE
Include past journal entries in the calendar

### ISSUE THREAD

**Issue by shrysr** [bastibe/org-journal#124]
I have several (~118) entries created using org journal. However, after fiddling around with the config and changing the filenames (formats) - I am no longer able to view the past entries in the Calendar. Is there some way to have the calendar recognise existing or past journal files?  At the moment, my only config is to specify org-journal-dir

**Comment by bastibe** [comment]
I assume you are talking about `M-x calendar`. After playing around, you probably ended up with mismatching file names and `org-journal-file-format`. What are the file names you are using?

**Comment by bastibe** [comment]
Can you show me your org-journal specific configuration?

**Comment by shrysr** [comment]
It appears the problems I was facing were related to the order of my startup scripts, though I do not yet know the exact cause. In any case, this was resolved today. org-journal is functioning as described in the documentation, rather to my delight. All past entries are visible in the calendar, and I think I understand it better. This issue can be closed!

**Comment by bastibe** [comment]
Thank you for following up on this.
