### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by engelmic** [bastibe/org-journal#126]
In trying to search journal entries using either org-journal-search or org-journal-search-forever, I get no results. I have tried both from the calendar and from a scratch buffer.
I am using Ubuntu 18.04 with emacs 25.2.2

**Comment by bastibe** [comment]
What is your config?

**Comment by engelmic** [comment]
Forgive me if my init is a mess - I am new to emacs and lisp.

```
(require 'package)

(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/"))

(setq package-enable-at-startup nil)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(package-selected-packages
   (quote
    (org-mode org-journal slime powerline-evil markdown-mode anaconda-mode helm evil))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

;; setting up evil with use-package
(use-package evil
  :ensure t
  :config
  (evil-mode t))

;;(use-package powerline-evil
;;  :ensure t)

;; the above code replaces this
;; (require 'evil)
;; (evil-mode t)

;; setting up helm with use-package
(use-package helm
  :ensure t
  :bind (("M-x" . helm-M-x)
         ("M-<f5>" . helm-find-files)
         ([f10] . helm-buffers-list)
         ([S-f10] . helm-recentf)))

(use-package ledger-mode
  :ensure t)

(use-package magit
  :ensure t
  :bind(("C-x g" . magit-status)))

;; setting up anaconda-mode
(use-package anaconda-mode
  :ensure t)
(add-hook 'python-mode-hook 'anaconda-mode)

;; set up slime
(use-package slime
  :ensure t)
(setq inferior-lisp-program "/usr/bin/clisp")
(setq slime-contribs '(slime-fancy))

;; Line Numbering
(global-linum-mode 1)

(use-package linum-relative
  :ensure t
  :config
  (linum-relative-mode t))

(setq linum-relative-current-symbol "")


;; load color theme
(load-theme 'adwaita)


;; Org-Mode things

(use-package org-journal
  :ensure t)
(require 'org-journal)
(setq org-journal-dir "~/journal")

;; setting up Org-Mode to execute Python code
(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)))

;; Save the running clock and all clock history when exiting Emacs, load it on startup
(setq org-clock-persist t)
;; Do not prompt to resume an active clock
(setq org-clock-persist-query-resume nil)
;; Enable auto clock resolution for finding open clocks
(setq org-clock-auto-clock-resolution (quote when-no-clock-is-running))
(setq org-clock-idle-time 999)

(setq org-todo-keywords
      '((sequence "TODO" "Blocked" "Developing" "Developed" "|"
		  "In-Pull-Req" "DONE")))
```

**Comment by bastibe** [comment]
Try using `(setq org-journal-dir "~/journal/")` (note the final `/`).

**Comment by engelmic** [comment]
That had no effect

**Comment by engelmic** [comment]
I had some errors in my init.el that I fixed (some things were imported both by the customizer and use-package), but I can't get search to return any results. I am more than willing to provide any necessary/pertinent debug/output/etc. I just don't know how to proceed.

**Comment by bastibe** [comment]
What file names are you using? Are they different from the file names created by org-journal-new-entry?

**Comment by engelmic** [comment]
I am using whatever org-journal creates by default. 20190104 for instance

**Comment by engelmic** [comment]
I have made all entries with M-x org-journal-new-entry

**Comment by bastibe** [comment]
How strange. Can you tell me the complete path to your journal files? What operating system are you running?

**Comment by engelmic** [comment]
journal path: /home/mike/journal/
OS - Ubuntu 18.04

**Comment by engelmic** [comment]
emacs 25.2.2
org is inbuilt, I think so I'm not sure

I found an individual who had this issue related to a "SCHEDULED:" statement, not sure if it is related:

[https://lists.gnu.org/archive/html/emacs-orgmode/2009-08/msg00923.html]

Sorry, I don't know enough about lisp to be of greater assistance.

Also, if I M-x org-journal-new-entry I get the "no year zero" message. I am presented with a buffer (in fundamental mode) with a date stamp:

* Sunday, 01/06/2019

If I save this (M-x save-buffer) and then M-x org-journal-new-entry I then get a time stamp, so the buffer is:

* Sunday, 01/06/2019

** 03:45 

Which is what I expected from the first M-x org-journal-new-entry.

**Comment by EFLS** [comment]
I'm having the same issue. No search results are found and neither do I see any highlighting in `M-x calendar`.

Also, is it normal that the files that are created don't have the `.org` extension?
So a new entry will be named `20190110` rather than `20190110.org`?
I found it strange that I have to activate `M-x org-mode` manually when a new file is created... (which I fixed with a hook, but that's probably not supposed to be needed)?

I'm running 26.1 and org-mode 9.2.

**Comment by EFLS** [comment]
Alright, so let me update again: I had changed the `org-journal-file-format` to `"%Y-%m-%d"`. Once I changed it back to its default and restarted emacs, org-journal works as expected, with `calendar` highlighting (and without the hooks to switch to org-mode).

I'll try to investigate further when it does and doesn't work at a future point in time...

**Comment by engelmic** [comment]
update on this:
If I remove this:
```
(setq org-journal-dir "~/journal/")
```
and allow it to use the default directory, then it seems to behave normally

Am i setting the directory wrong?

**Comment by engelmic** [comment]
OK, I think I have a theory.
On line 152 of org-journal.el, I found this:
```
(let ((dir (if (boundp 'org-journal-dir)
                        org-journal-dir
                      "~/Documents/journal/")))
```
Doesn't this if return True and set org-journal-dir  to "~/Documents/journal/" ONLY if it is already set?

**Comment by EFLS** [comment]
@engelmic Good catch, same here. I guess it that something is going wrong when the `org-journal-file-pattern` is being set. Unfortunately I currently have no time (and very limited elisp skills) to investigate this at the moment.

**Comment by bastibe** [comment]
@engelmic, you are certainly using it correctly. In fact, I have the very same line in my init.

Are you setting `org-journal-dir` before requiring org-journal?

**Comment by bastibe** [comment]
@EFLS great find!

That actually makes a lot of sense, since org-journal has customization hooks that update auxiliary variables if they are changed through customize, but aren't triggered by `setq`. This can also be circumvented by `setq`ing before `require`ing, but `customize-set-variable` is a more elegant solution!

**Comment by engelmic** [comment]
Sorry for the slow reply. In an effort to troubleshoot, I moved to emacs 26.1. This made the behavior completely different, so I have not tested any of the suggestions made after my last post. It is working for me now, though not as intended, I don't believe, but that is beyond the scope of this bug report. I may try these solutions on a vanilla install or a VM soon.

**Comment by EFLS** [comment]
> @EFLS great find!
> 
> That actually makes a lot of sense, since org-journal has customization hooks that update auxiliary variables if they are changed through customize, but aren't triggered by `setq`. This can also be circumvented by `setq`ing before `require`ing, but `customize-set-variable` is a more elegant solution!

Yeah that's what I expected, and I tried that in many different setups, but couldn't get it to work. But now with customize, it works perfectly. 
Maybe that needs to be added to the readme somewhere?

**Comment by EFLS** [comment]
I'd love to do that, which would be my very first contribution to a package through a PR. I'll probably get to that sometime later this week!

**Comment by cslux** [comment]
I think this can be closed!

**Comment by holzee** [comment]
I am not sure this issue is solved. Does not seem to work for me on Emacs 28

**Comment by cslux** [comment]
A  minimum working (non-working) configuration setup would be great.

```  emacs-lisp
(use-package org-journal
   :custom 
   (org-journal-dir "~/org/journal")
   :config
   (setq org-journal-date-format "%a %d/%m/%G"))
```
Would this configuration above reflect your org-journal setup?

Than  you have called `org-journal-search`? 

What is the content of ~/org/journal?

What is the value of the variable `auto-mode-alist`.

**Comment by holzee** [comment]
Sorry for my lapidary message. Here are further details on my **non-working** setup. Running GNU Emacs 28.0.50 built from source on MacOS 10.15.2 with [Castlemacs](https://github.com/freetonik/castlemacs) config.

Here is my custom.el file
```
(custom-set-variables
 '(org-journal-date-format "%a %d/%m/%G")
 '(org-journal-dir "~/org/journal/")
 '(org-journal-file-format "journal-%Y.org")
 '(org-journal-file-type 'yearly)
'(package-selected-packages
   '(org-journal)))

```
private.el file
```
(require 'org-journal)
```

`auto-mode-alist` has the current value 
```
("/Users/holzy/org/journal/journal-\\(?1:[0-9]\\{4\\}\\).org\\(\\.gpg\\)?\\'" . org-journal-mode)
 ("/Users/holzy/org/journal/\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)\\(\\.gpg\\)?\\'" . org-journal-mode)
```

Content of my journal file named `journal-2020.org`
```
* Wed 15/01/2020
:PROPERTIES:
:CREATED:  20200115
:END:
** 10:43 pam pam                                                      :test:
** 10:45 a new entry
* Thu 16/01/2020
:PROPERTIES:
:CREATED:  20200116
:END:
** 00:13 Should go to bed
```

Search is not working.

**Comment by cslux** [comment]
Please read the docstring of `org-journal-file-format`. I think it's a classical user error ;-)

**Comment by holzee** [comment]
Yippee. Thank you so much 😘
