### ISSUE TITLE
Error in org-journal due to org-version variable

### ISSUE THREAD

**Issue by vikrantrathore** [bastibe/org-journal#133]
In emacs 26.1 after installing org-journal from melpa using package installer emacs throws an error:

```
Symbol's value as variable is void: org-version
```

In the code in org-journal.el file it has a code which results in error:

```
62  ;;; Code:
63  (when (version< org-version "9.2")
64    (defalias 'org-set-tags-to 'org-set-tags))
```
I think error is with org-version and org-journal for emacs 26.1.

**Comment by bastibe** [comment]
I am running org-journal on emacs 26.1, myself. What version of org do you have installed? What is the value of `org-version` in your emacs?

**Comment by vikrantrathore** [comment]
> I am running org-journal on emacs 26.1, myself. What version of org do you have installed? What is the value of `org-version` in your emacs? How did you install org-journal?

I am running org-version "9.1.9"
Installed org-journal using package manager with melpa, gnu package repository.
org-journal version org-journal-20190121.909

On ctrl+c ctrl+j it still gives the same error as I said earlier org-version.

**Comment by ilkermutlu** [comment]
@vikrantrathore if you don't specifically need to stay on version `9.1.9`, upgrading `org` to `9.2` solved the issue for me.

**Comment by pmatos** [comment]
Same with org 9.1.14. Will try upgrade.

**Comment by pmatos** [comment]
org 9.2.1 now and still the same problem. If I do `org-version` manually and then try `org-journal` it works. Do I need to initialize org mode in my `.emacs` before starting `org-journal`? Using org-journal with `use-package`.

**Comment by bastibe** [comment]
Could this be an issue with use-package? I do not use use-package, on Emacs 26.1 and org 9.1.9 and don't see this issue.

**Comment by isaacngym** [comment]
Using org 9.2.1, encountering this. However when I recompile elpa I no longer get the error till I reopen emacs.

**Comment by pmatos** [comment]
I get the error, then I do `M-x org-version`, which works and then `C-c C-j` works.

**Comment by vikrantrathore** [comment]
I get the same thing after upgrading to 9.2 and recompile it starts to work. But when re-starting it doesn't work. Probably an issue with use-package and org-version setup, not sure. Even I tried to change the org-journal source in that specific line to always setup org-version as 9.2 it did not work.

**Comment by bastibe** [comment]
Does anyone have an idea how to fix this one? I do not...

**Comment by artyomboyko** [comment]
Same issue

**Comment by cslux** [comment]
Whoops! If org-journal.el is loaded before org.el you will get the error. 

We should add `(require 'org)` at the top.

**Comment by bastibe** [comment]
@cslux, thank you so much! If only I had known that the solution was this easy!
