### ISSUE TITLE
[question] open todays journal file without creating entry

### ISSUE THREAD

**Issue by pmatos** [bastibe/org-journal#134]
Is there a way to do this?

**Comment by EFLS** [comment]
Check out the documentation of `org-journal-new-entry`: it explains that with a prefix argument, today's file will be opened (instead of creating an entry).

So simply hit `C-u` and then your regular keybinding for `org-journal-new-entry`.

**Comment by pmatos** [comment]
Oh, the only docs I found were the readme file. Should have checked emacs docs. Thanks.
