### ISSUE TITLE
Make carry-over take marked items from the whole past, not  just the day before. 

### ISSUE THREAD

**Issue by mrvdb** [bastibe/org-journal#135]
I use org-journal daily and carry a list of tasks with the daily journal. Carry-over takes care of that. I have customized `org-journal-carryover-items` to:

```
org-journal-carryover-items "+carryover|+TODO=\"TODO\""
```

This works fine as long as every day has a journal. If I skip a day, the items are not carried and I have to dig them up from an earlier journal file manually

It would be helpful to either:
- look in all journal files in the past or 
- look back until items have been found or
- have a configurable nr of days to look back

**Comment by bastibe** [comment]
It should work for empty days as well. I use this all the time. Do you get any kind of error?

What doesn't work is if there was a day without journal entries that already had a scheduled (future) entry.

**Comment by mrvdb** [comment]
Perhaps an error, see below . The new journal file is created empty.  Glad to hear it should work, means I have done something wrong on my side.

Just reproduced it:
- last journal file `20190213.org`(which has one entry with `carryover` as tag
- `org-journal-new-entry` creates `20190215.org` with just the day header

*Messages* buffer has: `user-error: There was no year zero` ( I missed this the first time)

Tried again from scratch, but first issuing `org-reload` before `org-journal-new-entry` which made it work.

**Comment by bastibe** [comment]
Glad to hear you found a workaround.

I think this is related to #133.

**Comment by mrvdb** [comment]
Also, the same error is mentioned in #9  The loading issue there sounds similar to what I see here locally.

**Comment by shivekkhurana** [comment]
I have a different issue but the same fix works. New journal command opens a new file, but the timestamp is not added automatically.

I get the same error `user-error: There was no year zero` and `org-reload` fixes the issue. Here my config:
```elisp
;; Simple plain text journals that I'll mine someday for insights
(use-package org-journal
  :bind
  ("C-c n j" . org-journal-new-entry)
  :ensure t
  :config
  (setq  org-journal-file-format "%Y-%m-%d.org"
	 org-journal-dir "~/WIP/TimeMachine/"
	 org-journal-date-format "%A, %B %d, %Y"))
```

- I have already tried the fix mentioned in https://github.com/bastibe/org-journal/issues/133#issuecomment-465256227, added `(require 'org)` before org-journal config
- I have also tried using [`:after`](https://jwiegley.github.io/use-package/keywords/#after) keyword for `use-package` config, which basically ensures existence of a package before continuing.

None of the approaches work and I'm still not getting timestamps automatically.
Here is a video demo of the problem: https://imgur.com/a/woJnm98

What am I doing wrong? Do I need to `require` something apart from the config above?
I'm running emacs v26.3 on MacOS with org 9.3.6.


Thanks.

PS: Please let me know if I should open a new issue for my problem. 
PSPS: Org journal is amazing. Thanks for building this.

**Comment by cslux** [comment]
@shivekkhurana `org-journal-dir` need to be set before `org-journal` gets loaded, or use the `:custom` keyword of `use-package`. Not sure yet, if that is what causes the error, please let me know.

(use-package
  ...
  :custom (org-journal-dir "~/WIP/TimeMachine/")
  ...
)

**Comment by shivekkhurana** [comment]
Thanks for pointing that out @cslux. I updated my config to be:
```elisp|
(use-package org-journal
  :bind
  ("C-c n j" . org-journal-new-entry)
  :custom
  (org-journal-date-prefix "#+TITLE: ")
  (org-journal-file-format "%Y-%m-%d.org")
  (org-journal-dir "/path/to/org-roam-files/")
  (org-journal-date-format "%A, %d %B %Y"))
```
and now it seems to work.

**Comment by cslux** [comment]
This can be closed. It was due a bug. The items to carryover should always be carryed over from the last journal entry automatically even when there are empty days between the last and new journal entry.

Closing!
