### ISSUE TITLE
Subdirectories in `org-journal-file-format` don't work

### ISSUE THREAD

**Issue by ndw** [bastibe/org-journal#137]
Under "Journal Directory and Files", it says:

> org-journal-file-format - format string for journal file names (may contain directories relative to org-journal-dir).

But if I actually use directories:

``` lisp
(customize-set-variable 'org-journal-dir "~/Dropbox/Org/Journal/")
(customize-set-variable 'org-journal-file-format "%Y/%m/%d.org")
(customize-set-variable 'org-journal-date-format "%Y-%m-%d; %A %d %B %Y")

(require 'org-journal)
```

I find that `org-journal` doesn't create the intermediate directories "2019/02" in this case.

Bug or user error?

**Comment by ndw** [comment]
Mmm. I suppose that just typing `M-x make-directory RET RET` when the directory doesn't exist is reasonable enough. (I misunderstood that message when I first saw it.)

**Comment by bastibe** [comment]
So, you found a solution to your problem?

**Comment by ndw** [comment]
Yes. I left the issue open because I think it would be reasonable for the function that creates the journal to automatically create the necessary subdirectories. But if you don't feel like that's worth the trouble, feel free to close this.

If I get tired of typing `M-x make-directory RET RET` once a month, I may send you a patch 😄 in a month or two.

**Comment by bastibe** [comment]
I think "the Emacs way" is to not create directories (if you open a file in a nonexistent directory, Emacs will not create it automatically). 

But if this is an issue for you, I'd be happy to accept a pull request akin to [org-journal.el:292](https://github.com/bastibe/org-journal/blob/master/org-journal.el#L292)
