### ISSUE TITLE
When save journal entry it ask gpg key and related stuff

### ISSUE THREAD

**Issue by integerslab** [bastibe/org-journal#138]
Latest version from melpa at 25 feb ask me choice or enter gpg key when perform save - I don't need encryption and don't use it in org-journal. 

Please disable all this stuff by default. Thanks.

Forced to install previous version - elpa/org-journal-20190121.909. This version works as expected.

**Comment by bastibe** [comment]
I don't see this on my computer. Can you tell me when exactly this happens?

Also, can you make sure that you do not have `org-journal-enable-encryption` enabled?

**Comment by integerslab** [comment]
Here is my stuff:
```elisp
;; with my setting
(use-package org
  :config
  (provide 'org-habit)
  
  ;;; http://orgmode.org/manual/org_002dcrypt.html
  (require 'org-crypt)
  (org-crypt-use-before-save-magic)
  (setq org-tags-exclude-from-inheritance (quote ("crypt")))

  (setq org-crypt-key nil)
  ;; GPG key to use for encryption
  ;; Either the Key ID or set to nil to use symmetric encryption.

  (setq auto-save-default nil)
       ;; Auto-saving does not cooperate with org-crypt.el: so you need
       ;; to turn it off if you plan to use org-crypt.el quite often.
       ;; Otherwise, you'll get an (annoying) message each time you
       ;; start Org.

       ;; To turn it off only locally, you can insert this:
       ;;
       ;; # -*- buffer-auto-save-file-name: nil; -*-

  (require 'org-mouse)

)

(use-package org-journal
  ;; :after (org)
  ;; :requires org
  ;; :load-path "~/src/install/org-journal-initial"
  :init
  (setq org-journal-dir "~/my/org/journal")
  :config
  ;; (customize-set-variable 'org-journal-enable-encryption nil)
  ;; (customize-set-variable 'org-journal-encrypt-journal nil)
  ;; (customize-set-variable 'org-journal-encrypt-on nil)
  :bind (("<s-kp-divide>" . org-journal-new-entry)
         :map my-cmd-map
         ("C-c C-s" . org-schedule)
         ("j" . org-journal-new-entry)
         )
  )

(require 'org)
(require 'org-journal)
```

> Also, can you make sure that you do not have org-journal-enable-encryption enabled?

* Of course try it to disable but has no any effect

**Comment by amitp** [comment]
I have the same problem. `org-journal-encrypt-journal` is nil, `org-journal-enable-encryption` is nil, but when I open a new entry with `M-x org-journal-new-entry` it creates a gpg file instead of the regular file, and then asks about gpg keys.

I think the problem is that `org-journal-get-entry-path` adds ".gpg" to the file path if the file doesn't exist already. And that means for any new day, it will add ".gpg", which triggers the encryption system.

**Comment by amitp** [comment]
It is indeed that function. To test, I removed the ".gpg". It works when ".gpg" isn't on the filename.

```
(defun my/org-journal-encrypt-workaround (result)
  (s-replace ".gpg" "" result))
(advice-add 'org-journal-get-entry-path :filter-return #'my/org-journal-encrypt-workaround)
```

**Comment by cslux** [comment]
Sorry guys! This is may fault. b0f3d32 is the culprit. Creating a PR. A new version of `org-journal` will be available within the next 24 hours through MELPA.

**Comment by bastibe** [comment]
Thank you for finding this error, @integerslab, thank you for finding the offending function @amitp, and thank you for quickly fixing it, @cslux!
