### ISSUE TITLE
epg-context--make: GPG error: "no usable configuration", OpenPGP

### ISSUE THREAD

**Issue by vikrantrathore** [bastibe/org-journal#140]
Error while launching org-journal-entry using ctrl+c ctrl+j 

Gives an error 
```
epg-context--make: GPG error: "no usable configuration", OpenPGP
org-journal-file-name->calendar-date: Wrong type argument: arrayp, nil
```
org-journal version **org-journal-20190225.1106**

**Comment by zhd173** [comment]
I get the same error on Spacemacs org layer:

```shell
epg-context--make: GPG error: "no usable configuration", OpenPGP
```

- Emacs version : 26.1   
- OS : MacOS

**Comment by cslux** [comment]
@vikrantrathore Is your os MacOS too?

https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-08/msg00657.html

I probably need to disable the gpg org-journal file encryption on MacOS all together, hmm.

**Comment by cslux** [comment]
Hmm, this might very well be solved by PR #139 too.

**Comment by vikrantrathore** [comment]
> Hmm, this might very well be solved by PR #139 too.

Yes I am using macos
I changed the following snippets of code to make it work, I know this will result in not being able to use gpg by configuration. But I feel enabling a gpg for every file with encryption setting ignored is not ok.

```
;;;###autoload
(defun org-journal-dir-and-format->regex (dir format)
  "Update org-journal-file-pattern with the current
  org-journal-file-format"
  (concat
   (file-truename (expand-file-name (file-name-as-directory dir)))
   (replace-regexp-in-string
    "%d" "\\\\(?3:[0-9][0-9]\\\\)"
    (replace-regexp-in-string
     "%m" "\\\\(?2:[0-9][0-9]\\\\)"
     (replace-regexp-in-string
      "%Y" "\\\\(?1:[0-9]\\\\{4\\\\}\\\\)" format)))
"\\(\\.gpg\\)?\\'"))
```
to
```
;;;###autoload
(defun org-journal-dir-and-format->regex (dir format)
  "Update org-journal-file-pattern with the current
  org-journal-file-format"
  (concat
   (file-truename (expand-file-name (file-name-as-directory dir)))
   (replace-regexp-in-string
    "%d" "\\\\(?3:[0-9][0-9]\\\\)"
    (replace-regexp-in-string
     "%m" "\\\\(?2:[0-9][0-9]\\\\)"
     (replace-regexp-in-string
      "%Y" "\\\\(?1:[0-9]\\\\{4\\\\}\\\\)" format)))
   ))
```
and also changed 

```
(defun org-journal-get-entry-path (&optional time)
  "Return the path to an entry given a TIME.
If no TIME is given, uses the current time."
  (let ((file (file-truename
               (expand-file-name
                (format-time-string (concat org-journal-file-format) time)
                (file-name-as-directory org-journal-dir)))))
    (unless (file-exists-p file)
      (setq file (concat file ".gpg")))
file))
```
to 
```
(defun org-journal-get-entry-path (&optional time)
  "Return the path to an entry given a TIME.
If no TIME is given, uses the current time."
  (let ((file (file-truename
               (expand-file-name
                (format-time-string (concat org-journal-file-format) time)
                (file-name-as-directory org-journal-dir)))))
    file))
```

**Comment by cslux** [comment]
That wasn't indented. #139 will solve that.

On 27 February 2019 07:30:08 CET, vikrantrathore <notifications@github.com> wrote:
>> Hmm, this might very well be solved by PR #139 too.
>
>Yes I am using macos
>I changed the following snippets of code to make it work, I know this
>will result in not being able to use gpg by configuration. But I feel
>enabling a gpg for every file with encryption setting ignored is not
>ok.
>
>```
>;;;###autoload
>(defun org-journal-dir-and-format->regex (dir format)
>  "Update org-journal-file-pattern with the current
>  org-journal-file-format"
>  (concat
>   (file-truename (expand-file-name (file-name-as-directory dir)))
>   (replace-regexp-in-string
>    "%d" "\\\\(?3:[0-9][0-9]\\\\)"
>    (replace-regexp-in-string
>     "%m" "\\\\(?2:[0-9][0-9]\\\\)"
>     (replace-regexp-in-string
>      "%Y" "\\\\(?1:[0-9]\\\\{4\\\\}\\\\)" format)))
>"\\(\\.gpg\\)?\\'"))
>```
>to
>```
>;;;###autoload
>(defun org-journal-dir-and-format->regex (dir format)
>  "Update org-journal-file-pattern with the current
>  org-journal-file-format"
>  (concat
>   (file-truename (expand-file-name (file-name-as-directory dir)))
>   (replace-regexp-in-string
>    "%d" "\\\\(?3:[0-9][0-9]\\\\)"
>    (replace-regexp-in-string
>     "%m" "\\\\(?2:[0-9][0-9]\\\\)"
>     (replace-regexp-in-string
>      "%Y" "\\\\(?1:[0-9]\\\\{4\\\\}\\\\)" format)))
>   ))
>```
>and also changed 
>
>```
>(defun org-journal-get-entry-path (&optional time)
>  "Return the path to an entry given a TIME.
>If no TIME is given, uses the current time."
>  (let ((file (file-truename
>               (expand-file-name
>             (format-time-string (concat org-journal-file-format) time)
>                (file-name-as-directory org-journal-dir)))))
>    (unless (file-exists-p file)
>      (setq file (concat file ".gpg")))
>file))
>```
>to 
>```
>(defun org-journal-get-entry-path (&optional time)
>  "Return the path to an entry given a TIME.
>If no TIME is given, uses the current time."
>  (let ((file (file-truename
>               (expand-file-name
>             (format-time-string (concat org-journal-file-format) time)
>                (file-name-as-directory org-journal-dir)))))
>    file))
>```

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by bastibe** [comment]
I just merged #139, and the fix should land on Melpa within a day or so. Sorry for the inconvenience, and thank you all for your analysis and quick bug fix!

**Comment by vikrantrathore** [comment]
@bastibe @cslux 
This should be re-opened as today morning I tried using the new version with the code and still gives gpg error as I did not install gnupg on my mac.

I think it shouldn't give extension gpg when I do not want to encrypt. But the code still tries to create gpg file. 
In init.el for org-journal the settings set the encrypt to false still has an error.

```
(setq org-journal-file-format "%Y%m%d"
      org-journal-dir "~/Documents/daily_journal/"
      org-journal-encrypt-journal "")
```

I am now removing the gpg extension code to make it work again.

**Comment by cslux** [comment]
@vikrantrathore It's working, but your setting has a bug in it.

`org-journal-encrypt-journal` is of type 'boolean not 'string. In Emacs lisp
everything except nil and '() -- the empty list -- are true "t" values. Even the
empty string "".

https://www.gnu.org/software/emacs/manual/html_node/elisp/nil-and-t.html

**Comment by zhuanqizhirou** [comment]
If it's happening after updating emacs, find the file emacs/28.8/lisp/epg-config.el, search and change `(defconst epg-gpg2-minimum-version "2.1.6")`  version to 2.0.22
