### ISSUE TITLE
How to create a journal entry for a date in the past?

### ISSUE THREAD

**Issue by belugame** [bastibe/org-journal#141]
I'm still a emacs newby. What is the easiest way to create a journal entry for a day in the past or the future? Can I do that via the calendar or do I need to write my own function?

Thank you for your work! :+1:

**Comment by belugame** [comment]
Ah, just have to use `M-x org-journal-new-scheduled-entry`

**Comment by bastibe** [comment]
Or use the calendar and hit "i j".
