### ISSUE TITLE
First journal entry is always at top of file above carryover items

### ISSUE THREAD

**Issue by srtheartist-ia** [bastibe/org-journal#142]
The first journal entry of the day appears above the carryover items, and subsequent entries are below the carryover items.  The inconsistency bothers me and I can't figure out how to fix it.

I've tried inserting a (goto-char (point-max)) in the new entry function, and tried moving the new entry function under the one that inserts the carryover items.  No matter what I try, that firsrt new entry insists on being at the top of the file.  I'm sure it's a simple fix, I'm just don't know Lisp well enough, but I'm learning.

Each day I have to erase that first time stamp, go under the carryover items, and continue from t here.  It's cosmetic and not a big deal, it's just annoying.

Any ideas would be very much appreciated.

* Tuesday, 03/12/19...
  * 08:51  First new entry appears here
  * TODO from yesterday
  * STARTED from yesterday
  * WAIT from yesterday
  * 09:00 all other entries appear here

**Comment by cslux** [comment]
Hey @srtheartist-ia!

I implemented weekly, monthly and yearly journal file support. During that, I came across your mentioned issue and fixed that too. I'll create a PR for my weekly, monthly, yearly journal file implementation after I'm back from work and training.

https://github.com/cslux/org-journal/commit/e8dd8f178296d0cd7eee6034e9e51f82a116defb

**Comment by srtheartist-ia** [comment]
Fantastic, thank you.  I've been hoping for monthly file support as well.  I'm thankful for everyone's hard work - org-journal is a life saver. Good day to you.
