### ISSUE TITLE
All under first TODO is carried over

### ISSUE THREAD

**Issue by srtheartist-ia** [bastibe/org-journal#146]
emacs 25.2.2 / org 8.2.10 /
org-journal version is what I downloaded today
melpa stable

I've noticed some issues; I'm hoping they can be duplicated by others so I know I'm not insnae.

I tested using my custom init as well as a barebones default config with just require org and require org-journal.  

1.  Files created outside of emacs (nano, gedit, mousepad), or edited outside of emacs will not carryover correctly.  It's just plain text, so I don't see why it would make a difference.  

To duplicate:

create the following file in your org journal directory using nano or other editor saving it as yesterday's date

* Saturday, 03/16/2019
** text to keep on sat 1
** TODO task 1
** text to keep on this day 2
** TODO task 2
** text to keep on this day 3

Open emacs, then do C-c C-j (or whatever you have it bound to). 

In my testing, anything below the first TODO is carried over to Sunday if the file is created or edited outside of emacs.

2. A similar issue, related?

Test One:

I open emacs, 
create the same file manually for 'yesterday' in emacs,
save it using C-x C-s as 20190316,
then without closing the buffer for 20190316, I do C-c C-j,
carryover works like intended.

Test Two:

I open emacs,
create the same file manually for 'yesterday' in emacs,
save it as using C-c C-s as 20190316,
then I close the buffer, keep emacs open
do C-c C-j and
Everything below the first todo is carried over.

3.  first entry of the day is always placed at the top under the Date, instead of at the bottom, under the carryover items.

**Comment by bastibe** [comment]
Could you upload your file here? I'll see if I can reproduce your issue on my computer.

Your usage of another text editor might hint at an issue with line separators or file encodings. What operating system are you using?

Your third issue is a known issue. I currently don't have much time to work on it, but I'd be grateful for a pull request.

**Comment by cslux** [comment]
@bastibe I'm currently working on this issue,  and will create a test for it too.

**Comment by cslux** [comment]
Hmmm, works for me!

- org-version (9.2.2)
- emacs (26.1.92)

Before
``` 
* Friday, 03/15/19
:PROPERTIES:
:CREATED:  20190315
:END:
** 13:00
** TODO asdfsadf
** 14:00
** TODO asdasfd
** 15:00
```

After
``` 
* Friday, 03/15/19
:PROPERTIES:
:CREATED:  20190315
:END:
** 13:00
** 14:00
** 15:00
* Monday, 03/18/19
:PROPERTIES:
:CREATED:  20190318
:END:
** TODO asdfsadf
** TODO asdasfd
** 11:42  
```

Maybe it's due to a different org-version. I will test it with 8.2.10.

**Comment by srtheartist-ia** [comment]
@bastibe @cslux Most of the machines I use are xubuntu 18.04 or 18.10. I can upgrade org and see if that helps.  I'll cycle through the org-journal-file-type s to see if that makes a differnce.  I'm still using daily.  It works as intended on Fedora 29 (in Qubes), so it may be an org or xubuntu issue.

My intent isn't to complain, but to make you aware there may be issues.  If I was better with Lisp, I'd just work on it and post a solution.

Either way it's no big deal, moving the todo's to the bottom takes 2 seconds and that solves the problem to make it usable.  I'll try the upgrades.

**Comment by cslux** [comment]
@srtheartist-ia Yes please, test it with a more recent version of org. BTW, I added a test 86833edc354aefc319c6fd58d999c1460418ebab for your reported issue. You would need to evaluate the file `org-journal-test.el`, call `ert` and select the test `org-journal-carryover-items-test`

**Comment by srtheartist-ia** [comment]
On xubuntu I did fresh install, upgraded to emacs 26.1, org 9.1..., and the result is the same... using daily org-journal-file-type, any item below the first todo was carried over... 

I pulled out a new machine, installed fresh fedora 29 workstation, installed emacs 26.1, org 9.2.1... same results, it carries over any items below the first todo, so long as the items are above the todo items it leaves them where they belong.

I'm relatively new to emacs (if you couldn't tell), but I did try to evaluate the test file you posted... after installing use-package, bind-key, and filling in the paths, etc... i call ert and I keep getting a assumption failed error... sorry, I know my ignorance isn't helpful.

The only thing in my init is require package, with package archives, require org, require org-jounral, and require org-ecrypt, everything else is default.

I don't know what else to do, I create the test file in emacs, save it and kill the buffer, c-c c-j for new entry and it carries over anything under that first todo... the odd part is, if I create and save yesterday's file and leave the buffer open, then do a C-c C-j for new entry, it opens a new file for today and carry's the items over correctly.

I'm hoping this is helpful and not just wasting your time.  

I'm thankful for your help, when it's convenient

**Comment by cslux** [comment]
Strange! Can you post your org-journal setup please?

**Comment by srtheartist-ia** [comment]
`
(require 'package)
(setq package-archives
      '(("melpa" . "https://melpa.org/packages/")
        ("gnu" . "https://elpa.gnu.org/packages/")
        ("org" . "http://orgmode.org/elpa/")))
(package-initialize)

(require 'org)
(require 'org-journal)
(require 'org-crypt)
     (org-crypt-use-before-save-magic)
     (setq org-tags-exclude-from-inheritance (quote ("crypt")))
     
     (setq org-crypt-key "email")
       ;; GPG key to use for encryption
       ;; Either the Key ID or set to nil to use symmetric encryption.
       
     (setq auto-save-default nil)
       ;; Auto-saving does not cooperate with org-crypt.el: so you need
       ;; to turn it off if you plan to use org-crypt.el quite often.
       ;; Otherwise, you'll get an (annoying) message each time you
       ;; start Org.
     
       ;; To turn it off only locally, you can insert this:
       ;;
;; # -*- buffer-auto-save-file-name: nil; -*-
`

**Comment by cslux** [comment]
Found the bug! Pushing shortly! Thank you for your patience.

**Comment by srtheartist-ia** [comment]
Thanks for your time and hard work.  Monthly file support is fantastic!

**Comment by vitorqb** [comment]
hello @cslux. I cloned the repo at the master branch which has your commit (06f2f4c), added it to my load-path and required. I'm still seeing the issue there, which all items after the first TODO being carried over. I tracked it down to `(org-journal-extract-current-subtree)` miss behaving when the file is entirely hidden by the outline.

For example, if I open 20190320 and I expand the outline, like this:
```
* Wednesday, 03/20/2019
** TODO https://jakemccrary.com/blog/2016/06/20/my-recommended-clojure-testing-setup/
** 17:52 Working on blabla
** 18:02 Working on blablabla
```

And I call `org-journal-new-entry` (and it creates the 20190321) it works fine. However, If I open with it all hidden


```
* Wednesday, 03/20/2019...
```

And I call `org-journal-new-entry` then the bug persists, because `(org-journal-extract-current-subtree)` marks everything after the TODO and brings to the new 20190321 file.

I can try to make a PR later, when I have some time available. Let me know if you would like that.

**Comment by cslux** [comment]
@vitorqb Can you try it with the latest push please! Thank you!

**Comment by srtheartist-ia** [comment]
For me, issue remains when org-journal-file-type is set to daily.  With weekly and monthly (didn't test yearly), open emacs, C-c C-j opens the file, but I have to repeat the org-journal-new-entry to get them to carryover.

**Comment by cslux** [comment]
@srtheartist-ia @vitorqb Pushed another commit right now! 

Sorry and thank you for testing it.

I really hope this is now solved :-)

**Comment by vitorqb** [comment]
Thank you @cslux  for your contributions to org-journal, it is one of those simple packages that completely changed my workflow for better.

I tested with the new commit and it seems to be working properly :). I may have more time to test it later and I will let you know if I find anything miss behaving again.

**Comment by cslux** [comment]
@vitorqb Welcome! 

Glad to here it's working now! Thanks for testing.

**Comment by srtheartist-ia** [comment]
@cslux thank you, this works great for me.  I extended my testing a bit, as I plan, later, to go beyond using just TODO and DONE.

If I:

(setq org-todo-keywords 
       '((sequence "TODO(t)" "WAIT(w@/!)" "STARTED(s@/!)" "|" "DONE(d!)" "CANCELED(c@)")))

or without a sequence, the current commit only carries over the items marked TODO, and leaves the WAIT and STARTED items on previous day.

**Comment by cslux** [comment]
I think you  need to adopt  =org-journal-carryover-items= to make it work.

**Comment by cslux** [comment]
@srtheartist-ia 

This should do the trick:
``` emacs-lisp
(setq org-journal-carryover-items "/TODO|WAIT|STARTED")
```

**Comment by srtheartist-ia** [comment]
@cslux, thanks.  I was testing so many things, switching version, I forgot to set the variable... everything works great on my end, thanks again
