### ISSUE TITLE
org-journal-mode files not in 'org-mode'

### ISSUE THREAD

**Issue by weverett** [bastibe/org-journal#15]
I'm trying to pull To-do's from my agenda files which included my journal directory, but I'm getting the error "Agenda file /home/will/Journal/20131223 is not in `org-mode' When I scroll through the journal files that are loaded into buffers, I see that all of them are in fundamental mode rather than Journal mode for some reason. 

Relevant part of emacs config:

```
    (require 'cl)
    (require 'org-journal)
    (add-to-list 'org-agenda-files (expand-file-name "~/Journal"))
    (setq org-agenda-file-regexp "\\`[^.].*\\.org\\'\\|[0-9]+")
```

I manually added the change that ramLlama authored to org-journal.el and now when I try to get a full agenda, all of the journal files are correctly loaded in Journal mode, but I still get the error that they're not in `org-mode'.

**Comment by rickardsundin** [comment]
A quick note three years later...

For me, the configuration at top works better if the last line is modified to be
```
(setq org-agenda-file-regexp "\\`[^.].*\\.org\\'\\|\\`[0-9]+\\'")
```
which I think matches all filenames that ends with `.org` and all filenames that consists _only_ of numbers. The version above seems to match all filenames _containing_ numbers.

**Comment by bastibe** [comment]
If I'm not mistaken, this is what the README recommends as of 4876bbc7cd3129f6285f41b9076c178d30720163 (two months ago). There have been many iterations on this regex, and I still don't quite understand why some permutations work better than others despite being seemingly identical.

**Comment by MBuchaus** [comment]
this has again raised it's head.  Using spacemacs and have eval-after-load of org-journal then load the agenda-file regexp  and still receive the file is not in org mode.    is there a way to  put the header info in the file or another regex add-to list?

**Comment by txtyash** [comment]
Why do org-journal files not have a `.org` extension? This breaks org agenda.
