### ISSUE TITLE
org-journal-open-entry fails if a daily journal file doesn’t begin with a headline

### ISSUE THREAD

**Issue by TinaRussell** [bastibe/org-journal#150]
In `org-journal-open-entry`:
```
(goto-char (point-min))
(unless (org-journal-daily-p)
    (re-search-forward
     (format " *:CREATED: *%.4d%.2d%.2d" (nth 2 date) (car date) (cadr date))))
(org-journal-finalize-view)
```
With my config, `org-journal-daily-p` is t, so the `unless` block here is skipped and `org-journal-finalize-view` is run with point at the beginning of the buffer.
Then `org-journal-finalize-view`, in turn, runs `outline-back-to-heading`, which produces an error if point is before the first headline. So, with point at minimum, this will produce an error unless the very first line is a headline; this is ensured with the default setting of `org-journal-date-prefix`, which is "* ", but I have it set to "#+TITLE: ", which is why I noticed the problem.

**Comment by cslux** [comment]
I see! While testing with `org-journal-date-prefix` set to "#+TITLE: " I discovered that setting `org-journal-date-prefix` to something other than "* " want work for weekly/monthly/yearly journal files, unless someone writes a custom org-mode :-). But for daily journal files this should be doable.

**Comment by cslux** [comment]
Have you changed the value of `org-journal-time-prefix` too? Just curious!

**Comment by TinaRussell** [comment]
Yep, it’s set to "* ", so that each time entry is a level-1 heading.

**Comment by cslux** [comment]
Makes sense :-)

**Comment by snuffop** [comment]
This seems to have crept back up again..

**Comment by cslux** [comment]
@snuffop Does this happen with the latest version 20200226.1125 too? If yes, can you post your org-journal setup please.
