### ISSUE TITLE
Non-existent agenda file  [R]emove from list or [A]bort?

### ISSUE THREAD

**Issue by anthrolisp** [bastibe/org-journal#152]
Whenever org-journal creates a new file for entry I get the following (error) messages. I'm using EMACS 26.1 on ArchLinux.

(New file)
No previous journal entry before this one
Non-existent agenda file ~/Dropbox/org/journal/20190325.  [R]emove from list or [A]bort?
Saving file /home/name/Dropbox/org/journal/20190325...
Wrote /home/name/Dropbox/org/journal/20190325

I also just noticed that the first entry after file creation does not include "** TIME" but all subsequent entry attempts do.

CONFIG:
(use-package org-journal
  :ensure t
  :after org
  :custom
  (org-journal-dir "~/Dropbox/org/journal"))
    (setq org-journal-file-type 'weekly)
    (setq org-journal-enable-agenda-integration t)

**Comment by anthrolisp** [comment]
Not sure if this is related, but org-mode TODO keywords not recognized unless journal file ending is set to .org

**Comment by anthrolisp** [comment]
Is this fixed in Master? Many thanks in advance!

**Comment by cslux** [comment]
@anthrolisp Yes!

**Comment by cslux** [comment]
These are the changes https://github.com/bastibe/org-journal/commit/64183868033dd1aebe08b8722cb9ffd72b14198c.

**Comment by anthrolisp** [comment]
Thank you!

**Comment by cslux** [comment]
Welcome!
