### ISSUE TITLE
Can't use C-u C-c C-j anymore and all items are carried over

### ISSUE THREAD

**Issue by pmatos** [bastibe/org-journal#154]
Hi,

I recent updated my `org-journal` version to take advantage of the merge of #136. However, since I did so, all items are carried over, not just the TODOs. Also C-u C-c C-j does not work.

I start `org-journal` using `use-package` as:
```
;; org journal
(use-package org-journal
  :ensure t
  :defer t
  :custom
  (org-journal-dir "~/Dropbox/org/journal/")
  (org-journal-hide-entries-p nil)
  (org-journal-date-format "%A, %d %B %Y"))
```

Trying to `describe-function` `org-journal-new-entry` does not show it being bound to anything.

**Comment by cslux** [comment]
@pmatos You have set `defer` to `t`. Either remove it, or set it to, e.g. 0.5.

**Comment by cslux** [comment]
@pmatos  But you could also use the `:bind` keyword to bind C-c C-j to `org-journal-new-entry`.
``` emacs-lisp
(use-package org-journal
    :ensure t
    :bind (("<f9> s" . org-journal-search)
           ("C-c C-j" . org-journal-new-entry))
    :custom
    (org-journal-dir "~/Dropbox/org/journal/")
    (org-journal-hide-entries-p nil)
    (org-journal-date-format "%A, %d %B %Y"))
```
This would defer loading of org-journal until `C-c C-j` or `<f9> s` is pressed.

**Comment by cslux** [comment]
@

> However, since I did so, all items are carried over, not just the TODOs

Can't reproduce it with ab024dff9774caad814ab2dd674773179275e129

**Comment by bastibe** [comment]
@pmatos does removing or changing the `defer` fix your issue?

**Comment by pmatos** [comment]
@bastibe Thanks, @cslux solution works. Thanks.

**Comment by cslux** [comment]
@pmatos You're welcome!
