### ISSUE TITLE
Before first headline at position 1 in buffer  {previous day} 

### ISSUE THREAD

**Issue by snuffop** [bastibe/org-journal#156]
I've come across a new error with the latest version of org-journal and spacemacs develop 
On attempt to add new journal entry I get the error..  Debug below

       org-journal-date-format "%A, %B %d %Y"
       org-journal-date-prefix "#+TITLE: Daily Notes for "
       org-journal-dir "~/Notes/org/journal/"
       org-journal-enable-agenda-integration t
       org-journal-time-format "%K:%M "
       org-journal-time-prefix "** "

GNU Emacs 26.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.8) of 2019-04-12

Debugger entered--Lisp error: (error "Before first headline at position 1 in buffer 20190414")
  signal(error ("Before first headline at position 1 in buffer 20190414"))
  error("Before first headline at position %d in buffer %s" 1 #<buffer 20190414>)
  org-back-to-heading(t)
  #f(compiled-function () (interactive nil) #<bytecode 0x3289be9>)()
  apply(#f(compiled-function () (interactive nil) #<bytecode 0x3289be9>) nil)
  org-narrow-to-subtree()
  (progn (setq prev-entry-buffer (current-buffer)) (org-narrow-to-subtree) (mapc (function (lambda (carryover-path) (setq carryover-items-non-parents (cons (car carryover-path) carryover-items-non-parents)) (mapc (function (lambda (heading) (if ... nil ...))) carryover-path))) (org-map-entries mapper org-journal-carryover-items)) (setq carryover-items-with-parents (sort carryover-items-with-parents (function (lambda (x y) (< (car x) (car y)))))))
  (if (let ((inhibit-message t)) (org-journal-open-previous-entry (quote no-select))) (progn (setq prev-entry-buffer (current-buffer)) (org-narrow-to-subtree) (mapc (function (lambda (carryover-path) (setq carryover-items-non-parents (cons (car carryover-path) carryover-items-non-parents)) (mapc (function (lambda ... ...)) carryover-path))) (org-map-entries mapper org-journal-carryover-items)) (setq carryover-items-with-parents (sort carryover-items-with-parents (function (lambda (x y) (< (car x) (car y))))))))
  (save-restriction (if (let ((inhibit-message t)) (org-journal-open-previous-entry (quote no-select))) (progn (setq prev-entry-buffer (current-buffer)) (org-narrow-to-subtree) (mapc (function (lambda (carryover-path) (setq carryover-items-non-parents (cons ... carryover-items-non-parents)) (mapc (function ...) carryover-path))) (org-map-entries mapper org-journal-carryover-items)) (setq carryover-items-with-parents (sort carryover-items-with-parents (function (lambda (x y) (< ... ...))))))))
  (save-excursion (save-restriction (if (let ((inhibit-message t)) (org-journal-open-previous-entry (quote no-select))) (progn (setq prev-entry-buffer (current-buffer)) (org-narrow-to-subtree) (mapc (function (lambda (carryover-path) (setq carryover-items-non-parents ...) (mapc ... carryover-path))) (org-map-entries mapper org-journal-carryover-items)) (setq carryover-items-with-parents (sort carryover-items-with-parents (function (lambda ... ...))))))))
  (let* ((org-journal-find-file (quote find-file)) (mapper (function (lambda nil (let ((headings ...)) (setq org-map-continue-from (point)) headings)))) carryover-items-with-parents carryover-items-non-parents prev-entry-buffer) (save-excursion (save-restriction (if (let ((inhibit-message t)) (org-journal-open-previous-entry (quote no-select))) (progn (setq prev-entry-buffer (current-buffer)) (org-narrow-to-subtree) (mapc (function (lambda ... ... ...)) (org-map-entries mapper org-journal-carryover-items)) (setq carryover-items-with-parents (sort carryover-items-with-parents (function ...))))))) (if carryover-items-with-parents (progn (if (org-journal-org-heading-p) (progn (outline-end-of-subtree))) (if (eq (current-column) 0) nil (insert "\n")) (mapc (function (lambda (x) (insert (cdr ...)))) carryover-items-with-parents) (save-current-buffer (set-buffer prev-entry-buffer) (mapc (function (lambda (x) (kill-region ... ...))) carryover-items-non-parents) (save-buffer) (if org-journal--kill-buffer (progn (kill-buffer)))))))
  org-journal-carryover()
  (progn (org-journal-carryover))
  (if (and org-journal-carryover-items (string= entry-path (org-journal-get-entry-path (current-time)))) (progn (org-journal-carryover)))
  (let* ((entry-path (org-journal-get-entry-path time)) (should-add-entry-p (not prefix))) (if (string= entry-path (buffer-file-name)) nil (funcall org-journal-find-file entry-path)) (let ((entry-header (if (functionp org-journal-date-format) (funcall org-journal-date-format time) (concat org-journal-date-prefix (format-time-string org-journal-date-format time))))) (goto-char (point-min)) (if (search-forward entry-header nil t) nil (if (org-journal-daily-p) nil (let ((date (decode-time time)) (dates (sort ... ...)) found) (setq date (list (nth 4 date) (nth 3 date) (nth 5 date))) (while dates (if (calendar-date-compare dates ...) (progn ... ... ... ...)) (setq dates (cdr dates))) (if found nil (goto-char (point-max)) (forward-line)))) (if (looking-back "[^\011 ]" (point-at-bol)) (progn (insert "\n"))) (beginning-of-line) (insert entry-header) (if (org-journal-daily-p) nil (org-set-property "CREATED" (format-time-string "%Y%m%d" time))) (if org-journal-enable-encryption (progn (if (member org-crypt-tag-matcher (org-get-tags)) nil (org-set-tags org-crypt-tag-matcher)))))) (org-journal-decrypt) (if (and org-journal-carryover-items (string= entry-path (org-journal-get-entry-path (current-time)))) (progn (org-journal-carryover))) (if (org-journal-org-heading-p) (outline-end-of-subtree) (goto-char (point-max))) (if should-add-entry-p (progn (if (eq (current-column) 0) nil (insert "\n")) (let* ((day-discrepancy (- (time-to-days ...) (time-to-days time))) (timestamp (cond (... ...) (... ...) (t "")))) (insert org-journal-time-prefix timestamp)) (run-hooks (quote org-journal-after-entry-create-hook)))) (if (and org-journal-hide-entries-p (org-journal-time-entry-level)) (outline-hide-sublevels (org-journal-time-entry-level)) (save-excursion (org-journal-finalize-view))) (if should-add-entry-p (progn (outline-show-entry))))
  (let (oetu-active-p) (let ((now (decode-time nil))) (if (and (not time) (< (nth 2 now) org-extend-today-until)) (setq oetu-active-p t time (encode-time (nth 0 now) (nth 1 now) (nth 2 now) (1- (nth 3 now)) (nth 4 now) (nth 5 now) (nth 8 now))))) (let* ((entry-path (org-journal-get-entry-path time)) (should-add-entry-p (not prefix))) (if (string= entry-path (buffer-file-name)) nil (funcall org-journal-find-file entry-path)) (let ((entry-header (if (functionp org-journal-date-format) (funcall org-journal-date-format time) (concat org-journal-date-prefix (format-time-string org-journal-date-format time))))) (goto-char (point-min)) (if (search-forward entry-header nil t) nil (if (org-journal-daily-p) nil (let ((date ...) (dates ...) found) (setq date (list ... ... ...)) (while dates (if ... ...) (setq dates ...)) (if found nil (goto-char ...) (forward-line)))) (if (looking-back "[^\011 ]" (point-at-bol)) (progn (insert "\n"))) (beginning-of-line) (insert entry-header) (if (org-journal-daily-p) nil (org-set-property "CREATED" (format-time-string "%Y%m%d" time))) (if org-journal-enable-encryption (progn (if (member org-crypt-tag-matcher ...) nil (org-set-tags org-crypt-tag-matcher)))))) (org-journal-decrypt) (if (and org-journal-carryover-items (string= entry-path (org-journal-get-entry-path (current-time)))) (progn (org-journal-carryover))) (if (org-journal-org-heading-p) (outline-end-of-subtree) (goto-char (point-max))) (if should-add-entry-p (progn (if (eq (current-column) 0) nil (insert "\n")) (let* ((day-discrepancy (- ... ...)) (timestamp (cond ... ... ...))) (insert org-journal-time-prefix timestamp)) (run-hooks (quote org-journal-after-entry-create-hook)))) (if (and org-journal-hide-entries-p (org-journal-time-entry-level)) (outline-hide-sublevels (org-journal-time-entry-level)) (save-excursion (org-journal-finalize-view))) (if should-add-entry-p (progn (outline-show-entry)))))
  org-journal-new-entry(nil)
  funcall-interactively(org-journal-new-entry nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)

**Comment by cslux** [comment]
Hey Marty!

Sorry, and thanks for the report.

Fixed via 278e91a.

**Comment by snuffop** [comment]
yay  Danke

**Comment by davelnewton** [comment]
Curiously I am suddenly getting this same error (`org-journal 2.1.2`) for no apparent reason; Emacs config untouched. If I can't resolve it I'll update w/ details.

**Comment by psamim** [comment]
I also started to get this error without any change in configuration. I am using Doom emacs. I get this when I want to open a journal entry from calendar.

**Comment by madorian** [comment]
I'm getting this error whenever I try to open a new entry.
