### ISSUE TITLE
Request: mention using org-journal with `develop` Spacemacs

### ISSUE THREAD

**Issue by LemmingAvalanche** [bastibe/org-journal#157]
According to [this issue](https://github.com/ruibinx/spacemacs-journal/issues/5) on spacemacs-journal:

> If your using the develop branch in spacemacs you can enable org-journal and configure it:
>
> Docs: https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org#org-journal-support

The readme already points to spacemacs-journal on the topic of using org-journal with Spacemacs.  Maybe it could also mention using org-journal with `develop` Spacemacs (as opposed to stable (`master`) Spacemacs).

**Comment by cslux** [comment]
Thanks @LemmingAvalanche for your feedback! I have updated the readme. https://github.com/bastibe/org-journal/commit/5881c21588fda47059b8be8d0d66333f8d7f3b5b
