### ISSUE TITLE
Current day not being included when org-journal-enable-agenda-integration is t

### ISSUE THREAD

**Issue by FryJay** [bastibe/org-journal#158]
I recently updated org-journal to the latest and noticed that events entered for the current day were not appearing in the agenda.  Future days are still appearing.  I looked at org-agenda-files and found that only future dated journal files were being included.  

It looks like the issue was introduced by 786f611 as I reverted the code in that particular commit and the issue went away.

**Comment by cslux** [comment]
@FryJay Thanks for the report. It got fixed by https://github.com/bastibe/org-journal/commit/4798f2f4865229a1b93881d31fcee6680fdf0c99.

**Comment by FryJay** [comment]
@cslux that appears to have fixed it.  Thanks for the quick fix!
