### ISSUE TITLE
There was no year zero on org-journal-new-entry with carry-over items

### ISSUE THREAD

**Issue by markusalbertgraf** [bastibe/org-journal#162]
# Thank you for org-journal!!!

I use daily journal files and carryover (on freebsd).

When I use that the first time a day all works fine.  But after a reboot org-journal-new-entry results in ```user-error "There was no year zero"```.

## A cleaned trace
user-error("There was no year zero")
calendar-date-compare(((5 24 2019)) ((0 0 0)))
org-journal-open-entry("No previous journal entry before this one" t no-select)
org-journal-open-previous-entry(no-select)
org-journal-carryover()
org-journal-new-entry(nil)

## Probable cause
org-journal-open-entry compares (org-journal-file-name->calendar-date (buffer-file-name)) to org-journal-file-pattern.  The latter uses ```file-truename```, the former does not.  So ```/usr/home/me``` gets compared to ```/home/me```.

## Suggested fix
Replacing (buffer-file-name) with (file-truename (buffer-file-name)) seems to fix this on my machine.

## Here as patch:
```
--- /home/markus/.emacs.d/backups/!usr!home!markus!.emacs.d!elpa!org-journal-20190517.1443!org-journal.el~	2019-06-07 16:06:32.100361000 +0200
+++ /usr/home/markus/.emacs.d/elpa/org-journal-20190517.1443/org-journal.el	2019-06-11 20:17:03.300650000 +0200
@@ -702,7 +702,7 @@
 
 If no next/PREVious entry was found print MSG."
   (let ((calendar-date (if (org-journal-daily-p)
-                           (org-journal-file-name->calendar-date (buffer-file-name))
+                           (org-journal-file-name->calendar-date (file-truename (buffer-file-name)))
                          (org-journal-goto-journal-heading)
                          (org-journal-entry-date->calendar-date)))
         (view-mode-p view-mode)
```

**Comment by cslux** [comment]
@markusalbertgraf  Thank you! Resolved with 159794a, as suggested by you.
