### ISSUE TITLE
Not found via Melpa

### ISSUE THREAD

**Issue by Spoowy** [bastibe/org-journal#163]
On install via package-install I get a not-found error.

![Bildschirmfoto 2019-07-30 um 16 42 22](https://user-images.githubusercontent.com/6298122/62139099-099e3c80-b2e9-11e9-8dbb-36c20268c0ab.png)

Cheers,
Erwin

**Comment by cslux** [comment]
This has nothing to do with org-journal. This is a package.el thing. Restart emacs and try again, also try to update the package.el cache.


Regards,

Christian 

On July 30, 2019 2:43:04 PM UTC, Spoowy <notifications@github.com> wrote:
>On install via package-install I get a not-found error.
>
>![Bildschirmfoto 2019-07-30 um 16 42
>22](https://user-images.githubusercontent.com/6298122/62139099-099e3c80-b2e9-11e9-8dbb-36c20268c0ab.png)
>
>Cheers,
>Erwin

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by cslux** [comment]
@Spoowy Does it work again?

**Comment by Spoowy** [comment]
@cslux yep! Thanks.
