### ISSUE TITLE
Focus search results window immediately after search

### ISSUE THREAD

**Issue by jackbaty** [bastibe/org-journal#164]
After executing a search (C-c C-s) the results are shown in a new (or separate) window, but the insertion point remains in the original journal entry. Since I _always_ navigate within the results after a search, I would find it more convenient to have the focus/insertion point move automatically to the results window.

Is there a way to make that happen?

**Comment by cslux** [comment]
Currently this is not possible. This however, sounds like an upcoming default
behavior :-).

**Comment by cslux** [comment]
@jackbaty Hey @jackbaty! I have created a more polished search result buffer. Let me know if you like it or anything is missing.

**Comment by jackbaty** [comment]
This is great, thanks! My only comment is that when I have a large frame with several vertical windows, the results seem to show in unexpected places.

For example, I have a maximized frame split vertically into 2 windows.

With an org-journal entry in a buffer in the right window, I search (`C-c C-s`), and the results show in the current window, with the cursor at the first result, and the actual entry of that result in a split window below it. So far, perfect. If I move the cursor to the second result (using `n`), the selected (2nd) result entry is opened in a new split window at the bottom of the _left_ window. I now have 4 windows. Continuing to move down the results (still using `n`), the result entries are all shown in the bottom right window, as expected.

Hope that makes sense. The only real problem with this is that I end up with 3 org-journal buffers in 3 windows: top right (where I started), bottom right (the last result I looked at), and bottom left (the _first_ result I looked at).

Still a huge improvement, so I'm not complaining! :)

**Comment by cslux** [comment]
I understand what is going on, unfortunately I can't reproduce it. For me all result buffers are shown in the same window. Maybe it has something to do with some emacs configuration (https://www.gnu.org/software/emacs/manual/html_node/emacs/Window-Choice.html). At the moment I honestly don't know what is going on here :-/.

**Comment by jackbaty** [comment]
I hadn't considered that it might be a configuration somewhere else. I'll poke around and let you know if I figure it out. Otherwise, thanks for the improvements!
