### ISSUE TITLE
non-journal org functions not working when org-journal-dir points to non-existent directory

### ISSUE THREAD

**Issue by vibrys** [bastibe/org-journal#165]
I share emacs config between work and home.

While at home i use org-journal, at work I don't. As a consequence, 'org-journal-dir' directory does not exist at work and when I try to put timestamp (with 'org-time-stamp-inactive'), it fails with "Journal directory /media/mkwap/health/seszyt/journal/ not found. Create one? " message. Following is the stack trace. This action succeeds when org-journal is not installed.

  ```yes-or-no-p("Journal directory /media/mkwap/health/seszyt/journal/ not found. Create one? ")
  org-journal-dir-check-or-create()
  org-journal-list-files()
  org-journal-list-dates()
  org-journal-mark-entries()
  run-hooks(calendar-today-visible-hook)
```

Can org-journal act as inactive when 'org-journal-dir' does not exist?

**Comment by cslux** [comment]
Questions, why is org-journal installed at work?

Can you post your org-journal setup please. I'm sure we find a solution than.

-Chris

On August 15, 2019 12:48:05 PM UTC, Mat Vibrys <notifications@github.com> wrote:
>I share emacs config between work and home.
>
>While at home i use org-journal, at work I don't. As a consequence,
>'org-journal-dir' directory does not exist at work and when I try to
>put timestamp (with 'org-time-stamp-inactive'), it fails with "Journal
>directory /media/mkwap/health/seszyt/journal/ not found. Create one? "
>message. Following is the stack trace. This action succeeds when
>org-journal is not installed.
>
>```yes-or-no-p("Journal directory /media/mkwap/health/seszyt/journal/
>not found. Create one? ")
>  org-journal-dir-check-or-create()
>  org-journal-list-files()
>  org-journal-list-dates()
>  org-journal-mark-entries()
>  run-hooks(calendar-today-visible-hook)
>```
>
>Can org-journal act as inactive when 'org-journal-dir' does not exist?

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by vibrys** [comment]
Hi @cslux, I'm using org-journal as part of spacemacs, so org-journal is enabled as part of org layer, together with path to journal dir
```
     (org :variables
          org-enable-org-journal-support t
          org-journal-dir "/path/to/journal/at/home")
```

I'm sharing whole .emacs.d/, so also elpa packages.
Some time ago, I've added extra variable at emacs start (at-work), but I no longer do it.

regards,
Mat

**Comment by cslux** [comment]
Hey @vibrys, I don't know much about the layering architecture of spacemacs. I use `use-package` and there you can specify a condition when the package should be activated or not. 

At the initialization process I will decide what "Setup" should be activated based on the `(system-name)`. Currently I have three different, =work=, =full= and =tiny=.

``` emacs-lisp
(defconst my-setup-type (cond
                          ((string-match "lap-[0-9]+\\|tower" (system-name))
                           'full)
                          ((string-match "NL-00006" (system-name))
                           'work)
                          (t
                           'tiny)))

(use-package org-journal
   :if (eq my-setup-type 'full))
    ...)
```

Can you set some condition in the layer?

> Can org-journal act as inactive when 'org-journal-dir' does not exist?

Technically yes, but `org-journal` was designed that way.

**Comment by vibrys** [comment]
Thank You for the idea.
There is also one more factor, I didn't mention, but it's important.
What if 'journal' directory resides on some usb pen drive so that it could be mounted/umounted during when emacs session has already been started?

the initiial idea is just to let 'org-journal-dir' be also a function so that it could return nil if path does not exist, but as I see in the code, 'org-journal-file-format' also depends on 'org-journal-dir' at emacs startup and it does not seem as easy as just turning 'org-journal-dir' to be a function as well.

**Comment by cslux** [comment]
You could create a custom function which mounts and updates the `org-journal-dir` variable using e.g. `customize-set-variable`. 

I have pushed something to master. You shouldn't get asked now when you insert an org timestamp and the directory doesn't exists (https://github.com/bastibe/org-journal/commit/475d29764d2fbe3f13f633f40ef7e974b0b987c8).

**Comment by vibrys** [comment]
works fine, thank You Christian - it's nice to see You as a contributor in another great emacs package.

**Comment by cslux** [comment]
My pleasure! 

Thank you :-D
