### ISSUE TITLE
No Way of Disabling org-journal-carryover Using Customize

### ISSUE THREAD

**Issue by parhamdoustdar** [bastibe/org-journal#168]
There is no way of turning off `org-journal-carryover` functionality. The check that is done on the variable itself in the code is only checking if the variable is `nil`, but there is no way of setting a string to `nil` in the customize interface.

my suggestions would be:

- Either check for an empty string `""`, or;
- Define the customizable variable as a choice of items, and have two items like "Turn off carrying over TODO items`, and `Use a tags match`, or something like that.

For now, I'm just doing `custom-set-variables 'org-journal-carryover-items nil)` in my init file.

**Comment by cslux** [comment]
Thanks for the report @parhamdoustdar. Is fixed by 7cdd725.
