### ISSUE TITLE
org-journal-open-entry: Wrong type argument: listp, 2017

### ISSUE THREAD

**Issue by ngm** [bastibe/org-journal#171]
When calling `org-journal-new-entry`, I get the following error:

> org-journal-open-entry: Wrong type argument: listp, 2017

The file for the day is created (or opened if it already exists) OK, but the time for the new entry isn't created.

- os: Linux Mint 19.2
- emacs: 26.2
- org: 9.2.6
- org-journal: 1.15.1 (Package-Version: 20190909.1445)

**Comment by ngm** [comment]
Here's the trace from the debugger:

```
calendar-date-compare((2017) ((9 11 2019)))
  org-journal-open-entry("No previous journal entry before this one" t no-select)
  org-journal-open-previous-entry(no-select)
  org-journal-carryover()
  org-journal-new-entry(nil)
  funcall-interactively(org-journal-new-entry nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)
```

**Comment by cslux** [comment]
I fixed that already. Please download the new version from MELPA.

Close #171

**Comment by ngm** [comment]
I've updated the package to Package-Version: 20190910.1834 and it's working fine.

Thanks!

**Comment by cslux** [comment]
Thanks for confirmation.
