### ISSUE TITLE
Issue since September Release: missing function file-attribute-modification-time

### ISSUE THREAD

**Issue by gudesh** [bastibe/org-journal#173]
Hi,

since I updated the package in September, org-journal does not work properly anymore
(it opens a new file on a new day, with the first line as current date,
 but fails at printing a line with current time (ex: ** 09:52 ).

It outputs following message:
`org-journal-file-modification-time: Symbol’s function definition is void: file-attribute-modification-time
`

I use following Emacs version unter Ubuntu 18.04.3 LTS:
`GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21) of 2017-09-22, modified by Debian
`

I'm a great fan of org-journal and continue editing the files by hand, but it is a little bit less usable (-:

**Comment by cslux** [comment]
Thanks for the report. Is fixed with f52afef.

The function was added in a later Emacs version.
