### ISSUE TITLE
Open previous journal entry opens wrong file

### ISSUE THREAD

**Issue by vitorqb** [bastibe/org-journal#177]
Hello :).

I have been having strange issues with `org-journal-open-previous-entry`. Some days it fails to open the previous journal entry and, instead, it opens an older one.

I tried to debug it a little and I saw that `org-journal-open-entry` is calling `(org-journal-list-dates)`, and reversing it if `prev` is true. But at least for me `org-journal-list-dates` does *not* returns an ordered list of dates.

If I add a sorting on the very last lines of `org-journal-list-dates` and ensure it returns an ordered list of dates, then it all works.

Also, sometimes uninstalling and reinstalling org journal also solves it. I'm not sure if this could be explained because of the hashing algorithim since I see you are using `(keys (hash-table-keys org-journal-dates))`.

I'm using
;; Package-Version: 20191011.1315
;; Version: 1.15.1
emacs 26.3
Arch Linux 5.3.7

**Comment by cslux** [comment]
Hello @vitorqb!

What is the value of `org-journal-file-type`? Have you also tried to invalidate the cache when this happens (`org-journal-invalidate-cache`)?

**Comment by vitorqb** [comment]
Hi @cslux, thanks for getting back to me.

`org-journal-file-type` is daily.

Calling `org-journal-invalidate-cache` seems to "fix" the issue, that is, after calling it it seems that the `org-journal-open-previous-entry`  and `org-journal-open-next-entry` both open the correct files.

As a side note, I also realized that when this issue happens my TODO items are not carried over when creating a new entry (`org-journal-new-entry`). This is probably another side-effect of this issue.

**Comment by cslux** [comment]
I have a couple of questions. 
1. Have you always created new entries using `org-journal` functionality?
2. Have you switched between different `org-journal-file-type`'s? 

I think this issue should be resolved after calling `org-journal-invalidate-chache`. I will make the cache optional, because there are so many corner cases which could make the cache invalid, and you have probably hit one. I also could add a timer like `projectile` has, which when set to an integer greater than zero will trigger a recalculation of the cache after that many seconds.

**Comment by vitorqb** [comment]
> 
>     1. Have you always created new entries using `org-journal` functionality?
> 

I **always** use `org-journal-new-entry`.

>
>     2. Have you switched between different `org-journal-file-type`'s?
> 

No, never. Always daily.

> I think this issue should be resolved after calling `org-journal-invalidate-chache`. I will make the cache optional, because there are so many corner cases which could make the cache invalid, and you have probably hit one. I also could add a timer like `projectile` has, which when set to an integer greater than zero will trigger a recalculation of the cache after that many seconds.

Thanks for the option of making the cache optional, it would probably solve this issue for me :).

One little comment though, my usage of org-journal is pretty standard. The only configuration I actually have is to set the directory for the journal and nothing else. And for functionalities, I only use creating a new entry, navigating through entries and search. So I wonder what could be causing this behavior. If I'm able to find out anything else I'll let you know.

**Comment by cslux** [comment]
The cache is now disabled by default, and can be enabled by setting `org-journal-enable-cache` to `t`.
