### ISSUE TITLE
Creating a new entry freezes

### ISSUE THREAD

**Issue by er-cpp** [bastibe/org-journal#178]
* Platform:

```
$ uname -a
Linux laptop 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ emacs --version
GNU Emacs 25.3.2
```

* Setup:
** `~/.emacs`: https://pastebin.com/ZSjbMjts
** `~/.emacs.d`: https://postimg.cc/FYKxxg5P/7dc1b7aa

* Test file
** Location: `~/Documents/journal`
** Content: 
```
* Tuesday, 10/29/2019
** TODO 00:03                                                         :emacs:
   - State "TODO"       from              [2019-10-29 Tue 00:04]
```

* Runtime
** Action: `C-c C-j`
** Problem: Emacs freezes 
** process running: https://postimg.cc/dkhXSPbx/0873995a

**Comment by er-cpp** [comment]
C-g does unfreeze. Here's a screenshot just after:
https://postimg.cc/DWyZT44g. And here's the backtrace:

Debugger entered--Lisp error: (quit)
>   re-search-forward("^\\*+  *\\(\\<\\(ABANDONED\\|DONE\\|TODO\\)\\>\\)?
> *\\(.*?\\)\\([ ]:\\(?:[[:alnum:]_@#%]+:\\)+\\)?[ ]*$" nil t)
>   org-scan-tags(org-decrypt-entry (lambda (todo tags-list level) (progn
> (setq org-cached-props nil) (or (and (member "crypt" tags-list))))) nil)
>   org-decrypt-entries()
>   org-journal-decrypt()
>   org-journal-finalize-view()
>   org-journal-open-entry("No previous journal entry before this one" t
> no-select)
>   org-journal-open-previous-entry(no-select)
>   org-journal-carryover()
>   org-journal-new-entry(nil)
>   funcall-interactively(org-journal-new-entry nil)
>   call-interactively(org-journal-new-entry nil nil)
>   command-execute(org-journal-new-entry)
>

**Comment by cslux** [comment]
I'm afraid, but I can't reproduce it. I even compiled Emacs 25.3.1 from scratch and used your configuration. Everything works fine for me. According to the stacktrace it is not a `org-journal` thing anyway. Last thing you could try is to create a backup of your .emacs.d directory, and reinstall org-journal, and try it again. Or at least wipe .emacs.d/elpa.

**Comment by er-cpp** [comment]
How are you able to determine that, please?

"According to the stacktrace it is not a org-journal thing anyway"
>

**Comment by cslux** [comment]
I can't guarantee that it really is the case. It was an assumption. But since I can't reproduce it, I can't fix it.

What you can do to find out in which loop it stucks is to instrument for instance `org-scan-tags` using `edebug` (`M-x RET (info "(elisp)edebug") RET`) and step through it.

**Comment by bastibe** [comment]
@er-cpp It seems to me that you have customized your default TODO tags. Could you try recreating your problem without those customizations, and see if that fixes the issue?

**Comment by achernetsov** [comment]
I encountered this issue.

I found that issue started after I made entry where header ended with tag:

```
* Thursday, 21.05.2020
** 20:20 learning gtd, :gtd:
```

When I moved tag right after time issue was resolved.

```
* Thursday, 21.05.2020
** 20:20 :gtd: learning gtd
```

**Comment by cslux** [comment]
@achernetsov Can you give us a more detailed step by step instruction on how to reproduce this, please.

Thanks

**Comment by achernetsov** [comment]
# how to reproduce:
1. Have empty journal folder
2. Create journal entry with header ending with tag for day in past (today 20200522, so I create 20200521):

```
~/org/journal$ ls
20200521

~/org/journal$ cat 20200521
* Friday, 22.05.2020
** 13:31 test :test:
```

3. Try to create journal entry from emacs, using C-c C-j, it freezes.

# config

My ~/.ecams:

```
(require 'package)
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  (when no-ssl (warn "\
Your version of Emacs does not support SSL connections,
which is unsafe because it allows man-in-the-middle attacks.
There are two things you can do about this warning:
1. Install an Emacs version that does support SSL and be safe.
2. Remove this warning from your init file so you won't see it again."))
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  ;; Comment/uncomment this line to enable MELPA Stable if desired.  See `package-archive-priorities`
  ;; and `package-pinned-packages`. Most users will not need or want to do this.
  ;;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  )

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.
;; You may delete these explanatory comments.
(package-initialize)

(require 'org-journal)

(require 'org)
(define-key global-map "\C-cl" 'org-store-link)
(define-key global-map "\C-ca" 'org-agenda)
(setq org-log-done t)
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(calendar-date-style (quote european))
 '(ledger-default-date-format "%d.%m.%Y")
 '(ledger-reconcile-default-date-format "%Y/%m/%d")
 '(org-journal-dir "~/org/journal/")
 '(package-selected-packages (quote (git-auto-commit-mode ledger-mode org-journal))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(defun org-journal-save-entry-and-exit()
  "Simple convenience function.
  Saves the buffer of the current day's entry and kills the window
  Similar to org-capture like behavior"
  (interactive)
  (save-buffer)
  (kill-buffer-and-window))
(define-key org-journal-mode-map (kbd "C-x C-s") 'org-journal-save-entry-and-exit)

(setq org-agenda-files (list "~/org/index.org"
			     "~/org/notes.org"))

(setq org-default-notes-file (concat org-directory "/notes.org"))
;; Bind Org Capture to C-c r
(global-set-key "\C-cr" 'org-capture)

```

# notes

when I set tag right after time issue resolved:

```
* Friday, 22.05.2020
** 13:31 :test: test
```

**Comment by cslux** [comment]
It's working for me.

What is your org and Emacs version? I think this is because of an older version of org, can you try it with org-plus-contrib instead.

**Comment by achernetsov** [comment]
Thanks!

I updated emacs, cleaned all old configs, and performed fresh install of org-journal from melpa. All works now.

**Comment by cslux** [comment]
@achernetsov Glad to hear. Thanks for the feedback!
