### ISSUE TITLE
Search results date format

### ISSUE THREAD

**Issue by brookter** [bastibe/org-journal#179]
Hi, 

I'm just trying out the org-journal-search feature and it looks very useful, thanks...

Just one minor issue: I can't find a way to change the format of the date in the search results list. 

I have 2019-12-20 as my default format in org-journal-date-format, but the search list seems to hard code it to the American (Date) MM-DD-YYYY, which is confusing outside the US, of course, where DD-MM-YYYY is the standard.

I can't find a variable to configure this -- what am I missing, please?

Thanks!

**Comment by cslux** [comment]
Hi, it can very likely be hardcoded.
I will fix it Sunday evening.

cheers,
Chris 

On December 20, 2019 3:39:05 PM UTC, brookter <notifications@github.com> wrote:
>Hi, 
>
>I'm just trying out the org-journal-search feature and it looks very
>useful, thanks...
>
>Just one minor issue: I can't find a way to change the format of the
>date in the search results list. 
>
>I have 2019-12-20 as my default format in org-journal-date-format, but
>the search list seems to hard code it to the American (Date)
>MM-DD-YYYY, which is confusing outside the US, of course, where
>DD-MM-YYYY is the standard.
>
>I can't find a variable to configure this -- what am I missing, please?
>
>Thanks!

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by brookter** [comment]
That's great -- thanks very much for replying so quickly!

**Comment by cslux** [comment]
Hey @brookter!

Should be fixed, please check!

cheers,
Chris

**Comment by brookter** [comment]
That's wonderful -- does the trick nicely and such a quick response. I really appreciate it.

Thanks very much!

**Comment by cslux** [comment]
Perfect! My pleasure!
