### ISSUE TITLE
New Entry from orgmode buffer?

### ISSUE THREAD

**Issue by whiskeyputers** [bastibe/org-journal#181]
I'm running into the same issue as described in #58. Is this expected behavior or should I be able to use `C-c C-j` to add a new entry from an orgmode buffer?

If I press `C-c C-j` from a non orgmode buffer, `org-journal-new-entry` is called as expected and I'm taken to a new entry in my journal. Similarly, `C-u C-c C-j` in a non orgmode buffer takes me to my current journal file but does not create a new entry. If I press `C-c C-j` from an orgmode buffer, `org-goto` is called instead. If I press `C-c C-j` a second time, `org-journal-new-entry` is called as expected. 

For the time being, I'm binding `C-c j` to `org-journal-new-entry` as a workaround. But if I'm understanding correctly, I should be able to use `C-c j` from an orgmode buffer, right? Not a huge issue since I have a workaround, but figured I'd re-report it in case others are having the same issue or it's causing other problems. 

I am able to replicate this with the following stripped down init.el, running Emacs  26.3 (build 1, x86_64-w64-mingw32) and org 9.3.1 on Windows 10 1809:

```
(require 'package)

;; Only use HTTPS if GnuTLS is present
(let* ((no-ssl (and (memq system-type '(windows-nt ms-dos))
                    (not (gnutls-available-p))))
       (proto (if no-ssl "http" "https")))
  ;; Comment/uncomment these two lines to enable/disable MELPA and MELPA Stable as desired
  (add-to-list 'package-archives (cons "melpa" (concat proto "://melpa.org/packages/")) t)
  (add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)
  ; ;(add-to-list 'package-archives (cons "melpa-stable" (concat proto "://stable.melpa.org/packages/")) t)
  (when (< emacs-major-version 24)
    ;; For important compatibility libraries like cl-lib
    (add-to-list 'package-archives '("gnu" . (concat proto "://elpa.gnu.org/packages/")))))

;; Added by Package.el.  This must come before configurations of
;; installed packages.  Don't delete this line.  If you don't want it,
;; just comment it out by adding a semicolon to the start of the line.ist-
;; You may delete these explanatory comments.
(package-initialize)

;; Bootstrap use-package if it is not installed
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

(eval-when-compile
  (require 'use-package))

(require 'org)
(require 'org-journal)
```

**Comment by bastibe** [comment]
This is actually expected behavior. Org-mode defines its own C-c C-j, and overwrites org-journal's binding. This is actually documented [in the README](https://github.com/bastibe/org-journal#some-key-bindings-in-org-journal-overwrite-org-mode-key-bindings).

Minor modes are expected to only bind to C-c C-? keys, and are expected to not overwrite major mode bindings. However, C-c ? are reserved for user bindings, so your solution is exactly the right way to go about this.

**Comment by whiskeyputers** [comment]
Gotcha - thanks for the clarification and quick response. I'm an Emacs newbie, so I saw that in the README but misunderstood what it was saying. I thought it meant the C-c C-j binding in org-journal was supposed to overwrite org-mode's binding.

**Comment by bastibe** [comment]
If the note in the README is ambiguous, would you like to create a pull request that improves it? (You can create a pull request right here in Github by editing the README file)

**Comment by whiskeyputers** [comment]
Just submitted #183 to hopefully make that note clearer. :)
