### ISSUE TITLE
Make Weekly Journal Start on a Different Day

### ISSUE THREAD

**Issue by Spauldo** [bastibe/org-journal#185]
Currently, `org-journal` creates weekly journal files that start on Monday.

I am looking to use `org-journal` for my weekly reports.  When I'm on site, I have to turn in a document to the government that gives my activities from Sunday - Saturday.  I am planning on creating an export filter for this.  It'd be a lot easier if I could have weekly journal files that run Sunday - Saturday.

I've dug around in the code and found the function `org-journal-convert-time-to-file-type-time`, which seems to have chosen Monday because of the eccentricities of the ISO calendar.  I figure adding a number between -1 and 5 to the value returned by `calendar-iso-to-absolute` will accomplish what I need to do.  That number could possibly be linked to `org-agenda-start-on-weekday` as well, as I also plan to have my agenda start on Sunday.

I'm planning on doing this for my own needs regardless, but would you be interested in a pull request?  Do you see any hidden gotchas I might run into?

**Comment by bastibe** [comment]
I would absolutely be interested in a pull request! I would guess that there is a variable for setting the week-start somewhere in org-mode, and we should probably reuse that.

**Comment by Spauldo** [comment]
Pull request #186 added.  Let me know if you want changes to it.  It was a bit more complicated than I would have liked due to the way ISO dates work.  I've done a bit of testing and it seems to work, but I didn't have time for extensive testing.

**Comment by aragaer** [comment]
Looks like it doesn't work properly when weekday is sunday.
I have a file named journal-2020-10-18.org (that was sunday) with a Sunday entry and CREATED: 20201018
When I try to create a new entry on monday 19th, I'm getting the following error:
```
org-journal--search-forward-created: Search failed: "[ 	]*:CREATED:[ 	]+20201018[ 	]*$"
```
Deleting the Sunday entry from the file allows me to add monday entries.

**Comment by Spauldo** [comment]
I tested it and confirmed it doesn't seem to work on Sundays.

I stopped using this shortly after I did the pull request because my
reporting requirements changed.  I might be able to look into this at some
point, but at the moment I'm swamped with my job.

I'd suggest reverting the pull request for now.
