### ISSUE TITLE
2 questions about carry-over

### ISSUE THREAD

**Issue by winsphinx** [bastibe/org-journal#187]
1. carry-over is a great function, but after carried, there is always a `empty` file left. (which contains only some title).  Can this empty file be deleted automatically?

2. for example:
```
* example project
** DONE step 1
** TODO step 2
...
```
 one project with `done` and `todo` items would be split to two part. Can it be carried-over with whole project?

**Comment by cslux** [comment]
Hey @winsphinx!

That file should get deleted indeed. However, it shouldn't get deleted without confirmation. I'll try to implement something in the next few days.

- Chris

**Comment by cslux** [comment]
To answer your second question. This can already be achieved by customizing `org-journal-carryover-items`. In case of your example you would need to set `org-journal-carryover-items` to `"/TODO|DONE"`.

**Comment by winsphinx** [comment]
* Thanks for your commit, but I'm afraid there's something wrong on my emacs. Seems it doesn't delete the non-content-file. Should I forget something to configure?

* On the 2nd question, I have read README times and that setting seems be a global variable.  If it is set to `"/TODO|DONE"`, even all single `DONE` items are carried-over.

Maybe my poor English blocks my mind, and I give a more detail example:  

On the file `20200214`, I wrote:
```
* Project
** DONE step 1
** TODO step 2
```
and after carrying-over to file `20200215`, it is:
```
* Project
** TODO step 2
```
and in `20200214` it left:
```
* Project
** DONE step 1
```

For that is a /whole/ project, I hope /all/ the items under this title would be carried-over to the new file `20200215`. How can I set the variables?

Thank you again.

**Comment by cslux** [comment]
>     * On the 2nd question, I have read README times and that setting seems be a global variable.  If it is set to `"/TODO|DONE"`, even all single `DONE` items are carried-over.

You are right, it would also carryover DONE items. That means the project would be carried over until the end of the universe :)

Hmm, this isn't possible right now I guess than. I don't have any good ideas in my mind right now. Suggestions are welcome. 

>     * Thanks for your commit, but I'm afraid there's something wrong on my emacs. Seems it doesn't delete the non-content-file. Should I forget something to configure?

The empty journal file doesn't get deleted at the moment, if it is empty after the carryover operation. I'm currently thinking about a possible implementation.

**Comment by cslux** [comment]
I have just pushed a fix for question 1. You need to set the variable `org-journal-carryover-delete-empty-journal` to `ask` or `always`, default is `never`.

I will close this issue and open a new one for your second question.
