### ISSUE TITLE
Use inactive timestamp for created property

### ISSUE THREAD

**Issue by doolio** [bastibe/org-journal#188]
or perhaps the date part of `org-journal-date-format`. It's hardcoded to be %Y%m%d. My personal preference would be the ISO format or %F but perhaps it should be a customisable option. There also seems to be two spaces between the property keyword and its value. Is that necessary?

**Comment by cslux** [comment]
We could make it indeed customizable. Though, it only will work when it is unique between the journal entries. I wouden't reuse `org-journal-file-format` or `org-journal-date-format`. 

> There also seems to be two spaces between the property keyword and its value. Is that necessary?

That wasn't on purpose.

Are you interested in creating a PR for one of those?

**Comment by cslux** [comment]
> > There also seems to be two spaces between the property keyword and its value. Is that necessary?
> 
> That wasn't on purpose.

That extra space comes from org mode itself I guess, not sure why.

**Comment by cslux** [comment]
The two spaces come from `org-indent-lines`.

**Comment by cslux** [comment]
Maybe I should have just used the inactive org timestamp for the created property which uses the ISO 8601 format by default. Org-mode users are used to it. I will change that.

**Comment by doolio** [comment]
> Are you interested in creating a PR for one of those?

I can try but I'm not a programmer and my elisp-fu is rather limited.

> That extra space comes from org mode itself I guess, not sure why.
The two spaces come from org-indent-lines.

Interesting, I wonder why that is.

> Maybe I should have just used the inactive org timestamp for the created property which uses the ISO 8601 format by default. Org-mode users are used to it. I will change that.

Great. Much appreciated. I think using the ISO format as the default is best. Removes ambiguity for users in different locales. But I presume whatever is used must be understood by the calendar as I guess it is this property value that is used to open journal entries from there. Thanks for your time.

**Comment by cslux** [comment]
I work already on the date thing and I'm halfway way through. The only thing left is the conversation functionality to convert from the old format to the new one.

The two space thing is an org-mode thing. If you don't like it, you should write a bug report to the org mailing list. 

best 
Christian 


On February 15, 2020 3:48:30 PM UTC, doolio <notifications@github.com> wrote:
>> Are you interested in creating a PR for one of those?
>
>I can try but I'm not a programmer and my elisp-fu is rather limited.
>
>> That extra space comes from org mode itself I guess, not sure why.
>The two spaces come from org-indent-lines.
>
>Interesting, I wonder why that is.
>
>> Maybe I should have just used the inactive org timestamp for the
>created property which uses the ISO 8601 format by default. Org-mode
>users are used to it. I will change that.
>
>Great. Much appreciated. I think using the ISO format as the default is
>best. Removes ambiguity for users in different locales. But I presume
>whatever is used must be understood by the calendar as I guess it is
>this property value that is used to open journal entries from there.
>Thanks for your time.

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by cslux** [comment]
Advice needed! What is a good way to handle such a case, where outdated format is replaced with a new one.

- Should the user just be forced to call a function which converts the timestamps.
- Should I implement a routine which checks every time when the org-journal-mode is activated whether the timestamps need to be converted
- Should I just search for the new style timestamp at the current spots where it is used, and if not found try the old timestamp format, and if found, convert the timestamps
- ...

Thanks!

**Comment by bastibe** [comment]
I think your last proposal is most useful. Search for the new style timestamp, and if that fails for the old style. This has the added benefit of being a simpler algorithm that doesn't need to concern itself with re-writing existing files.

Backwards compatibility is a nuisance, but absolutely necessary. Nothing erodes trust in a project more than developers willfully breaking existing installations (I had to learn this the hard way).

**Comment by cslux** [comment]
Thanks bastibe! That was also the way I thought would be the most appropriate one.

**Comment by doolio** [comment]
Yes, I think your last proposal proposal is the best approach. Thank you both.

**Comment by cslux** [comment]
@doolio  Done! See `org-journal-created-property-timestamp-format`, valid value is e.g. [%Y-%m-%d %a] which is the org inactive timestamp.

**Comment by doolio** [comment]
Thanks so much Christian. Works like a charm.
