### ISSUE TITLE
[question] CSV export

### ISSUE THREAD

**Issue by holocronweaver** [bastibe/org-journal#191]
Is there an easy way to export org-journal entries to time series CSV, perhaps using `org-map-entries` on the results of a programmatic org-journal-search?

Use case: one nice feature of a ubiquitous blog framework like Wordpress is plugins that allow visualizing and exporting data about your entries, such as tags (sick day, project, etc) and daily values (e.g., weight, mood rating, daily high temperature, etc.).

I would like to accomplish something similar with org-journal by exporting my entries across a given time period into a time series CSV file which can be visualized using common tools.

For example, I would like to visualize sick days as thermometer icons on a calendar, plot my weight over time, and create a Github-style heatmap calendar of entries with a specific project tag.

**Comment by bastibe** [comment]
You can perhaps have a look at `org-journal-schedule-view`, which prints a summary of future entries. Perhaps that can be extended for your use case.
