### ISSUE TITLE
org-journal-file-header doesn't seem to work

### ISSUE THREAD

**Issue by jsravn** [bastibe/org-journal#192]
Trying out org-journal for the first time - I've set `org-journal-file-header` but it seems to always be ignored - it only inserts the default title. Here's what my config looks like:

```
  (setq org-journal-file-type 'yearly)
  (setq org-journal-file-format "%Y.org")
  (setq org-journal-enable-agenda-integration t)
  (setq org-journal-date-format "%e %b %Y (%A)")
  (setq org-journal-file-header "#+TITLE: Journal\n#+CATEGORY: journal\n#+STARTUP: folded")
  (setq org-journal-time-format "")
  (setq org-journal-find-file 'find-file)

```

Am I missing something?

**Comment by cslux** [comment]
Hey @jsravn!

If I use your config:
``` emacs-lisp
(use-package org-journal
    :load-path "~/Developing/third_party/org-journal"
    :custom:
    (org-journal-file-format "%Y.org")
    :config
    (setq org-journal-file-type 'yearly)
    (setq org-journal-enable-agenda-integration t)
    (setq org-journal-date-format "%e %b %Y (%A)")
    (setq org-journal-file-header "#+TITLE: Journal\n#+CATEGORY: journal\n#+STARTUP: folded")
    (setq org-journal-time-format "")
    (setq org-journal-find-file 'find-file))
```
I end up with the following journal file when I create the first entry (C-c C-j).
``` org
#+TITLE: Journal
#+CATEGORY: journal
#+STARTUP: folded
* 18 Feb 2020 (Tuesday)
:PROPERTIES:
:CREATED:  20200218
:END:
** 
```
Not quite sure what could be wrong. 

The only thing wrong with your setup is `org-journal-file-format`, either you set it before loading `org-journal`, use the customize interface or any of the customize function, otherwise `auto-mode-alist`  and `org-journal-file-pattern` will not get updated.

**Comment by jsravn** [comment]
Hmm, I wonder what's going on. I tried duplicating your config, but it still doesn't insert the header:

```
(use-package! org-journal
  :custom
  (org-journal-file-format "%Y.org")
  (org-journal-dir org-directory)
  :config
  (setq org-journal-file-type 'yearly)
  (setq org-journal-enable-agenda-integration t)
  (setq org-journal-date-format "%e %b %Y (%A)")
  (setq org-journal-file-header "#+TITLE: Journal\n#+CATEGORY: journal\n#+STARTUP: folded")
  (setq org-journal-time-format "")
  (setq org-journal-find-file 'find-file)
  )
```

It could be an issue w/ something else, I will try to dig. Thank you for your help!

**Comment by jsravn** [comment]
Stepping through it with edebug, something is inserting "#+TITLE: 2020" when the org file is created, which then causes org-journal to not insert its own header (it checks if the buffer is empty which fails).

**Comment by jsravn** [comment]
Okay, figured it out - using doom-emacs with file-templates enabled, it was adding the header. Removed and it works. Thanks!

**Comment by cslux** [comment]
Thank for letting us know where the issue was.

**Comment by g6ai** [comment]
> Okay, figured it out - using doom-emacs with file-templates enabled, it was adding the header. Removed and it works. Thanks!

Thanks for the solution! Spent hours trying to pinpoint this issue. Would be ideal if this is included in the documentation :)
