### ISSUE TITLE
org-journal-new-scheduled-entry seems to move all existing todos to the scheduled date

### ISSUE THREAD

**Issue by jsravn** [bastibe/org-journal#193]
When I try org-journal-new-scheduled-entry, it creates a new entry on the desired date, but also seems to carry over all the TODOs on the current date to the new date. Is there a way to prevent that?

**Comment by cslux** [comment]
Does changing org-journal-carryover-items fix your wish. Perhaps (setq
org-journal-carryover-itesm nil) is what you need.
