### ISSUE TITLE
org-journal-search produces no results

### ISSUE THREAD

**Issue by holocronweaver** [bastibe/org-journal#194]
Perhaps I have some weird misconfiguration, but I expected this to return results:

`journal/20200101`:
```
* Tuesday, 2020-02-18
:PROPERTIES:
:CREATED:  20200218
:END:
** 01:04 testing things
#+begin_src python
  print(test, just a test')
#+end_src
```

`org-journal-search` for `test` from 2020-02-16 to 2020-02-19 produces no results:

```
Search results for "test" between Sunday, 02/16/2020 and Wednesday, 02/19/2020: 

```

My config:
```
(use-package org-journal
  :config
  (progn
    (setq org-journal-file-type 'yearly
          org-journal-dir (concat org-directory "/journal")
          org-journal-date-format "%A, %F"
          )))
```

**Comment by cslux** [comment]
It's because of your configuration, please test again with this configuration:
``` emacs-lisp
(use-package org-journal
    :after org ;; requires org for `org-directory'
    :custom
    (org-journal-dir (concat org-directory "/journal"))
    :config
    (setq org-journal-file-type 'yearly
             org-journal-date-format "%A, %F"))
```

**Comment by holocronweaver** [comment]
Thanks! Use of `:customize` for `org-journal-dir` did the trick.

TIL [`customize-set-variable` triggers variable-setting methods and setq does not unless run prior to package load](https://emacs.stackexchange.com/a/106/315). Emacs + org user for 5+ years and have never noticed this distinction!

**Comment by mindlike** [comment]
FYI, this will likely trip up many Doom Emacs users, since the customize interface is not supported. Good to learn about the `:custom` tag in `use-package`!

**Comment by mindlike** [comment]
Actually `:custom` didn't work. Here's the only way I could get this to work in Doom:

```
(use-package! org-journal
  :after org
  :config
  (customize-set-variable 'org-journal-dir (concat org-roam-directory "journal"))
  ...)
```

**Comment by cslux** [comment]
> Actually `:custom` didn't work for me. Here's the only way I could get this to work in Doom:

Interesting 🤔
