### ISSUE TITLE
Agenda integration does not work if you alter the default file pattern

### ISSUE THREAD

**Issue by lhernanz** [bastibe/org-journal#195]
The function `(defun org-journal-file-name->calendar-date (file-name)` expects the default file name pattern with year, month and day. If you remove the day and/or the month (for example because you are using a monthly journal), this function will return `nil` and the agenda integration will not work as not journal files will be added to the agenda files. There are some other functions that call this one so I am not sure if this bug has some other side effects.
Probably the best thing would be to make this function aware of the journal type that you have configure to look for less or more date fields.

**Comment by cslux** [comment]
Should be fixed!

**Comment by lhernanz** [comment]
It is fixed! Thanks
