### ISSUE TITLE
First TODO on old buffer is not deleted on carryover

### ISSUE THREAD

**Issue by vitorqb** [bastibe/org-journal#196]
When I have a TODO entry on the previous day as the first node of a tree, like this:

```
* Saturday, 02/22/2020
** TODO FOO
** 16:47 Working on something
    blablabla
```

When I call `org-journal-new-entry`, which in turns calls `org-journal-carryover-items`, it adds the `**TODO FOO` before the new entry (as expected), *BUT* it does not deletes the `** TODO FOO` from the old file.

Therefore, if I call `org-journal-new-entry` again, the TODO is added once again, as the gif below shows.

![gif](https://i.ibb.co/mtbXGm5/peek.gif)

Git bisect lead me to this:

```
fb989163c60ea0c931e9d317c364af7a511d08fe is the first bad commit
commit fb989163c60ea0c931e9d317c364af7a511d08fe
Author: Christian Schwarzgruber <c.schwarzgruber.cs@gmail.com>
Date:   Sun Feb 16 09:20:14 2020 +0100
    Add option to delete empty entry/file after carryover operation (Default never)
 org-journal.el | 90 +++++++++++++++++++++++++++++++++++++++++++++++-----------
 1 file changed, 73 insertions(+), 17 deletions(-)
```

Looking at the code I wonder why the `org-journal-carryover` is taking the `cdr` of entries:

``` emacs-lisp
    ;; Delete carryover items
    (with-current-buffer prev-buffer
      (mapc (lambda (x)
              (kill-region (car x) (cadr x)))
            (reverse (cdr entries)))
```

Maybe this should be `(reverse entries)` instead of `(reverse (cdr entries))`?

```
GNU Emacs 27.0.60 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.13, cairo version 1.17.3) of 2020-02-02
```

**Comment by cslux** [comment]
That won't work for:

```
** Parent heading
*** TODO adsasdf
```

**Comment by cslux** [comment]
There is a little bit more broken. Carryover functionality needs to be redesign a little.

**Comment by cslux** [comment]
Thanks for the report @vitorqb. Should work now 0761967
