### ISSUE TITLE
org-journal-new-entry is broken

### ISSUE THREAD

**Issue by rileyrg** [bastibe/org-journal#199]
It's just opening the journal file from a few days ago and putting the cursor to the top. I recompiled after straight.el pulled in the latest version.

setup:-

```lang-elisp
(use-package org-journal
:bind
("C-c J" . org-journal-new-entry))
```

custom.el:-

```
 '(org-journal-dir "~/.emacs.d/orgfiles/journal-files")
 '(org-journal-file-format "%Y%m%d.org")


```
So today is 25-2-2020, its opening:-

![Screenshot from 2020-02-25 20-34-39](https://user-images.githubusercontent.com/362891/75280713-47772b00-580e-11ea-938c-0eb610616cfa.png)

**Comment by cslux** [comment]
Do you see any error messages in the message buffer?

**Comment by rileyrg** [comment]
Nothing I'm afraid.

**Comment by rileyrg** [comment]
I just put my existing files into org-journals/tmp and restarted emacs and it works with a new file.

**Comment by rileyrg** [comment]
This might help. Despite it showing the older file (cursor at the top) it is creating a new in today's file (but doesnt bring it to the front)

> * Tuesday, 02/25/2020
> ** 23:12 test
> ** 23:13                                                               :test:
> ** 23:16 
> ** 23:17 
> ** 23:18 
> ** 23:28 
>

**Comment by cslux** [comment]
Should be fixed.

**Comment by rileyrg** [comment]
That is.
