### ISSUE TITLE
outline-back-to-heading: Before First Heading with #+TITLE as first line

### ISSUE THREAD

**Issue by snuffop** [bastibe/org-journal#201]
Hi  I'm running into an issue with the 20200226.1125 version of org-journal

Using:
Emacs 26.3
Spacemacs 300 Devel
org-plus-contrib 20200224 <latets I believe

I use autoinsert  auto expand template to create the new file Daily

-- Template --

```
#+TITLE: Daily Notes for `(marty/journal-title)`
#+CATEGORY: Journal
#+STARTUP: content indent

* Status () {}                                                             :Day:
* `(marty/journal-graphicslink)`
* Tasks
* Entries

```
-- Functions --

```
(defun marty/autoinsert-yas-expand ()
  (let ((template ( buffer-string )))
    (delete-region (point-min) (point-max))
    (yas-expand-snippet template)
    (evil-insert-state)))


(defun marty/journal-title ()
  "The journal heading based on the file's name."
  (interactive)
  (let* ((year  (string-to-number (substring (buffer-name) 0 4)))
         (month (string-to-number (substring (buffer-name) 4 6)))
         (day   (string-to-number (substring (buffer-name) 6 8)))
         (datim (encode-time 0 0 0 day month year)))
    (format-time-string org-journal-date-format datim)))

(defun marty/journal-graphicslink ()
  " Set the Graphics Link to Today in the Pictures folder"
  (interactive)
  (let* ((year  (string-to-number (substring (buffer-name) 0 4)))
         (month (string-to-number (substring (buffer-name) 4 6)))
         (day   (string-to-number (substring (buffer-name) 6 8)))
         (datim (encode-time 0 0 0 day month year)))
    (format-time-string "[[/home/marty/Nextcloud/Pictures/%Y/Daily/%B/%d][Graphics Link]]" datim)))

```

-- Generated Output Today

```
#+TITLE: Daily Notes for Thursday, February 27 2020
#+CATEGORY: Journal
#+STARTUP: content indent

* Status () {}                                                             :Day:
* [[/home/marty/Nextcloud/Pictures/2020/Daily/February/27][Graphics Link]]
* Tasks
* Entries

```
-- Expected output  With cursor at the end of the 4 on the last entry
```

#+TITLE: Daily Notes for Thursday, February 27 2020
#+CATEGORY: Journal
#+STARTUP: content indent

* Status () {}                                                             :Day:
* [[/home/marty/Nextcloud/Pictures/2020/Daily/February/27][Graphics Link]]
* Tasks
* Entries
** 07:24

```
Instead the cursor is at position 0,0  before #+TITLE and a message in the log reads

outline-back-to-heading: Before first heading

I removed the #+ headers and stashed them in another file and the org-journal-new-entry function
seems to work correctly pushing the new

`** HH:MM`

into the file at the end below all other entries.

I remember this comming up in the past with the headers..

Might it be related to the org-journal-file-header  just added lately.. dunno

Marty

**Comment by cslux** [comment]
I might have been fixed this already. Can you test it with HEAD please? If still doesn't work, can you please also post the rest of your org-journal setup.

**Comment by cslux** [comment]
d4ff2b0 might have fixed it.

**Comment by snuffop** [comment]
Yes 20200226.1125   fixed issue.. yay!!

**Comment by cslux** [comment]
Thanks for checking!

**Comment by snuffop** [comment]
Strange Maybe not related but I now get
Debugger entered--Lisp error: (wrong-type-argument sequencep \.\.\.)
  copy-sequence(\.\.\.)
  undo-tree-node-copy([nil ([nil ([nil ([nil ... ... nil ... 0 nil]) ((apply yas--snippet-revive 1 274 #s(yas--snippet :expand-env nil :fields nil :exit nil :id 0 :control-overlay nil :active-field nil :previous-active-field nil :force-exit nil))) nil (24151 49966 790292 782000) 0 nil]) ((apply yas--take-care-of-redo #s(yas--snippet :expand-env nil :fields nil :exit nil :id 0 :control-overlay nil :active-field nil :previous-active-field nil :force-exit nil)) (1 . 274) (#("#+TITLE: Daily Notes for `(marty/journal-title)`\n#+CATEGORY: Journal\n#+STARTUP: content indent\n\n* Status () {}                                                             :Day:\n* `(marty/journal-graphicslink)`\n* Tasks\n* Entries\n" 0 49 (fontified nil line-prefix "" wrap-prefix "") 49 69 (fontified nil line-prefix "" wrap-prefix "") 69 95 (fontified nil line-prefix "" wrap-prefix "") 95 96 (fontified nil line-prefix "" wrap-prefix "") 96 177 (fontified nil line-prefix "" wrap-prefix #("* " 0 2 (face org-indent))) 177 210 (fontified nil line-prefix "" wrap-prefix #("* " 0 2 (face org-indent))) 210 218 (fontified nil line-prefix "" wrap-prefix #("* " 0 2 (face org-indent))) 218 228 (fontified nil line-prefix "" wrap-prefix #("* " 0 2 (face org-indent)))) . 1) (1 . 229) (t . -1)) nil (24151 49966 790295 648000) 0 nil]) nil nil (24151 49966 790297 575000) 0 nil] #s(undo-tree :root [nil nil nil nil (24152 3922 332426 582000) 0 nil] :current [nil nil nil nil (24152 3922 332426 582000) 0 nil] :size 0 :count 0 :object-pool #<hash-table eq 0/65 0x17b4abd>) [nil nil ((#(" " 0 1 (fontified nil line-prefix #("*" 0 1 (face org-indent)) wrap-prefix #("*** " 0 1 (face org-indent) 1 4 (face org-indent)) face org-level-2)) . -312) (undo-tree-id0 . -1) (undo-tree-id1 . -1) (undo-tree-id2 . 1) (313 . 314) 311) nil (24152 3911 998702 800000) 0 nil])
  undo-tree-copy(#s(undo-tree :root [nil ([nil ([nil ([nil ... ... nil ... 0 nil]) (...) nil (24151 49966 790292 782000) 0 nil]) ((apply yas--take-care-of-redo #s(yas--snippet :expand-env nil :fields nil :exit nil :id 0 :control-overlay nil :active-field nil :previous-active-field nil :force-exit nil)) (1 . 274) (#("#+TITLE: Daily Notes for `(marty/journal-title)`\n#+CATEGORY: Journal\n#+STARTUP: content indent\n\n* Status () {}                                                             :Day:\n* `(marty/journal-graphicslink)`\n* Tasks\n* Entries\n" 0 49 (fontified nil line-prefix "" wrap-prefix "") 49 69 (fontified nil line-prefix "" wrap-prefix "") 69 95 (fontified nil line-prefix "" wrap-prefix "") 95 96 (fontified nil line-prefix "" wrap-prefix "") 96 177 (fontified nil line-prefix "" wrap-prefix #("* " 0 2 (face org-indent))) 177 210 (fontified nil line-prefix "" wrap-prefix #("* " 0 2 (face org-indent))) 210 218 (fontified nil line-prefix "" wrap-prefix #("* " 0 2 (face org-indent))) 218 228 (fontified nil line-prefix "" wrap-prefix #("* " 0 2 (face org-indent)))) . 1) (1 . 229) (t . -1)) nil (24151 49966 790295 648000) 0 nil]) nil nil (24151 49966 790297 575000) 0 nil] :current [nil nil ((#(" " 0 1 (fontified nil line-prefix #("*" 0 1 (face org-indent)) wrap-prefix #("*** " 0 1 (face org-indent) 1 4 (face org-indent)) face org-level-2)) . -312) (undo-tree-id0 . -1) (undo-tree-id1 . -1) (undo-tree-id2 . 1) (313 . 314) 311) nil (24152 3911 998702 800000) 0 nil] :size 872 :count 7 :object-pool #<hash-table eq 4/65 0x39084c9>))
  undo-tree-save-history(nil overwrite)
  undo-tree-save-history-from-hook()
  run-hook-with-args-until-success(undo-tree-save-history-from-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
when trying to save the file..   Other org files save..

**Comment by snuffop** [comment]
Ahh Undo-tree history issues.

**Comment by snuffop** [comment]
AAAAH  emacs is such a bleeding ball of band-aids   sqirt   smak on a new band-aid..  squirt elsewhere.. aah

**Comment by cslux** [comment]
:-)
