### ISSUE TITLE
`org-journal-mode` is not automatically enabled

### ISSUE THREAD

**Issue by gmichokostas** [bastibe/org-journal#203]
I have the following in my `init.el`

```elisp
(use-package org-journal
  :ensure t
  :config
  (setq org-journal-file-type 'yearly
        org-journal-dir "~/notes/"
        org-journal-time-format ""
        org-journal-file-format "%Y"
        org-journal-date-format "%A, %d %B %Y"))
```

According to README when I do `C-c C-j` it will open or create a file in `org-journal-mode` but 
instead of it is in in `Fundamental` mode. I have to enable the `org-journal-mode` manually with `M-x`. 

Is there a way to enable the mode automatically? 

Thanks!

**Comment by cslux** [comment]
Hey!

You need to use the customize interface for org-journal-dir and org-journal-file-format.

(use-package
  ....
 :custom
 (org-journal-dir "~/notes/")
...
)


On March 3, 2020 1:15:56 PM UTC, Yiorgos Michokostas <notifications@github.com> wrote:
>I have the following in my `init.el`
>
>```elisp
>(use-package org-journal
>  :ensure t
>  :config
>  (setq org-journal-file-type 'yearly
>        org-journal-dir "~/notes/"
>        org-journal-time-format ""
>        org-journal-file-format "%Y"
>        org-journal-date-format "%A, %d %B %Y"))
>```
>
>According to README when I do `C-c C-j` it will open or create a file
>in `org-journal-mode` but 
>instead of it is in in `Fundamental` mode. I have to enable the
>`org-journal-mode` manually with `M-x`. 
>
>Is there a way to enable the mode automatically? 
>
>Thanks!

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by gmichokostas** [comment]
Awesome! That did the job. Thank you very much!
