### ISSUE TITLE
symbol's function definition is void: org-journal-find-location

### ISSUE THREAD

**Issue by komali2** [bastibe/org-journal#207]
In the readme, the following capture template is recommended:

          ("j" "Journal entry" entry (function org-journal-find-location)
           "* %(format-time-string org-journal-time-format)%^{Title}\n%i%?")

However, there doesn't appear to be a function called `org-journal-find-location`. 

What's the preferred way of using org-journal with org-capture?

**Comment by cslux** [comment]
But in the README right above the snippet you posted is also the `org-journal-find-location` function definition. In other words, you are supposed to write one.
