### ISSUE TITLE
changing file format results in "There was no year zero" 

### ISSUE THREAD

**Issue by wanderer** [bastibe/org-journal#208]
When setting `org-journal-file-format` journal entries are no longer created correct and there is a resulting message "There was no year zero" 

Here is my org config
```
(use-package org-journal
  :custom
  (org-journal-file-format "%y%m%d.org")
  (org-journal-dir
   (concat org-directory "/journal")))
```

**Comment by cslux** [comment]
You need to use %Y no %y.
