### ISSUE TITLE
Carry over TODO-config

### ISSUE THREAD

**Issue by thomasheartman** [bastibe/org-journal#210]
Hi,

First off: loving the package so far, and the readme is great! I have a question regarding configuration that I couldn't find an answer to, though.

Would it be possible to copy over any `#+TODO:` config (and potentially other config) from the previous entry? I'm using the following one for work right now:
```
#+todo: TODO(t) REVIEW(r) | DONE(d)
```
and it would be nice if every new entry would have the same configuration.

I know you can set these in your config, but I think I'd rather have them specified at a file (or maybe directory?) level. That said, there are probably other ways to configure this that I'm just not thinking of at the moment.

Appreciate any input! Cheers!

**Comment by bastibe** [comment]
Thank you!

Instead of carrying them over every time, you could add those to `org-journal-file-header`, and have them auto-inserted into every new file. Would that work for you?

**Comment by thomasheartman** [comment]
Ooh, yeah! That looks like it's just what I need actually. Thanks! 

My initial thought was that if you have multiple systems, then you could have multiple file headings and use a different set of TODO states for each one, where they'd automatically inherit the heading from the previous entry. 

This may be quite complex though, and because the `org-journal-file-header` variable can also be a function (as per the documentation), then that's probably a better way to solve that issue. Not that I need it right now, but it's a classic case of overthinking.

Anyway, this should be all I need right now, so I'll close the issue. I couldn't find anything about it in the readme, though. Is there more documentation elsewhere that I should have read, or is it just a case of reading the source code?

**Comment by thomasheartman** [comment]
One downside to using a string only, is that it's not automatically evaluated when you create a new journal file. Maybe this can be achieved with the function version?

**Comment by thomasheartman** [comment]
And one more thing: to configure which items are carried over, the only way is to set the `org-journal-carryover-items`, right? 

Seems like this can easily get out of sync, but I guess I'll have to be watchful of that, or get comfortable enough with lisp that I can make the configuration dynamic.

At the moment, I've got this:
```elisp
(setq org-journal-carryover-items "TODO=\"TODO\"|TODO=\"REVIEW\"")
(setq org-journal-file-header "#+TODO: TODO(t) REVIEW(r) | DONE(d)")
```

**Comment by bastibe** [comment]
> One downside to using a string only, is that it's not automatically evaluated when you create a new journal file. Maybe this can be achieved with the function version?

Yes, that's true. That's an interesting bug. We'd have to re-enable org-mode after carryover in order for it to pick up these changes. If that's important to you, please open a new issue!

**Comment by thomasheartman** [comment]
Maybe you could set them by setting `org-todo-keywords` somehow? I'd prefer them to be buffer-local, though. 

Anyway, I'll just use the simple approach for the time being, and then see whether it's an actual issue or not. If it turns out to be too annoying, I'll open another issue, but I'll leave it for a bit.

Thanks for all your help!
