### ISSUE TITLE
[Feature Request] Conveniuence function: Re-encrypt journal to a new encryption key

### ISSUE THREAD

**Issue by wakatara** [bastibe/org-journal#213]
It would be very nice if there was a convenience function to allow re-encrypting to a new key in org-journal. 

At the moment, the only way I could puzzle this out was to move the gpg file, decrypt it manually with gpg, and then re-encrypt it with the new key and move the resulting file back into org-journal (and then changing the org-crypt setup to point to the new key.). 

Not sure if that's within the purview of org-journal (or my lack of emacs-fu simply made me not realize there was an esasier way to do this) but would be helpful.

(btw, loving the fully encrypted journal feature - works just the way I want to and well with Deft.).

**Comment by bastibe** [comment]
Great idea!

Anyone interested in implementing this? I don't use encryption, so it's not for me.

**Comment by cslux** [comment]
That should be straight forward. I'll add something. I also encrypt my private journal files, and occasionally  re-encrypt all my encrypted files with a new gpg key. This is definitely something which I can need beside in org-journal.

**Comment by cslux** [comment]
@wakatara! 

I have added a function `org-journal-re-encrypt-journals` (https://github.com/bastibe/org-journal/commit/40e9f694969f467a9ce2a4b68719f154490eca0d). I have tested it with my own journal files. Is this what you wanted?

**Comment by wakatara** [comment]
Hey there @cslux !

Yes, this looks pretty much like it'd do the trick! Thanks! (I'm just about to test it now.).

Definitely better than the manual thing I did. While it's unrelated to the implementation, it might be a wise idea to mention in the docs that if you are git checking changes to your files or using a service that has time back ups, you will need to eliminate old versions of the file as they will still be decryptable by the old key until such a time as it expires (if for example, the reason for re-encrypting is a compromise.).

Looks good though! Merci!
