### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by cslux** [bastibe/org-journal#214]

**Comment by cslux** [comment]
@bastibe I don't have sufficient permissions to enable CI in travis.

https://travis-ci.org/github/bastibe/org-journal

```
 This is not an active repository

You don't have sufficient rights to enable this repo on Travis.
Please contact the admin to enable it or to receive admin rights yourself. 
``

https://docs.travis-ci.com/user/tutorial/

I have pushed a ".travis.yml" to the branch "ci".

**Comment by bastibe** [comment]
OK, I enabled the repo on Travis. I think as soon as you push to master, it should pick up the `.travis.ml` and start working. I didn't find any option to select a specific branch, so I guess we'll have to do this on master. Right?

**Comment by bastibe** [comment]
Wait... I can at least trigger builds manually on the "ci" branch. I've done that.

**Comment by cslux** [comment]
Cool!

**Comment by bastibe** [comment]
It seems that the current test bench is taking too long and are terminated before they complete. Can you trigger manual builds on your end now?

**Comment by cslux** [comment]
Seems to stuck. Great, it's always a pleasure with travis ;-)

**Comment by cslux** [comment]
Ok, up and running. Test for emacs-25.3 doesn't work because it hangs. I tested it locally to, and indeed the test run hangs. This is due to the org version coming with emacs-25.3, which is to old for org-journal, we need at least version 9.1.

**Comment by bastibe** [comment]
Great work! Thank you for setting that up!
