### ISSUE TITLE
Create issue template

### ISSUE THREAD

**Issue by cslux** [bastibe/org-journal#216]
Unfortunately I'm unable to create an issue template (https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository).
@bastibe  I very likely don't have the permissions to do so.

I think it would help us as developer to fix the bugs faster if the post there org-journal setup when they open an issue due to a bug. Otherwise we have always to ask for it, which is bored. Can you setup an issue template @bastibe please?

Thanks!

Chris

**Comment by bastibe** [comment]
Good idea!

I've created an issue template and a bug report template. It seems that the templates are simply files in the `.github` directory in the master branch, so we can refine them there. (Also, Github didn't offer to create them as a pull request instead of directly pushing to master 😠)

**Comment by cslux** [comment]
Cool, thanks!

**Comment by cslux** [comment]
I'll close this than. We can refine them as needed.
