### ISSUE TITLE
Org-capture

### ISSUE THREAD

**Issue by Gahamelas** [bastibe/org-journal#220]
Hi, and congrats on your package.
I haven't used it yet, but I was wondering what the difference would be between org-journal and org-capture set to capture journal entries in a tree-fashion way. Thank you.

**Comment by bastibe** [comment]
Org-journal is a directory full of daily org-mode files. It includes functions for encryption, searching, scheduling things in the future, and carrying TODO items with you until they are done.

Org-capture is a way of saving transient information into one or many org-mode files.

I don't know what more to say. You seem to imply that they are "competitors" in some way. But they are not. They are simply different things. Read the documentation on both, or try them yourself, to learn more.

**Comment by Gahamelas** [comment]
Thanks, I ask because many users have implemented—as I understand—what org-journal does by using org-capture: you can get an subtree of dates and time with entries as long as in org-journal. That is why I ask.

**Comment by Gahamelas** [comment]
BTW, I would disagree with "Org-capture is a way of saving transient information into one or many org-mode files.". How so "transient"? I very well keep muy diary using org-capture, and I can tell it's permanent.

**Comment by bastibe** [comment]
Do you have an issue with org-journal?

This is not a forum for discussions about your preferred Emacs tools, sorry.

**Comment by Gahamelas** [comment]
No, I'm not stating my preferred emacs tool, I am just asking what is superior in org-journal that org-capture cannot set to do as a way to avoid adding packages onto my init.e, thus slowing it down.
