### ISSUE TITLE
[question] Title with date on top of header

### ISSUE THREAD

**Issue by rsuhada** [bastibe/org-journal#221]
I'm using daily journals, with date set as the org `#+TITLE: ` along with a few startup options.

I set these using:
```
(org-journal-date-prefix "#+TITLE: ")
(org-journal-file-header "#+STARTUP: showstars\n#+STARTUP: showall\n#+STARTUP: indent")
```

This puts the TITLE as the **last** line of the header.
Is there an option to have TITLE on top, followed by all the startup settings?

The reason is both cosmetic and interoperability with other packages (particularly deft).

**Comment by bastibe** [comment]
As far as I know, there is no such option, sorry.

**Comment by cslux** [comment]
@rsuhada Why not use org-journal-file-header for everything? You could set org-journal-file-header to a function, and do what ever you want.
