### ISSUE TITLE
Problem accessing org-journal-file-type and calendar not showing

### ISSUE THREAD

**Issue by kaydeetwo** [bastibe/org-journal#222]
Hi - I've been using org-journal for a number of months now. Have the default set as daily files.

First question: would like to move to weekly or even monthly files - but `org-journal-file-type` doesn't come up under `M-x customize` or isn't an option in auto-fill when adding to `.emacs` customize variable. Do I need to access `org-journal-file-type` some other way?

Also, if I hit `M-x calendar` I don't see any days showing that journal entries exist - they all look the same. Is there anything I need to set/configure to have the calendar show entries?

Clearly I'm not a LISP/emacs pro - so hoping I could get some pointers here on the above.

Thank you!

JW

**Comment by cslux** [comment]
> would like to move to weekly or even monthly files - but `org-journal-file-type` doesn't come up under `M-x customize`

Works for me. How did you install org-journal? What version of org-journal do you use? 

![Screenshot from 2020-04-24 17-35-57](https://user-images.githubusercontent.com/1712313/80230613-75cc8780-8652-11ea-8224-ba6cc4650d27.png)

> Also, if I hit `M-x calendar` I don't see any days showing that journal entries exist - they all look the same. Is there anything I need to set/configure to have the calendar show entries?

Please poste your org-journal setup? Also, do you use spacemacs or something similar?

**Comment by kaydeetwo** [comment]
OK - so this was a rookie 'mistake' - I re-installed/upgraded via package install in emacs to version 2.0.0. And in `M-x customize` I now see the file type - have changed to monthly and think working great. I also now see current day's entry in `M-x calendar` - although I don't see prior ones, but that's not too much of an issue for me.

Automated customize added

```
 '(org-journal-dir "~/org/journal/")
 '(org-journal-file-type (quote monthly))
```

in `.emacs` - and I also have:

```
;; include org-journal mode
(require 'org-journal)
(setq org-journal-dir "~/org/journal/")
```

I use helm. But thanks - I think I'm good for now - and appreciate the quick response!
