### ISSUE TITLE
Setting org-journal-time-format and org-journal-time-prefix to nil causes an error

### ISSUE THREAD

**Issue by parhamdoustdar** [bastibe/org-journal#225]
**Describe the bug**
I'm trying to make my journal a continuous stream of the day, without the timestamps and headings. however, this currently causes an error.

I tried setting `org-journal-hide-entries-p` to `nil`, but I can see in the code that `outline-hide-other` gets called without checking that variable.

**To Reproduce**
1. Set the two variables I mentioned to nil
2. Call org-journal-new-entry

**Expected behavior**
I expect the cursor to be put at the start of a new empty line with no errors.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Mac OS 10.15.3
 - Emacs Version [e.g. 25]: 28.0.50

**Your Emacs Configuration**
```
(custom-set-variables
 '(org-journal-carryover-items "")
 '(org-journal-dir "~/Dropbox/journal/")
 '(org-journal-hide-entries-p nil)
 '(org-journal-time-format "")
 '(org-journal-time-prefix "")
)
```

**Comment by parhamdoustdar** [comment]
I gathered some more info about this if it helps.

So, the reason this doesn't happen with the default prefix is that when `outline-hide-other` is called and the cursor is on something other than the very first heading, everything works well. However, it breaks when it's on the first heading or anywhere in the text of the first heading. When I remove the time prefix, the whole file is under theheading which is the day. 

Here is what I mean. Copy and paste this into an org buffer:

```
* heading 1

text 1

* heading 2

text 2

* heading 3

Text 3
```

Now, try going to headings 2 or 3, and use `eval-expression` to run `(outline-hide-other)`. You'll see that it works well.

Now, put the cursor on `heading 1` or `text 1` and evaluate `(outline-hide-other)` and boom! It'll fail.

This seems to be a bug with `outline-mode` for all intents and purposes, but you know better.

Thanks for looking into this! <3

**Comment by bastibe** [comment]
Thank you for your bug report and analysis.

I see you are using the very latest Emacs development version. Do you know whether the bug is happening on the stable version as well?

**Comment by parhamdoustdar** [comment]
I'm sorry for wasting your time. After looking more deeply into this, and while almost sending a bug to the GNU Emacs bug list, I realized that it is an issue with Emacspeak. I submitted a patch, so no one else should hopefully face it! :-)

**Comment by cslux** [comment]
Glad to hear that you found out the cause. 

On April 28, 2020 4:21:10 PM UTC, Parham Doustdar <notifications@github.com> wrote:
>I'm sorry for wasting your time. After looking more deeply into this,
>and while almost sending a bug to the GNU Emacs bug list, I realized
>that it is an issue with Emacspeak. I submitted a patch, so no one else
>should hopefully face it! :-)

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com
