### ISSUE TITLE
2.1.0 breaks org-deadline function

### ISSUE THREAD

**Issue by yuchen-lea** [bastibe/org-journal#226]
**Describe the bug**

When calling function `org-deadline` or `org-schedule`  at a heading (no matter inside journal file or out), warning as below:

> org-journal-entry-date->calendar-date: Args out of range: "[2020-04-27 Mon]", 726, 733

**To Reproduce**

It's really weird... When I run into edebug mode, I found when execute 
`org--deadline-or-schedule` , it will jump to `org-journal-entry-date->calendar-date` at this line:

> (org-add-planning-info type time 'closed)

org-journal 2.0.0 works, however 2.1.0 breaks down.

I also tried force to recompile code of both org and org-journal, still doesn't work.

**Desktop (please complete the following information):**
 - OS: Mac 10.15.3
 - Emacs Version 26.3
 - Org mode version 9.3.6
 - org-journal 2.1.0

**Your Emacs Configuration**

This happens even when I removed all org-journal and org-mode configurations.

**Comment by cslux** [comment]
Are you using org-journal from Melba stable?

**Comment by cslux** [comment]
> This happens even when I removed all org-journal and org-mode configurations.

That's strange. Can you post a backtrace please. Call `toggle-debug-on-error` and reproduce the error, and post the backtrace. Did you switch between different org-journal-file-type? Have you tried with org-journal from Melpa (not Melpa stable)?

**Comment by yuchen-lea** [comment]
Thanks for telling way this efficient way to report bug! Here is the backtrace when calling org-schedule:

> Debugger entered--Lisp error: (args-out-of-range "[2020-04-27 Mon]" 717 724)
>   match-string(2 "[2020-04-27 Mon]")
>   org-journal-entry-date->calendar-date()
>   org-journal-file->calendar-dates("/Users/yuchen/Documents/Notes/journals/daily/2020-04-27.org")
>   mapcar(org-journal-file->calendar-dates ("/Users/yuchen/Documents/Notes/journals/daily/2020-04-27.org" "/Users/yuchen/Documents/Notes/journals/daily/2020-04-28.org"))
>   org-journal-list-dates()
>   org-journal-mark-entries()
>   run-hooks(calendar-today-visible-hook)
>   #f(compiled-function () #<bytecode 0x45ae2f5d>)()
>   calendar-generate-window(4 2020)
>   calendar-basic-setup(nil)
>   calendar()
>   org-read-date(nil to-time nil "SCHEDULED" nil nil)
>   org-add-planning-info(scheduled nil closed)
>   #f(compiled-function () #<bytecode 0x4b1f1d45>)()
>   org--deadline-or-schedule(nil scheduled nil)
>   org-schedule(nil)
>   funcall-interactively(org-schedule nil)
>   call-interactively(org-schedule nil nil)
>   command-execute(org-schedule)

Let me make it more clear:
- this happens under melpha version `20200424.1917`
- melpha-stable is 2.0.0, works fine, no error. I now switch back to 2.0.0, and manually add the auto expand file header function, which is the main reason I upgrade :)
- I did switch between different org-journal-file-type, now I'm using daily type. Running the function `org-journal-invalidate-cache` doesn't solve this.

**Comment by cslux** [comment]
org-journal is integrated into the calendar, hence, org-journal functions are called when you add deadline/scheduled timestamps. 

What is the current value of org-journal-file-type. C-h v org-journal-file-type.



> org-journal-file->calendar-dates("/Users/yuchen/Documents/Notes/journals/daily/2020-04-27.org")
> mapcar(org-journal-file->calendar-dates ("/Users/yuchen/Documents/Notes/journals/daily

Indicates that org-journal-file-type is not set to 'daily but rather to one of weekly, monthly, yearly.

Please check your configuration files. custom.el etc. Somewhere the org-journal-file-type variable gets altered.

**Comment by yuchen-lea** [comment]
Oops, I set it to "daily" rather than daily, and I find it's "Daily" indeed... I just think too simple. Thanks for your time.
