### ISSUE TITLE
Carry over carries DONE task

### ISSUE THREAD

**Issue by arussel** [bastibe/org-journal#228]

**Comment by arussel** [comment]
I'm not sure this is a but. I've modified the test:
https://github.com/arussel/org-journal/commit/43409ad78afad94ff86ee89c87f18ce699d69cdb
The test fails with the error:
```
** TODO a
** b1
*** TODO b1
*** DONE b1
*** b1 note
*** b2
**** TODO b2
**** b3
***** TODO b3
***** DONE b3
** TODO b
** DONE done below b
** 14:00 Some journal entry 2
** 17:39
" "* Test header
** TODO a
** b1
*** TODO b1
*** b2
**** TODO b2
**** b3
***** TODO b3
** TODO b
** 17:39
```

Where i have done task in the result. Am I misunderstanding the expected behavior, or can we consider it a bug ? (If this is a bug I'll be happy to dig into it)

to test 'live', this file will do:
* Wednesday, 01/02/19
* Work
** DONE a
** a
** TODO a
** b1
*** TODO b1
*** DONE b1
*** b1 note
*** b2
**** TODO b2
**** b3
***** TODO b3
***** DONE b3
** DONE this is a done task
* Home
** DONE this is a done task
** TODO b
** DONE this is done
** 14:00 Some journal entry 2

**Comment by cslux** [comment]
The headings Work and Home are at the same level as the journal entry if you move them one below the journal heading it works.

**Comment by arussel** [comment]
@cslux ok, my misunderstanding, I thought that because we have a single file per journal entry, all TODO were expected to be carry over and all DONE task were expected to 'stay' where they were.
