### ISSUE TITLE
Args out of Range Error Calling When Calling org-journal-new-entry If There Exists a Non org-journal recognizable CREATED Timestamp Somewhere Previous in the Hierachy

### ISSUE THREAD

**Issue by ptrckbkr** [bastibe/org-journal#231]
**Describe the bug**
I found this issue after installing org-expiry. Basically org-expiry started creating TODO entries with a CREATED property that looks like this :CREATED:  [2020-05-14 Thu 08:17]. After that org-journal started to fail.

Note: It seems to work if the entry is already created

**To Reproduce**
Create a Journal File That has a CREATED entry like such.

```
* Monday, 05/11/2020
:PROPERTIES:
:CREATED:  20200511
:END:
** TODO TASK 1
:PROPERTIES:
:CREATED:  [2020-05-14 Thu 08:23]
:END:

```
Then execute org-journal-new-entry

**Expected behavior**
A new entry should be added for today.

**Desktop (please complete the following information):**
 - OS: Linux/Manjaro
 -  GNU Emacs 26.3 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.10)
 of 2019-08-29 

**Your Emacs Configuration**
Doom Emacs + 
```
(after! org-journal
  (setq org-journal-file-format "%Y-%m.org"
        org-journal-file-type 'monthly))


```
**Backtrace**
Debugger entered--Lisp error: (args-out-of-range "[2020-05-14 Thu 08:17]" 5031 5038)
  match-string(2 "[2020-05-14 Thu 08:17]")
  org-journal-entry-date->calendar-date()
  org-journal-file->calendar-dates("/REDACTED/2020-05.org")
  org-journal-new-entry(nil)
  funcall-interactively(org-journal-new-entry nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)

**Comment by cslux** [comment]
Currently only journal entries should have a CREATED property.

**Comment by cslux** [comment]
@ptrckbkr Commit 2c43b10 should have fixed it.

**Comment by ptrckbkr** [comment]
That fixes it. Thanks.
