### ISSUE TITLE
Journal entries are not being picked up

### ISSUE THREAD

**Issue by djeis97** [bastibe/org-journal#233]
When I use `org-journal-open-previous-entry` it always errors saying "No previous journal entry...", similarly with `org-journal-open-next-entry`. This issue also seems to affect carrying over TODOs from the previous entry.

**To Reproduce**
1. Open a journal file with multiple entries.
2. Place the cursor on the second (or a later) entry
3. Run `org-journal-open-previous-entry`

**Expected behavior**
The previous entry is selected.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Emacs Version: 26.3

**Your Emacs Configuration**
```
(setq-default
              org-journal-dir "~/org/roam/"
              org-journal-date-prefix "* "
              org-journal-file-format "Journal %Y-%m.org"
              org-journal-date-format "%A, %d %B %Y"
              org-journal-enable-agenda-integration t
              org-journal-enable-cache t
              org-journal-file-type 'monthly)
```

I'm fairly confident that the problem comes back to the recent change to `org-journal-file->calendar-dates` (which now always returns `nil` for me): the guard using a call to `(outline-level)` always fails. Looking at the source of the function `outline-level` it does not seem to do what you intended there. I'm guessing you either intended to call `org-outline-level` or call the function stored in the variable `outline-level` (which, in org buffers, seems to be set to `'org-outline-level`).

**Comment by cslux** [comment]
@djeis97 Yep, your are right, `org-outline-level` is the correct function to call.

Thank you for the report!

**Comment by djeis97** [comment]
Thanks for resolving it so quickly!
