### ISSUE TITLE
Create entries in past ok, "There was no year zero" for today

### ISSUE THREAD

**Issue by ajft** [bastibe/org-journal#234]
**Describe the bug**
From the calendar, "i j" correctly creates entries in the past, says "There was no year zero" for today, and creates entries for future dates with unwanted extra text.

**To Reproduce**
("X" below indicates the cursor position)

On past days, "i j" creates a buffer holding:
```
* Tuesday, 2020-05-19
** X
```
On today's date, "i j" displays error message "There was no year zero" and creates a buffer holding:
```
* Thursday, 2020-05-21X
```
On future dates, "i j" creates a buffer holding:
```
* Friday, 2020-05-29
** TODO 
<2020-05-29>X
```
**Expected behavior**
Buffer created for past, present and future as for past.

**Desktop (please complete the following information):**
 - OS: linux, ubuntu 20.04
 - Emacs Version 26.3
 - org-journal  2.1.0

**Your Emacs Configuration**
org-journal installed from package
```
(use-package org-journal
  :load-path "~/.emacs.d/lisp/org-journal")

(setq org-journal-date-format "%A, %F")
(setq org-journal-file-format "%Y-%m-%d.org")```

**Comment by cslux** [comment]
Hmm, works for me.

Can you try if it is also happing with the following setup.

``` emacs-lisp
(use-package org-journal
  :load-path "~/.emacs.d/lisp/org-journal"
  :custom 
  (org-journal-file-format "%Y-%m-%d.org")
  :config
  (setq org-journal-date-format "%A, %F"))
```
Thanks!

**Comment by ajft** [comment]
I've discovered that I was using an ancient version of `use-package` and replaced that with the current version, together with the change above I now have correct response for today and past days, but still have incorrect entries generated for any date in the future. eg, "i j" on Sunday produces : ```* Sunday, 2020-05-24
** TODO 
<2020-05-24>```

**Comment by cslux** [comment]
> but still have incorrect entries generated for any date in the future. eg, "i j" on Sunday produces:

Why is this incorrect?

**Comment by ajft** [comment]
Sorry, too many personal things going on at the moment to check my mail. Hadn't realised you'd closed this.

When I create an journal for a day in the past by "i j" on the calendar, the buffer contains:
```
* Dayname, date
** 
```
With dayname, date for that day from the calendar.

Creating one for today, the buffer contains
```
* Dayname, date
** HH:MM
```
Where HH:MM are the time _now_

But when I create one for a day in the future it is:
```
* Dayname, date
** TODO
<date>
```

I don't understand where the "TODO" and active timestamp come from, and why the appear for journal entries for dates in the future.

**Comment by cslux** [comment]
Works as designed. C-h f org-journal-new-date-entry RET.
