### ISSUE TITLE
Work with org-download

### ISSUE THREAD

**Issue by dangirsh** [bastibe/org-journal#236]
Thanks for this package! I can confirm I use it daily ;)

**Describe the bug**
org-download checks if the major-mode is `org-mode` for its features to work. In journal files, the major-mode is org-journal. 

**To Reproduce**
Try running `org-download-screenshot` in a journal file.

**Expected behavior**
Screenshot should be inserted to the buffer as a file link.

I had expected `org-journal` to be a minor mode, so this failure was surprising to me. `org-download` has checks like `(eq major-mode 'org-mode)` in a few places, which I think is fair. I tested that `org-download` works fine in `org-journal` buffers by manually updating those guards.

It seems like the potential fixes are:

1. Make org-journal a `minor-mode`
2. Find a more general way for `org-download` to check it's in an `org-mode`-ish buffer.
3. Just add `org-journal-mode` to the relevant guards in `org-download`.

I don't know if 1 is possible, and think 3 is obviously ugly. My vote is 1 if possible.

FYI @abo-abo

**Comment by bastibe** [comment]
This is a very good argument for making org-journal a minor mode.

I know we discussed this at some point in the past, but maybe it's time to revisit it. (Or did we reach a consensus last time we discussed making org-journal a minor mode? I forget...)

**Comment by cslux** [comment]
I think this should be fixed upstream, by checking if the current mode has been derived from `org-mode`.

```
(derived-mode-p 'org-mode)
```

**Comment by cslux** [comment]
I will create a PR for https://github.com/abo-abo/org-download.

**Comment by dangirsh** [comment]
Ah, `derived-mode-p` is exactly what I was looking for. 

Thanks for the fast fix! Confirmed it works for me.
