### ISSUE TITLE
Ability to stop the insertion of time entry when using org-journal-new-entry

### ISSUE THREAD

**Issue by psibi** [bastibe/org-journal#237]
**Is your feature request related to a problem? Please describe.**

As the title describes, I want to have the ability to stop the insertion of time entry when using org-journal-new-entry. This should be configurable via a variable with the default value with the current behaviour.

I can volunteer to implement the same if there is no objection.

**Comment by cslux** [comment]
You can achieve that, by calling `org-journal-new-entry` with a prefix argument C-u C-c C-j.

**Comment by psibi** [comment]
Oh, thanks! I didn't know that.
