### ISSUE TITLE
Open an org date picker for `org-journal-new-date-entry` if not on a date

### ISSUE THREAD

**Issue by brabalan** [bastibe/org-journal#241]
**Is your feature request related to a problem? Please describe.**
I often want to enter some information in org-journal for a previous or future date, but I'm not in a calendar context. In that case I cannot use `org-journal-new-date-entry`, as I get the error `org-journal-calendar-date->time: Symbol’s value as variable is void: displayed-month`.

**Describe the solution you'd like**
In that case, an org date picker would pop up (using `org-read-date`).

**Comment by cslux** [comment]
Good idea.

**Comment by cslux** [comment]
@brabalan Resolved via  1de9153.

**Comment by brabalan** [comment]
Thanks!

**Comment by cslux** [comment]
You are welcome!
