### ISSUE TITLE
org-journal-dir can't be a symlink or subdir of some symlink

### ISSUE THREAD

**Issue by wpchou** [bastibe/org-journal#242]
**Describe the bug**
Setting org-journal-dir as a symlink or subdir of some symlink leads to failing to insert time prefix and format and beeping out "user-error: There was no year zero" when using org-journal-new-entry. Setting org-journal-carryover-items as nil can bypass this problem.

Stops here when i was edebuging-defun org-journl-new-entry: https://github.com/bastibe/org-journal/blob/master/org-journal.el#L645

**To Reproduce**
Setting org-journal-dir as a symlink or subdir of some symlink.

**Expected behavior**
org-journal-new-entry insert time string correctly.

**Desktop (please complete the following information):**
 - OS: archlinux
 - Emacs Version: 27.0.91

**Comment by cslux** [comment]
Should be fixed via  e1003e3. Thanks for the report!

**Comment by lsiksous** [comment]
This bug come and go

**Comment by cslux** [comment]
@lsiksous so you are still seeing it

**Comment by lsiksous** [comment]
No I don't. I was just saying that the bug comes back from time to time. There is other related Issues. But I definitely stopped using a symlink for org-journal-dir. Thx for asking.

**Comment by cslux** [comment]
Ok! I'll use them now, maybe I came across some bugs, and use symlinks in the teste as well.



On May 28, 2020 3:18:48 PM UTC, Laurent Siksous <notifications@github.com> wrote:
>No I don't. I was just saying that the bug comes back from time to
>time. There is other related Issues. But I definitely stopped using a
>symlink for org-journal-dir. Thx for asking.

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com
