### ISSUE TITLE
magic-mode-alist error

### ISSUE THREAD

**Issue by tpeacock19** [bastibe/org-journal#243]
**Describe the bug**

The recent commit https://github.com/bastibe/org-journal/commit/a3ff9ce81884bffbe121eba72c7b05589ac91448 to use magic-mode-alist does not account for non-file buffers (dired, info, help, temp buffers for org-htmlize, etc.). This results in an error whenever (set-auto-mode) as the org-journal-is-journal does not return nil.

```emacs-lisp

(defun org-journal-is-journal ()
  "Determine if file is a journal file."
  (string-match (org-journal-dir-and-file-format->pattern) (buffer-file-name)))

-->

  (string-match (org-journal-dir-and-file-format->pattern) nil)) 
```

**To Reproduce**
1. Run emacs with latest org-journal build
2. Open Info buffer
3. Eval: (set-auto-mode)

**Expected behavior**
The magic-mode-alist function should be able to handle non-file buffers and return nil

Can we change the function to something like:

```emacs-lisp
(defun org-journal-is-journal ()
  "Determine if file is a journal file."
(if (buffer-file-name)
      (string-match (org-journal-dir-and-file-format->pattern) (buffer-file-name))
    nil))
```

**System Info**
 - OS: ArchLinux
 - Emacs Version 27.091

**Comment by cslux** [comment]
Please create a PR. Thanks 

On May 27, 2020 10:25:40 AM UTC, tpeacock19 <notifications@github.com> wrote:
>**Describe the bug**
>
>The recent commit
>https://github.com/bastibe/org-journal/commit/a3ff9ce81884bffbe121eba72c7b05589ac91448
>to use magic-mode-alist does not account for non-file buffers (dired,
>info, help, temp buffers for org-htmlize, etc.). This results in an
>error whenever (set-auto-mode) as the org-journal-is-journal does not
>return nil.
>
>```emacs-lisp
>
>(defun org-journal-is-journal ()
>  "Determine if file is a journal file."
>(string-match (org-journal-dir-and-file-format->pattern)
>(buffer-file-name)))
>
>-->
>
>  (string-match (org-journal-dir-and-file-format->pattern) nil)) 
>```
>
>**To Reproduce**
>1. Run emacs with latest org-journal build
>2. Open Info buffer
>3. Eval: (set-auto-mode)
>
>**Expected behavior**
>The magic-mode-alist function should be able to handle non-file buffers
>and return nil
>
>Can we change the function to something like:
>
>```emacs-lisp
>(defun org-journal-is-journal ()
>  "Determine if file is a journal file."
>(if (buffer-file-name)
>(string-match (org-journal-dir-and-file-format->pattern)
>(buffer-file-name))
>    nil))
>```
>
>**System Info**
> - OS: ArchLinux
> - Emacs Version 27.091

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com

**Comment by cslux** [comment]
@tpeacock19 Actually `(and (buffer-file-name) (string-match (org-journal-dir-and-file-format->pattern) (buffer-file-name)))` would be enough.

**Comment by tpeacock19** [comment]
didnt get to create the PR as I need to sleep but thanks for the quick update.

**Comment by cslux** [comment]
I thought so, but this might have influenced some users, and considered it as urgent to fix it as soon as possible.

Thanks again!
