### ISSUE TITLE
Question: How do I keep file header for weekly file types?

### ISSUE THREAD

**Issue by yosevu** [bastibe/org-journal#244]
Hello! Is it possible to keep my file header for weekly file types?

For example, I have customized these variables:

```elisp
(org-journal-file-format "%Y-%m-%d.org")
(org-journal-file-header "#+TITLE: %Y-%m-%d\n#+ROAM_TAGS: journal\n\n[[file:journal.org][Journal]]\n\nWeek %V, %Y\n\n")
(org-journal-date-format "%Y-%m-%d (%A)")
(org-journal-time-prefix "")
(org-journal-time-format "")
```

which gives me the following template:

```Org
#+TITLE: 2020-05-30
#+ROAM_TAGS: journal

[[file:journal.org][Journal]]

Week 22, 2020

* 2020-05-30 (Saturday) 
```
When I set `(org-journal-file-type 'weekly)`

I loose my header:

```Org
* 2020-05-30 (Saturday) 
:PROPERTIES:
:CREATED:  20200530
:END:
```

**Comment by jmburgos** [comment]
It seems to be a recent bug.  I do weekly journals and my header used to work with no problem.  But today, after updating, it is not showing up anymore.  For reference, here is my header string:

`(setq org-journal-file-header "#+TITLE: Weekly agenda\n#+STARTUP: showall\n* Clock table\n#+BEGIN: clocktable :maxlevel 4 :emphasize nil :scope file :link t\n#+END:\n* Plan for this week\n")`

**Comment by cslux** [comment]
@yosevu Works for me using your settings.

``` emacs-lisp
(use-package org-journal
    :after org
    :config
    (setq org-journal-file-format "%Y-%m-%d.org"
          org-journal-file-header "#+TITLE: %Y-%m-%d\n#+ROAM_TAGS: journal\n\n[[file:journal.org][Journal]]\n\nWeek %V, %Y\n\n"
          org-journal-date-format "%Y-%m-%d (%A)"
          org-journal-time-prefix ""
          org-journal-time-format "")
    :bind
    ("C-c j" . org-journal-new-entry))
```
Will result in that journal file.

```
#+TITLE: 2020-06-02
#+ROAM_TAGS: journal

[[file:journal.org][Journal]]

Week 23, 2020

* 2020-06-02 (Dienstag)
  :PROPERTIES:
  :CREATED:  20200602
  :END:
```

**Comment by cslux** [comment]
@jmburgos @yosevu Side note,  switching between different org-journal-file-type won't work. You would need to convert to the old journals to the new journal format, or use a different org-journal-dir.

I created once a quick and dirty conversation function, see https://github.com/bastibe/org-journal/issues/160#issuecomment-493758815.
