### ISSUE TITLE
[Bug] Cursor jumps up to top of mid of first screen on saving of long encrypted (yearly) journal file 

### ISSUE THREAD

**Issue by wakatara** [bastibe/org-journal#245]
**Describe the bug**
On an encrypted journal that exceeds the length of the window (by a very healthy margin) a save which re-encrypts the journal but then returns the cursor back to an initial position midway down the first screen (an entire two screens up even folded) rather than at the point of I hit the save command. Effectively the cursor jumps back to the first "screen" of entries and midway down that screen.

**To Reproduce**
Take a very long annual file full of lots of entries (mine, an annual file is 4500+ lines, 38 "date" day headings, and subheadings on the "time" entry

eg.
``` org-mode
* 2020-05-31 Sun (day entry)
:PROPERTIES:
:CREATED:  20200531
:END:
** 23:23 Weekly checkin - last week in May (time entry)                            :gps:
** 22:08 Crushing lockdown
``` 
PS> Just a bug bear but why is the CREATED tag not in ISO format ie. 2020-05-31?)

**Expected behavior**
On a save of the buffer the file should encrypt as it does but the cursor position should not jump and remain at the insertion point prior to save. 

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OSX
 - Emacs Version 27.0.91
 - gpg (GnuPG) 2.2.20, libgcrypt 1.8.5

**Your Emacs Configuration**
``` emacs-lisp
; Org Journal config
(use-package org-journal
  :ensure t
  :defer t
  :custom
  (org-journal-dir "~/Dropbox/Apps/deft")
  (org-journal-file-type 'yearly)
  (org-extend-today-until 1)
  (org-journal-file-format "journal-%Y.org")
  (org-journal-date-format "%Y-%m-%d %a")
  (org-journal-encrypt-journal t)
  (org-journal-enable-cache t)
  (org-journal-carryover-items nil))
```

**Comment by cslux** [comment]
> **Describe the bug**
> On an encrypted journal that exceeds the length of the window (by a very healthy margin) a save which re-encrypts the journal but then returns the cursor back to an initial position midway down the first screen (an entire two screens up even folded) rather than at the point of I hit the save command. Effectively the cursor jumps back to the first "screen" of entries and midway down that screen.

Thanks for the report. I will investigate it as soon as I find time. 


> PS> Just a bug bear but why is the CREATED tag not in ISO format ie. 2020-05-31?)

My bad :-( We can't force the ISO date now, as it would brake the existing journal files.
But, I have added a conversation function to convert all CREATED property timestamp to the new format bound to `org-journal-created-property-timestamp-format`. 

To change the CREATED timestamp:
1. Set `org-journal-created-property-timestamp-format` to your preferred date
2. Call `org-journal-convert-created-property-timestamps`, which asks for the old format.

**Comment by wakatara** [comment]
> To change the CREATED timestamp:
>     1. Set `org-journal-created-property-timestamp-format` to your preferred date
>     2. Call `org-journal-convert-created-property-timestamps`, which asks for the old format.

Oh wow, that's amazing. Thank you. I was just about to write something to do the conversion. Very handy. Thanks.

Any idea what is causing the returned cursor position to re-position all the way up the buffer (only thing I could think of off the top of my head was some mismatch between the length of the decrypted buffer you're typing in versus the encrypted one the function crypts on save.  ¯\\_(ツ)_/¯

Thanks very much for the convenience functions. Off to apply those now. Merci!

**Comment by cslux** [comment]
@wakatara I can't reproduce it. I think the problem is somewhere else. Have you tried it with a minimal fresh setup too?

``` emacs-lisp
;;; Setup package.el
(require 'package)

(when (version< emacs-version "25.1")
  (setq package-enable-at-startup nil)) ;; Will be set to nil by `package-initialize' as of 25.1
(setq package-archives '(("marmalade" . "https://marmalade-repo.org/packages/")
                         ("melpa"     . "https://melpa.org/packages/")
			 ("gnu"       . "http://elpa.gnu.org/packages/")
                         ("orgmode"   . "http://orgmode.org/elpa/")))
(package-initialize)

;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(require 'use-package-diminish)
(require 'use-package-bind-key)

(require 'use-package)
(use-package org-journal
    :ensure t
    :defer t
    :custom
    (org-journal-dir "~/Dropbox/Apps/deft")
    (org-journal-file-type 'yearly)
    (org-extend-today-until 1)
    (org-journal-file-format "journal-%Y.org")
    (org-journal-date-format "%Y-%m-%d %a")
    (org-journal-encrypt-journal t)
    (org-journal-enable-cache t)
    (org-journal-carryover-items nil))
```

And than start emacs like this `emacs -q -l dotemacs.mini`

**Comment by wakatara** [comment]
I am beginning to think you may be correct. Either there was a quirk in my config, or the latest version of the package you released just before the 2020-0613 melpa version fixed this, since I am no longer seeing this as of Wednesday when I wrote one of my weekly updates.  :-/ 

Sorry, if this somehow was a wild good chase, but I do think something you changed in the release before 0613 seems to have corrected this problem when I updated the package.
