### ISSUE TITLE
#+SETUPFILE directive not processed on new journal file

### ISSUE THREAD

**Issue by mrvdb** [bastibe/org-journal#246]
On the top of my daily journal files I use a `#+SETUPFILE` directive which loads the setup I want for journal files.

That line  is put there courtesy of `org-journal-file-header`

```(setq org-journal-file-header "#+SETUPFILE: ~/.emacs.d/org-config.org")```

At the journal file creation it seems the setupfile directive is not processed and I have to `C-c C-c` on it to apply its settings.

- arch linux
- emacs 28.0.50

**Comment by cslux** [comment]
Makes sense. I'll fix it the next few days.

**Comment by cslux** [comment]
Should be fixed with commit 1d8e8e6!

Thanks for the report!
