### ISSUE TITLE
org-journal-schedule-view returns 'wrong type argument'

### ISSUE THREAD

**Issue by dalanicolai** [bastibe/org-journal#247]
**Describe the bug**
After scheduling an item using `org-journal-new-scheduled-entry`, `org-journal-schedule-view` returns 'wrong type argument'

**To Reproduce**
- Install org-journal (version 20200604.1806)
- add a scheduled entry with ``org-journal-new-scheduled-entry` and save buffer
- Now `M-x org-journal-schedule-view` shows no items, and returns 'Wrong type argument: characterp,'

**Expected behavior**
Expect to see the item in the *Org-journal schedule* buffer

**Screenshots**
![image](https://user-images.githubusercontent.com/18429791/83875923-496b5700-a738-11ea-8cac-4943a37645c0.png)
![image](https://user-images.githubusercontent.com/18429791/83876238-d6161500-a738-11ea-8c70-ee1ea647e8a7.png)

**Desktop (please complete the following information):**
 - OS: Linux Fedora 32 x86_64
 - Emacs Version 26.3 build 2

**Your Emacs Configuration**
org-journal (version 20200604.1806)

**Comment by cslux** [comment]
Hey @dalanicolai, org-journal-schedule-view needs a little polishing.

**Comment by cslux** [comment]
Should be fixed with commit 817545a.

**Comment by dalanicolai** [comment]
Wow! That was really fast. So I can confirm it works here now. Which is great of course. Thanks a lot!
