### ISSUE TITLE
user-error: There was no year zero Upon new journal entry

### ISSUE THREAD

**Issue by atzbacher** [bastibe/org-journal#251]
**Describe the bug**
When creating a new org-journal entry the correctly named file (if it is a new day) is created but the time stamp is missing and the user-error: There was no year zero is issued.
Same config works as expected under Manjaro 20.0.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Emacs Version 26.1

**Your Emacs Configuration**
(use-package org-journal 
  :load-path "~/.emacs.d/lisp/org-journal"
  :custom 
  (org-journal-file-format "%Y-%m-%d.org")
  :config
  (setq org-journal-date-format "%A, %F")
)

**Comment by cslux** [comment]
Seems to be windows thing. Please have a look at this issue https://github.com/bastibe/org-journal/issues/235.

**Comment by cslux** [comment]
@atzbacher As a first step I would enable debug on error. M-x toggle-debug-on-error RET.

Please post the backtrace. Probably org-journal-dir-and-file-format->pattern returns a file name which isn't correct because of the drive letters on windows.

**Comment by atzbacher** [comment]
Toggle on error doesn't trigger. I just get the user-error in the message buffer. 

If i change `org-journal-file-type` to weekly, monthly or yearly it works.

**Comment by cslux** [comment]
> If i change `org-journal-file-type` to weekly, monthly or yearly it works.

Very strange, but so should it be. Anyway, I found the cause. The commit 9f66bf4 should have fixed to bug.

**Comment by atzbacher** [comment]
Yes it did. Thanks!
