### ISSUE TITLE
Carrying items over does not update the time stamp

### ISSUE THREAD

**Issue by brabalan** [bastibe/org-journal#252]
**Describe the bug**
When a TODO item is carried over, its timestamp is not updated. As a consequence it does not show in the agenda daily view.

**To Reproduce**
- have a TODO item in a previous day with a timestamp of that day
- call `org-journal-new-entry`

**Expected behavior**
- the item is moved (this is the case) **and its timestamp is updated** (this is not)

**Your Emacs Configuration**
The part relevant to org-journal.
```emacs-lisp
(use-package! org-journal
  :config
  (map!
   (:leader
    (:n "d o j" 'org-journal-new-entry)))
  :custom
  (org-journal-dir deft-directory)
  (org-journal-date-prefix "#+TITLE: ")
  (org-journal-time-prefix "* ")
  (org-journal-file-format "%Y-%m-%d.org")
  (org-journal-date-format "%Y-%m-%d (%A)"))
(setq org-journal-enable-agenda-integration t)
```

**Comment by cslux** [comment]
Hey @brabalan! Indeed, I'll fix tomorrow.

**Comment by cslux** [comment]
Should be fixed!

**Comment by brabalan** [comment]
It works, thanks!

**Comment by shka** [comment]
That commit updates all timestamps also SCHEDULE and DEADLINE...
Is this expected?

**Comment by cslux** [comment]
@shka That depends, it might be desired. I'll add a switch.

**Comment by cslux** [comment]
@shka Scheduled/Deadline time stamps need to be updated manually from now on.

**Comment by shka** [comment]
Thanks for the prompt update! But unfortunately, the latest org-journal-20200615.724 w/ org-20200608 changes the SCHEDULED/DEADLINE timestamps, still.

**Comment by cslux** [comment]
@shka Right! The latest commit should have finally resolved it.

**Comment by shka** [comment]
Great, org-journal-20200616.1006 solved this! Thank you so much!
