### ISSUE TITLE
There was no year zero Error when using `%F` instead of `%Y-%m-%d` in `org-jounal-file-format`

### ISSUE THREAD

**Issue by yogsototh** [bastibe/org-journal#253]
**Describe the bug**
When using 

```elisp
(setq org-journal-file-format "%Y/%F.org")
```

Creating a new entry fails with the message: user error There was no year zero.

**Workaround**: simply replace `%F` by `%Y-%m-%d` in `org-journal-file-format`.

**To Reproduce**

```elisp
(setq org-journal-file-format "%Y/%F.org")
```
Then `(org-journal-new-entry)`

**Expected behavior**
Mainly `%F` should be treated as `%Y-%m-%d` (there might be other time format suffering from the same problem).

**Desktop (please complete the following information):**
 - OS: macOS
 - Emacs Version: GNU Emacs 26.3 (build 1, x86_64-apple-darwin17.7.0, Carbon Version 158 AppKit 1561.6) of 2020-05-07

**Your Emacs Configuration**

After my workaround:

```elisp
(setq org-journal-dir "~/.org/journal/"
        org-journal-file-type 'daily
        ;; format time detail here:
        ;; https://www.gnu.org/software/emacs/manual/html_node/elisp/Time-Parsing.html
        org-journal-file-format "%Y/%Y-%m-%d.org" ;; DO NOT USE %F for %Y-%m-%d due to a trick in org-journal
        org-journal-date-format "%F %A"
        org-journal-enable-agenda-integration t)
```

**Comment by cslux** [comment]
Makes sense. We did not support the placeholder %F until now. 

%F is now supported!
