### ISSUE TITLE
[Feature Request] Performance of org-journal-list-files

### ISSUE THREAD

**Issue by philScholl** [bastibe/org-journal#258]
On Windows 10, `org-journal-list-files` is very slow for having a journal file per day. For example, opening the calendar buffer with journal integration takes 10-20 seconds on my computer (~80% of overall time is taken by `org-journal-list-files` according to profiler). This is mostly due to multiple `file-truename` calls, which seems to be pretty slow (at least on Windows).

If I am not completely mistaken, calling `file-truename` is not necessary in the predicate, as this has already been mapped to the file list.
Would it be possible to have the file list cached?

**Comment by cslux** [comment]
@philScholl I have removed the two `file-truename` calls in `org-journal-list-files`. Please let me know if this has improved the speed. We have support for caching the dates, but not for files, see `org-journal-enable-cache`.

**Comment by philScholl** [comment]
@cslux yes, this helped a lot - the execution time approximately halved for opening the calendar.
