### ISSUE TITLE
New entry keybinding maped to org-goto by default

### ISSUE THREAD

**Issue by weverett** [bastibe/org-journal#26]
Not sure what exactly to do about this, but org-mode uses C-c C-j to invoke org-goto, so maybe org-journal should disable that key binding?

**Comment by bastibe** [comment]
Yes, I know about this. Originally, I used to use C-c j, which worked fine. C-c [letter] is reserved for user-configurated key bindings, so we can't use that from org-journal. Do you have a good idea for a better key binding than C-c C-j? I recommend rebinding org-journal-new-entry to C-c j yourself.

**Comment by weverett** [comment]
I don't know what would make a good default. I actually meant that you could disable the org-goto keybinding, but I suppose that's probably be annoying to someone who was expecting the normal function there. Maybe no default binding and just a note at the top of the README.org suggesting the C-c j/b/f? That's sort of what the org manual does in the part where they talk about agendas.

**Comment by weverett** [comment]
Then too, you could also just make it C-c j anyway. By default org uses C-c ' to call org-edit-special, so it's not that reserved.

**Comment by bastibe** [comment]
See #22 for further discussion of C-c j. I'm afraid that we'll have to stick with C-c C-[...] key bindings. But I agree that this should be noted in the README.

**Comment by bastibe** [comment]
this is now noted in the README (as of 755fc5d)
