### ISSUE TITLE
org-jounrnal make org loaded when elisp file open

### ISSUE THREAD

**Issue by tshu-w** [bastibe/org-journal#263]
**Describe the bug**
After I install org-journal, if I open any elisp file, it will make org loaded.

**To Reproduce**
```emacs-lisp
;;; emacs -nw -Q -l ~/.emacs.d/test.el

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org"   . "https://orgmode.org/elpa/")
                         ("gnu"   . "https://elpa.gnu.org/packages/")))

;; initialize packages
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil)          ; To prevent initializing twice
  (package-initialize))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(package-install 'org-journal)
(eval-after-load
    'org
  '(progn (print "Org loaded") t))

(find-file "~/.emacs.d/test.el")
```

**Expected behavior**
"Org loaded" was not printed after `emacs -nw -Q -l ~/.emacs.d/test.el`.

**Screenshots**
<img width="1920" alt="Screen Shot 2020-06-22 at 12 30 45 PM" src="https://user-images.githubusercontent.com/13161779/85248701-38368000-b484-11ea-883a-9288d323daf9.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Emacs Version: GNU Emacs 27.0.91 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101)) of 2020-06-20

This also happens on Emacs 26.3 or 28.

**Comment by cslux** [comment]
Thanks for the report, good catch. Should be fixed with https://github.com/bastibe/org-journal/commit/24b587978241328fcad40f932602a0a4c1e7d403
