### ISSUE TITLE
Void variable from "org-journal-previous-entry"

### ISSUE THREAD

**Issue by christabella** [bastibe/org-journal#266]
**Describe the bug**
I've enabled the org-journal Doom module with `(org +journal)` but trying to do `org-journal-previous-entry` (or next-entry) results in `Lisp error: (void-variable displayed-month)`. Navigating via `M-x calendar` and `i j` over some date opens that journal entry, so the calendar package is alright...

I asked on the Doom discord for help and Henrik suggested that it appears to be a bug in org-journal using an uninitialized variable.

**To Reproduce**
- Latest Doom with `(org +journal)` in `init.el`
- Create 2 journal entries, and try to navigate to one from the other with org-journal-<previous/next>-entry

**Expected behavior**
Navigate to the previous/next entry.

**Screenshots**
- 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OSX
 - Emacs Version [e.g. 25]: 26.3

**Your Emacs Configuration**
The part relevant to org-journal.
```
(setq org-directory "~/org/"
      org-journal-dir "~/Dropbox/org/journal"
      org-roam-directory "~/Dropbox/org/zettels"
      org-roam-db-location "~/org-roam.db"
      org-journal-file-format "%Y-%m-%d.org"
      org-journal-date-prefix "* "  ;; No title, print heading straightaway.
      ;; Heading example: `Friday, 12 June 2020'
      org-journal-date-format "%A, %d %B %Y"
      org-ellipsis " ▼ "
      ;; Automatically add journal TODO's to agenda.
      org-journal-enable-agenda-integration t
      )

(use-package! org-journal
  :config
  (map!
   "s-j" #'org-journal-new-entry
   "C-M-S-s-j" #'org-journal-new-entry
   "C-M-S-s-k" #'org-journal-new-entry  ;; Today, or Kyō (今日)
   "s-J" #'org-journal-open-current-journal-file))
```

**Comment by cslux** [comment]
Hey @christabella, `org-journal-previous-entry` and `org-journal-next-entry` are supposed to be used only inside the calendar. 
There are two other functions, `org-journal-open-next-entry` and `org-journal-open-previous-entry` which can be used inside an org-journal buffer the navigate. 

But thinking about this, I think having two types of next/previous function is bad. There should be only one next/previous function, which work inside the calendar, and an org-journal buffer.

**Comment by christabella** [comment]
OMG! That is such an incredibly facepalm moment for me, I was using that in a previous config but forgot about its existence. Ahhhh.... Thank you!!

**Comment by christabella** [comment]
That makes a lot of sense. Well I don't know about having two types of functions, not familiar with designing Emacs packages... Whatever makes the most sense to you :) For now I'm very happy with just using `org-journal-open-next-entry`!

**Comment by cslux** [comment]
> OMG! That is such an incredibly facepalm moment for me, I was using that in a previous config but forgot about its existence. Ahhhh.... Thank you!!

Such things happen :-D.

 


> That makes a lot of sense. Well I don't know about having two types of functions, not familiar with designing Emacs packages... Whatever makes the most sense to you :) For now I'm very happy with just using `org-journal-open-next-entry`!

A next/prev functions which are context aware. When the cursor is inside the calendar do the calendar part, when in an org-journal buffer do the other part, for all other cases print a message that the function is used in the wrong context. 
It would a) improve the usability, and b) is easier to maintain.
