### ISSUE TITLE
Do not split windows

### ISSUE THREAD

**Issue by jmburgos** [bastibe/org-journal#269]
**Is your feature request related to a problem? Please describe.**
Calling `org-journal-new-entry` splits the Emacs windows horizontally.  This is a (mild) annoyance when using complex window layouts (e.g. for EXWM users).  Also I tend to leave the org-journal window open (to take notes, etc.), so I prefer that the org-journal buffer is just opened in the current buffer. 

**Describe the solution you'd like**
Have the windows splitting behaviour controlled by a variable (e.g. org-journal-split-window) that may take options (horizontal, vertical) but that allows for not doing any splitting.

**Comment by bastibe** [comment]
We actually have a customization option for that: You may customize `org-journal-find-file` to have org-journal open journal files with any function you like.

**Comment by jmburgos** [comment]
I did know that.  Doing `(setq org-journal-find-file 'find-file)` does exactly what I needed.  Thanks!
