### ISSUE TITLE
PROPERTIES is created outside of headline for the first journal entry  

### ISSUE THREAD

**Issue by reyman** [bastibe/org-journal#271]
**Describe the bug**

If the journal don't already exist, calling `SPC n j j` in doom-emacs create this incorrect file : 

```
:PROPERTIES:
:CREATED:  20200702
:END:
#+TITLE: jeudi, 02 juillet 2020
** 22:15 my entry
```

When i recall `SPC n j j` to create a new entry, i have this error : 

`user-error: Before first headline at position 14 in buffer 2020.org `

If i add properties block into new headline (ex : *2020), problem disapear.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu
 - Emacs Version 26.2, doom emacs 2.0.9
-  Org-journal pinned commit by doom : 24b587978241328fcad40f932602a0a4c1e7d403

**Your Emacs Configuration**

```
(after! org-journal
(setq org-journal-dir "~/Notes/xxx/journal")
(setq org-journal-date-prefix "#+TITLE: ")
(setq org-journal-file-type 'yearly)
(setq org-journal-file-format "%Y.org")
(setq org-journal-date-format "%A, %d %B %Y")
(setq org-journal-enable-agenda-integration t))
```

**Comment by cslux** [comment]
Changing `org-journal-date-prefix` is not allowed for `org-journal-file-type` weekly, monthly, yearly. `C-h v org-journal-date-prefix RET`

```
org-journal-date-prefix is a variable defined in ‘org-journal.el’.
Its value is "* "

  You can customize this variable.

Documentation:
Prefix for ‘org-journal-date-format’.

The default prefix creates an ‘org-mode’ heading.  This default
should not be changed for weekly, monthly or yearly journal
files.  An alternative for daily journal files could be
"#+title: " creating a title rather than a heading.  To create
a "#+title: " for weekly, monthly or yearly (but also daily)
journal files, customize ‘org-journal-file-header’ instead.
```
