### ISSUE TITLE
Change time track format to 12hr

### ISSUE THREAD

**Issue by romariorobby** [bastibe/org-journal#273]
is is possible to change time track format to 12hr?

**Comment by cslux** [comment]
I don't understand. Do you mean org-clock format?

**Comment by romariorobby** [comment]
I mean this 
![2020-07-10_19-00](https://user-images.githubusercontent.com/40323094/87152328-b2b62b00-c2df-11ea-9e8d-f74e931699d3.png)

**Comment by cslux** [comment]
You would need to customize the variable `org-journal-time-format`. The value is passed to `format-time-string`, see `C-h v format-time-string` for all the possibilities. I guess you would need to change `org-journal-time-format` to `"%I:%M"`.

**Comment by romariorobby** [comment]
Oh it changed now! Thanks.
