### ISSUE TITLE
org-publish for org-journal

### ISSUE THREAD

**Issue by rafiks** [bastibe/org-journal#275]
**Describe the bug**
I am trying to use org-publish to publish my org files but the problem is org-journal does not store the file with a .org extension.

**To Reproduce**

**Expected behavior**
org files will be published as an html file.

**Desktop (please complete the following information):**
 - OS: MacOsX
 - Emacs Version 28
- Doom

**Your Emacs Configuration**
(require 'ox-publish)
(setq org-publish-project-alist
      '(
      ;; add all components below here ....
       ("org-notes"
        :base-directory "~/Documents/orgmode/projects/blog"
        :base-extension "org"
        :publishing-directory "~/public_html/"
        :recursive t
        :publishing-function org-html-publish-to-html
        :headline-levels 4
        :auto-preamble t
        )
       ("org-static"
        :base-directory "~/Documents/orgmode/projects/blog"
        :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
        :publishing-directory "~/public_html/"
        :recursive t
        :publishing-function org-publish-attachment
        )
       ("org"
        :components ("org-notes" "org-static"))
      )
    )

**Comment by cslux** [comment]
Hey @rafiks, you can append `.org` to `org-journal-file-format`.
