### ISSUE TITLE
Question: `org-journal-time-` suffix? 

### ISSUE THREAD

**Issue by Silipwn** [bastibe/org-journal#276]
I was interested in knowing if there is any implementation for adding content after a time entry in org-journal?
I noticed that there was a variable for `org-journal-time-prefix`, is there any way to add content after a time entry?
```
* 20:00
<template content>
more content
```
where `template content` can be defined.

**Comment by cslux** [comment]
There is a hook called `org-journal-after-entry-create-hook` you can use for that.
