### ISSUE TITLE
Use `org-store-new-agenda-file-list` to add files to `org-agenda-files`

### ISSUE THREAD

**Issue by stig** [bastibe/org-journal#280]
**Describe the bug**
Org allows `org-agenda-files` to be a directory, or a file on disk. In this case the org-agenda-files are added one line at a time. (I use this because it syncs my Org agenda files nicely between machines using Syncthing.)

**To Reproduce**

1. In your config:

```emacs-lisp
(setq org-agenda-files "~/org/org-agenda-files.txt")
```

**Expected behavior**
I expect that when enabling the org agenda integration for org journal, journal files should be added to org-agenda-files using Org's built-in mechanism for this, rather than manipulating the variable directly. This *should* result in new lines added to the `~/org/org-agenda-files.txt` files.

**Desktop (please complete the following information):**
 - OS: macOS
 - Emacs Version: GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101)) of 2020-06-15

**Your Emacs Configuration**

```
#+begin_src emacs-lisp
(setq org-agenda-files "~/org/org-agenda-files.txt")
(use-package org-journal
  :bind (("C-c j j" . org-journal-new-entry)
	 ("C-c j o" . org-journal-open-current-journal-file))
  :custom
  (org-journal-dir "~/org/journal/")
  (org-journal-date-prefix "#+title: ")
  (org-journal-time-prefix "* ")
  (org-journal-file-format "%Y-%m-%d.org")
  (org-journal-date-format "%A, %d %B %Y")
  (org-journal-enable-agenda-integration t)
  (org-journal-skip-carryover-drawers (list "LOGBOOK")))
```

**Comment by cslux** [comment]
Good catch! Thank you @stig.
