### ISSUE TITLE
doom-emacs says `org-journal-mode-map` a void-variable!

### ISSUE THREAD

**Issue by zenny** [bastibe/org-journal#282]
Hi,

Trying to run doom-emacs with org-journal-mode-map, exactly explained in https://github.com/bastibe/org-journal/blob/master/README.org#kill-journal-buffer-after-saving-buffer-by-dhruvparamhans except keybinding to `C-c n s`:

```
(defun org-journal-save-entry-and-exit()
  "Save buffer of the current day's entry and kill the window."
  (interactive)
  (save-buffer)
  (kill-buffer-and-window))
(define-key org-journal-mode-map (kbd "C-c n s") 'org-journal-save-entry-and-exit)
```

But when running emacs gives init error. When checked with `doom doctor` gave:

``
$ ~/.emacs.d/bin/doom doctor
The doctor will see you now...

> Checking your Emacs version...
> Checking for Emacs config conflicts...
> Checking for private config conflicts...
> Checking for stale elc files...
> Checking Doom Emacs...
! Attempt to load DOOM failed
  (config.el (void-variable org-journal-mode-map))

There are 1 warnings!
✓ Finished! (2.6900s)
```

Any input? Cheers and stay safe,
/z

**Comment by cslux** [comment]
That usually means: You try to access org-journal-mode-map before org-journal was loaded.

Never used doom-emacs, hence, I can't tell you whats the "doom-emacs way" to probably configure packages.

**Comment by cslux** [comment]
But `eval-after-load` works for sure. 

``` emacs-lisp
(eval-after-load "org-journal"
  (define-key org-journal-mode-map (kbd "C-c n s") 'org-journal-save-entry-and-exit))
```

**Comment by zenny** [comment]
> But `eval-after-load` works for sure.
> 
> ```emacs-lisp
> (eval-after-load "org-journal"
>   (define-key org-journal-mode-map (kbd "C-c n s") 'org-journal-save-entry-and-exit))
> ```

@cslux, thanks for prompt reply. So nice of you! Anyway doom reports the same even with appending `eval-after-load` part..

**Comment by cslux** [comment]
Thanks for sharing that information.
