### ISSUE TITLE
Support for inserting entries at the front of the journal file

### ISSUE THREAD

**Issue by adamfaryna** [bastibe/org-journal#283]
**Is your feature request related to a problem? Please describe.**

For any journal other than daily, it's impossible to add another day entry at the front of the journal file. The entries are always inserted at the end of the file.

**Describe the solution you'd like**

The solution is to add an optional parameter to 'org-journal-new-entry' that when 't' would add a new entry at the front of the file rather than the end.

**Describe alternatives you've considered**
none

**Comment by cslux** [comment]
This feature is already on the 2.2.0 milestone, see #209.

Closing.
