### ISSUE TITLE
CREATED property doesn't get created 

### ISSUE THREAD

**Issue by kuleje** [bastibe/org-journal#284]
**Describe the bug**
Running `org-journal-new-entry` doesn't succesfully produce a new entry. I get this error:
`user-error: Created property regex (\(?1:[0-9]\{4\}\)\(?2:[0-9][0-9]\)\(?3:[0-9][0-9]\)) doesn’t match CREATED property value (nil)`
From what I understand, when the weekly file is created it a CREATED property should be created, but it doesn't seem to be there. 

**To Reproduce**

1. Run `org-journal-new-entry`

**Expected behavior**
New entry should be succesfully created

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Manjaro Linux
 - Emacs Version [e.g. 25] 26.3 (Spacemacs 0.300, `develop` branch)

**Your Emacs Configuration**
The part relevant to org-journal.

```
(setq org-journal-dir "~/org/notes/")
(setq org-journal-date-prefix "#+TITLE: ")
(setq org-journal-file-type 'weekly)
(setq org-journal-file-format "%Y-%m-%d") 
(setq org-journal-time-prefix "* ")
(setq org-journal-date-format "%Y, week %W")
(setq org-journal-time-format "%Y-%m-%d %H:%M")
```

**Comment by benisjammin** [comment]
I've been getting the same error for the past several days, here's what the debugger gives. The error itself seems to be thrown by `org-journal-entry-date->calendar-date`

```emacs-lisp
Debugger entered--Lisp error: (error "Created property regex (\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)) doesn’t match CREATED property value (nil)")
  signal(error ("Created property regex (\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)) doesn’t match CREATED property value (nil)"))
  error("Created property regex (%s) doesn't match CREATED property value (%s)" "\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)" nil)
  org-journal-entry-date->calendar-date()
  org-journal-file->calendar-dates("/path-to-my/org-journal/20200803")
  org-journal-new-entry(nil)
  funcall-interactively(org-journal-new-entry nil)
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)
```

**Comment by cslux** [comment]
In case of `org-journal-new-entry`, this error means we couldn't find the entry after which the new entry should be inserted.

@benisjammin `org-journal-date-prefix` shouldn't be changed  when using  weekly, monthly or yearly journal files, see `C-h v org-journal-date-prefix`.

@benisjammin What is your setup?

**Comment by benisjammin** [comment]
Here is the relevant part of my config.
I don't recall changing any part of this in several months, whereas the error showed up one or two weeks ago.

```emacs-lisp
 '(org-journal-carryover-delete-empty-journal (quote ask))
 '(org-journal-carryover-items "TODO=\"TODO\" \"IN-PROGRESS\" \"ON-HOLD\"")
 '(org-journal-date-format "%A, %d %B %Y")
 '(org-journal-date-prefix "* ")
 '(org-journal-dir "~/path-to-my/org-journal/")
 '(org-journal-enable-agenda-integration t)
 '(org-journal-enable-cache t)
 '(org-journal-enable-encryption nil)
 '(org-journal-encrypt-journal nil)
 '(org-journal-encrypt-on (quote kill-save-hook))
 '(org-journal-file-type (quote weekly))
 '(org-journal-find-file (quote find-file))
 '(org-journal-follow-mode t)
 '(org-journal-hide-entries-p nil)
 '(org-journal-time-format "%Hh%M
")
 '(org-journal-time-format-post-midnight "+%Hh%Mm
")
```

I tried again this morning. A new weekly journal (`20200810`) was created, but `C-x C-s` gives the following debugger report:

```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument stringp (1 4 2018))
  #f(compiled-function (key --cl-var--) #<bytecode 0x3a259d>)("/path-to-my/org-journal/20180104" ((1 4 2018)))
  maphash(#f(compiled-function (key --cl-var--) #<bytecode 0x3a259d>) #<hash-table equal 388/1095 0x10f83bd>)
  org-journal-dates-puthash()
  org-journal-after-save-hook()
  run-hooks(after-save-hook)
  basic-save-buffer(t)
  save-buffer(1)
  funcall-interactively(save-buffer 1)
  call-interactively(save-buffer nil nil)
  command-execute(save-buffer)
```
I get the `(wrong-type-argument stringp (1 4 2018))` error every time.

Additionally `C-c C-b` does not seem to find the previous journal entry throwing, "No journal entry before this one."

I'm not sure if this is directly related or if this warrants a unique bug report

**Comment by cslux** [comment]
Hmm, calling `org-journal-invalidate-cache` should fix it.

**Comment by benisjammin** [comment]
That did the trick, I'll update if it shows up again. Thanks!

**Comment by cslux** [comment]
Yes please, let me know if it shows up again. But I think this is my fault.
