### ISSUE TITLE
Problems with active timestamps in carry-over items

### ISSUE THREAD

**Issue by turkja** [bastibe/org-journal#285]
**Bug description**

If I have a TODO-item (didn't try any other carry-over types) with embedded active timestamp, it loses the time part of the timestamp when carried over to next journal.

**How to reproduce**
Create a simple TODO-entry like this:

```
* TODO [2020-08-09 18:00] things to do
I want to do this thing tomorrow <2020-08-10 Mon 15:00>
```

When this entry is carried over to next journal, it becomes like this:

```
* TODO [2020-08-09 18:00] things to do
I want to do this thing tomorrow  <2020-08-10 Mon>
```

**Expected behavior**
Should be like this in the new journal:

```
* TODO [2020-08-09 18:00] things to do
I want to do this thing tomorrow  <2020-08-10 Mon 15:00>
```

**Sofware versions**
 - Emacs Version 26.3
- org-journal 2.1.0

**Emacs Configuration**

```
(setq org-journal-file-format "%Y%m%d")
(setq org-journal-enable-agenda-integration t)
(setq org-journal-time-format "[%Y-%m-%d %R] ")
(setq org-journal-encrypt-journal t)
(setq org-journal-enable-cache t)

```

**Comment by cslux** [comment]
@turkja Thanks for the report. Should be fixed with commit b8bd786.
