### ISSUE TITLE
Cannot create new entry after updating Emacs to 27.1

### ISSUE THREAD

**Issue by kondanta** [bastibe/org-journal#287]
**Describe the bug**
When I try to create new entry (both with (org-journal-today) and (org-journal-new-entry) it returns to an error after updating Emacs to 27.1.

**To Reproduce**
- Open Emacs
- M-x org-journal-today RET

**Expected behavior**
I expect it to open a new file with today's date

**Screenshots**
![](https://i.imgur.com/yc1OQkz.png)
**Desktop (please complete the following information):**
 - OS: both macOS Catalina 10.15.6  and Linux 5.7
 - Emacs Version: 27.1

**Your Emacs Configuration**
The part relevant to org-journal.
```emacs-lisp
  (use-package org-journal
    :bind
    ("C-c n j" . org-journal-new-entry)
    ("C-c n t" . org-journal-today)
    :custom
    (org-journal-dir "~/.journal/")
    (org-journal-date-prefix "#+TITLE: ")
    (org-journal-file-format "%Y-%m-%d.org")
    (org-journal-date-format "%A, %d %B %Y"))
  (defun org-journal-today ()
    (interactive)
    (org-journal-new-entry t))
  (setq org-journal-enable-agenda-integration t)
```

**Comment by cslux** [comment]
Was this a major Emacs upgrade? If so, you need to recompile all packages again, see `byte-recompile-directory`. I use Emacs 27.0.91 on all my machines (self compiled), and haven't seen this error.

**Comment by kondanta** [comment]
I was under the impression that org-journal's the issue. However, I've tried couple of other functionalities, like expand region, and org-timestamp they have also prompted the same error. So I believe this is a problem of mine rather than the project. Thanks for the information regarding recompilation. I was using Emacs 26.3 before upgrading to 27.1. So there is definitely something wrong with my config. 😞

**Comment by cslux** [comment]
Seems to be, but it's not your config. I'm pretty sure its because of the compiled elisp files in your elpa directory. The line `byte-code(....)` looks very suspicious. If you are using `use-package` or similar to manage your Emacs packages, you can just delete the ~/.emacs.d/elpa/ or ~/.config/emacs/elpa directory as well, and restart Emacs. All your packages will then be reinstalled and of course recompiled, which should fix the error. But first try this: Hit the keys `M-:` (`eval-expression`), and enter `(byte-recompile-directory "~/.emacs.d/elpa" nil t)`.

**Comment by kondanta** [comment]
Alright, I've solved my issue on macOS and will try it on Linux evening. For anyone who might get the same issue, here's links for the solution:
- https://emacs.stackexchange.com/questions/5552/emacs-on-android-org-mode-error-wrong-type-argument-stringp-require-t/26875#26875
- https://www.reddit.com/r/emacs/comments/flb0vc/wrongtypeargument_stringp_require_info_with_emacs/g14sboi?utm_source=share&utm_medium=web2x

**Comment by cslux** [comment]
Glad you found a fix, and thanks for sharing.
