### ISSUE TITLE
org-journal-previous-entry takes me to first journal entry

### ISSUE THREAD

**Issue by sergiusens** [bastibe/org-journal#294]
**Describe the bug**
Seem that since the merge of https://github.com/bastibe/org-journal/commit/7f96657df3875b9b3633fb903e7cdaa9f1d9e117 org-journal-previous-entry always takes me to the first journal entry I have

**To Reproduce**
- Use Daily journal file
- Locate a recent entry from many
- call org-journal-previous-entry

**Expected behavior**
I expect going to the previous journal entry

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (KDE Neon)
 - Emacs Version 27.1

**Your Emacs Configuration**
The part relevant to org-journal.
```
  (use-package org-journal
    :ensure t
    :defer t
    :bind
    ("C-c j j" . org-journal-new-entry)
    :custom
    (org-journal-dir "~/org/journal/")
    (org-journal-enable-agenda-integration t)
    (org-journal-file-format "%Y-%m-%d.org")
    :init
    ;; Prefijo para cargar org-journal
    (setq org-journal-prefix-key "C-c j ")
    :config
    (defun ss/org-journal-file-header-func (time)
      "Custom function to create journal header."
      (concat
       (pcase org-journal-file-type
         (`daily "#+TITLE: Agenda Diaria\n#+STARTUP: content")
         (`weekly "#+TITLE: Agenda Semanal\n#+STARTUP: content")
         (`monthly "#+TITLE: Agenda Mensual\n#+STARTUP: content")
         (`yearly "#+TITLE: Agenda Anual\n#+STARTUP: content"))))

    (defun ss/new-buffer-p ()
      (not (file-exists-p (buffer-file-name))))

    (defun ss/org-journal-daily ()
      (let ((template-file (expand-file-name "agenda-diaria.org" ss/org-template-directory)))
        (when (ss/new-buffer-p)
          (save-excursion
            (goto-char (point-max))
            (insert-file-contents template-file)))))

    (add-hook 'org-journal-after-header-create-hook #'ss/org-journal-daily)

    (setq org-journal-file-header 'ss/org-journal-file-header-func
	      org-journal-carryover-items "TODO=\"TODO\"|TODO=\"WAIT\"|TODO=\"HOLD\""))
```

**Comment by cslux** [comment]
Fixed via e7c51c4. Thanks for the report!

**Comment by sergiusens** [comment]
Oh, sorry for the double report! I got a Github 404 on my first try and did not check if my submit actually went through

**Comment by cslux** [comment]
No problem. 

On September 12, 2020 5:29:21 PM UTC, Sergio Schvezov <notifications@github.com> wrote:
>Oh, sorry for the double report! I got a Github 404 on my first try and
>did not check if my submit actually went through

-- 
Christian Schwarzgruber
T: +43 699 194 166 34
E: c.schwarzgruber.cs@gmail.com
