### ISSUE TITLE
Saving a file is slow due to agenda file update

### ISSUE THREAD

**Issue by proudot** [bastibe/org-journal#299]
Hi and thanks again for this great piece of software, 

Saving a daily journal file is quite slow because of the agenda file update (See profiler below). Any quick fix toward that problem ?

```
- command-execute                                                 245  88%
 - call-interactively                                             245  88%
  - funcall-interactively                                         245  88%
   - save-buffer                                                  198  71%
    - basic-save-buffer                                           198  71%
     - run-hooks                                                  197  71%
      - org-journal-update-org-agenda-files                       196  71%
       - org-journal-search-build-file-list                       196  71%
        - org-journal-list-files                                  195  70%
         - seq-filter                                             184  66%
          - seq-map                                               184  66%
           - apply                                                184  66%
            + #<compiled 0x1002bd551>                             184  66%
         + directory-files-recursively                             11   3%
        + org-journal-file-name->calendar-date                      1   0%
        org-journal-serialize                                       1   0%
     + basic-save-buffer-1                                          1   0%
   + smex                                                          47  17%
+ ...                                                              30  10%
+ redisplay_internal (C function)                                   1   0%
```

**Comment by cslux** [comment]
> Any quick fix toward that problem ?

Unfortunately not. How many journal files do you have?

**Comment by proudot** [comment]
I have seven agenda-files, the biggest one is 3000 lines or <100Kb. I am on windows 10, maybe that can affect performances ?

I also have org-journal-enable-agenda-integration set to t. However I have less than 250 files in my journal directory.

**Comment by cslux** [comment]
>  am on windows 10, maybe that can affect performances ?

Possible. Puh, I think it's not really an org-journal performance thing. All we do, is figure out which files should be included. An org-agenda parses them.

**Comment by proudot** [comment]
But could we disable the org-agenda parsing upon saving ? What is its use ?

**Comment by cslux** [comment]
No, unless you turn off the agenda integration all together.

**Comment by proudot** [comment]
For the record, I got around that problem by switching to yearly journal. Windows does not seems to be playing well with hundreds of daily files.
