### ISSUE TITLE
Allow org-journal to use .org suffix

### ISSUE THREAD

**Issue by hammerandtongs** [bastibe/org-journal#30]
As opposed to altering org-agenda-file-regexp (which seems more likely to have side effects and be error prone in installation) I would like to have the option of simply defining an org-journal-file-suffix to be ".org". The current behavior could be achieved by leaving it undefined.

**Comment by bastibe** [comment]
Thank you for the feedback. You can do this right now by `(setq org-journal-file-format "%Y%m%d.org")` (the default is `"%Y%m%d"`).

I think that this is a more general solution than specifying a specific suffix. Please let me know if you disagree. 

Also, I'd be interested to know your use case for the agenda. Personally, I found agenda searches to be unpleasantly slow and error prone, and I stopped using them since we added a built-in search to org-journal.

**Comment by hammerandtongs** [comment]
Thanks, this did seem to work.

I'm using the journal feature quite a bit but not really any of the extra features atm so my use case isn't really even formed yet.

If it were up to me I'd like to see my journal entries in the agenda view which I use quite a bit but not at all the calendar.

Looking at calendar my entries aren't even showing up so I'll have to sort that out.

**Comment by MBuchaus** [comment]
I have found by doing this the functionality of org-journal fails.  the prev and next functions as well as search no longer work.  yet if left to numeric without .org  orgzly will not see them as well as (at least in my spacemacs) they will not be seen by agenda.  I've found that if I setup a symlink to the numeric file with the same name + .org  I get the function i'm looking for.

**Comment by bastibe** [comment]
@MBuchaus if functionality breaks with a non-standard `org-journal-file-format`, that is a bug. If you found such a bug, please open a new issue. I believe that I fixed that particular problem in a recent version of org-journal.

In retrospect, it would have been better to go with `*.org` files right from the start. But org-journal started out as an extension of [PersonalDiary](https://www.emacswiki.org/emacs/PersonalDiary), which used the numeric file name convention. And now we can't just change the file format without breaking every existing user's journal.

**Comment by MBuchaus** [comment]
Ok I'm prepping a full issue post.
