### ISSUE TITLE
Reschedule an entry in the future

### ISSUE THREAD

**Issue by brabalan** [bastibe/org-journal#300]
I really like `org-journal-new-scheduled-entry` and the ability to carry-over entries for simple tasks. However sometimes I need the entry to be rescheduled not to the next day (which is automatic), but further in the future. Would you consider implementing a function to reschedule an existing entry?

**Comment by cslux** [comment]
`org-time-stamp` isn't enough?

**Comment by cslux** [comment]
Forget my last message :-). 

When inside an org-journal entry, and the function (org-journal-reschedule-entry) gets called, and the entry contains TODOs with a simple timestamp (<...>):

  1. Provide the calendar view to let the user enter a new future date 
      Should be limited to only future dates, not sure if that is possible with the standard date picker, if not, and the date is in the past, abort with an `user-error` message.
  2. Move and update the entry to match the new date.

That should work.

**Comment by brabalan** [comment]
That would be perfect, thanks!

**Comment by cslux** [comment]
@brabalan You can now call `org-journal-reschedule-scheduled-entry` to move the entry to the future.

**Comment by brabalan** [comment]
I have an issue with the generated timestamp when there is a `Properties` drawer. Here is the entry before calling `org-journal-reschedule-scheduled-entry`:
```
* TODO test
:PROPERTIES:
:LAST_REVIEW: 2020-10-21 Wed
:NEXT_REVIEW: 2020-11-21 Sat
:END:
 <2020-11-02>
 [2020-11-02 Mon 10:08]
```
and here it is after:
```
* TODO test
:PROPERTIES:
:LAST_REVIEW: 2020-10-21 Wed
:NEXT_REVIEW: 2020-11-21 Sat
:END:
 <2020-11-02>
 [2020-11-02 Mon 10:08]
<2020-11-03 Tue>
```

All work well if there is no property drawer.
