### ISSUE TITLE
org-journal-new-entry fails after update

### ISSUE THREAD

**Issue by fapdash** [bastibe/org-journal#301]
**Describe the bug**
When I run `org-journal-new-entry` it creates the proper file and date headline but fails to add an entry.
So it happens when I call the function interactively as well as programatically.
This also breaks all of my org-capture templates because the `org-journal-find-location` function fails.

The following error gets shown in the `Messages` buffer:
`user-error: Before first headline at position 1 in buffer 20200928`

**To Reproduce**
To make sure that this is not related to my org-journal config I switched to a very basic config but the problem persisted.

**Expected behavior**
A new entry heading gets inserted.

**Screenshot**
![screenshot_107](https://user-images.githubusercontent.com/459631/96377144-c34e2b00-1183-11eb-8322-edb4d988584d.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Emacs Version: GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.30) of 2019-09-16
- org-journal Version: 20200912.1339

**Your Emacs Configuration**
```
(use-package org-journal
  :ensure t
  :defer t
  :init
  ;; Change default prefix key; needs to be set before loading org-journal
  (setq org-journal-prefix-key "C-c j ")
  :config
  (setq org-journal-dir org_journal))
```

**Comment by cslux** [comment]
Does calling `org-journal-invalidate-cache` fix the problem?

**Comment by fapdash** [comment]
Yes, it does. Thank you!

I'm a bit confused about this though. The README seems to indicate that caching is only activated via the variable `org-journal-enable-cache` and this is my help output:

```
org-journal-enable-cache is a variable defined in ‘org-journal.el’.
Its value is nil

Documentation:
If ‘t’, journal entry dates will be cached for faster calendar operations.

You can customize this variable.

[back]
```

**Comment by cslux** [comment]
Ah sorry. Needs, a little rework.

**Comment by cslux** [comment]
Closing this issue. I'll create a new issue to enhance the caching implementation, and remove the option `org-journal-enable-cache`.
