### ISSUE TITLE
Current day's TODOs carry over when creating a future scheduled entry

### ISSUE THREAD

**Issue by pace577** [bastibe/org-journal#306]
**Describe the bug**
When I create a future scheduled entry using `org-journal-new-scheduled-entry`, say 5 days into the future, all the current day TODO items are carried over to that future date entry. I work with monthly journals.

**To Reproduce**

- Set `org-journal-file-type` to `'monthly`
- Create an new journal entry with `org-journal-new-entry`
- Turn it into a TODO item using `org-todo`
- Create a future journal entry with `org-journal-new-scheduled-entry`

**Expected behavior**
The current day TODO items should stay as they are. Only the scheduled entry must be created at the future date.

**Screenshots**
![org-journal-todo-entry-issue-1](https://user-images.githubusercontent.com/49357590/97068914-70dc9680-15e9-11eb-99a8-03207a751cf9.png)
![org-journal-todo-entry-issue-2](https://user-images.githubusercontent.com/49357590/97068922-74701d80-15e9-11eb-8eaf-91a1b01106b1.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Emacs Version 27.1

**Your Emacs Configuration**
I'm using Doom Emacs with the `(org +roam +journal)` module
Tested this behavior using `doom/sandbox` excluding private configuration.

**Comment by cslux** [comment]
Hey, thanks for the report. I haved fixed this two days ago. https://github.com/bastibe/org-journal/commit/00f3d39cd5ba2d199d75a1d2e95f4fa37fac1f8c#diff-799bc0c274211f453977229b6ab043e5372808a95866f76ea0c5a49c3f914b49R1016

If it still occurs with the new version reopen this issue.
