### ISSUE TITLE
how to get org-journal-new-scheduled-entry behave similarly to org-schedule (i.e. "SCHEDULED:" keyword + correct duration)?

### ISSUE THREAD

**Issue by Ziip-dev** [bastibe/org-journal#308]
**Describe the bug**
When scheduling a future appointment I run `org-journal-new-scheduled-entry`, select the corresponding day in the calendar view, then type e.g. `14:00+2` (everything seems to be interpreted correctly as the overlay indicates - cf. screenshot 1).
But the entry that `org-journal` generates when I validate has no `SCHEDULED:` keyword (unlike `org-schedule`), and the time of the appointment has shifted strangely (cf. screenshot 2).

**To Reproduce**
- Call `org-journal-new-scheduled-entry`
- Select a future day in the calendar view
- Type the time of the appointment manually with its duration
- Press `RET` to generate the entry

I doubt something this big really comes from a real bug and will be reproducible, but as I am still a beginner with `org-journal` I hope I can get some help here.

**Expected behavior**
A new entry in `org-journal` with the `SCHEDULED:` keyword like with `org-schedule` and the correct time and duration (cf. screenshot 3).

**Screenshots**
screenshot 1
![screen1](https://user-images.githubusercontent.com/62331138/97717364-ff0ebc00-1ac4-11eb-88f3-03edb1d884b2.png)

screenshot 2
![screen2](https://user-images.githubusercontent.com/62331138/97717372-03d37000-1ac5-11eb-9dea-c856efa90787.png)

screenshot 3
![screen3](https://user-images.githubusercontent.com/62331138/97718982-d982b200-1ac6-11eb-8f44-3a991b2ca040.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Emacs Version 27.1

**Your Emacs Configuration**
```
(use-package org-journal
  :custom
  (org-journal-dir "~/Documents/org/roam/dailies/")
  (org-journal-file-type 'daily)
  (org-journal-date-prefix "#+TITLE: ")
  (org-journal-file-format "%Y-%m-%d.org")
  (org-journal-date-format "%A, %d %B %Y")
  :config
  (setq org-journal-find-file #'find-file-other-window
        org-journal-enable-agenda-integration t))
```

**Comment by cslux** [comment]
Screenshot 2 is correct, this is how it is currently implemented. However, I'm open for any changes which make it more like the expected one. If I would be a user of this package, I would have assumed, based on the function name `org-journal-new-scheduled-entry`, that a new (TODO) entry will be created with a scheduled timestamp. But that is not how it works at the moment, we create an active timestamp, any ignore the given time, we just interpret the selected calendar date (day under cursor).

I currently work on issue #300, and I really think we should either change the name of the function, or create a scheduled entry analogue to `org-schedule`, or maybe even use `org-capture` instead of providing our own function(s). For the later we could provide some sane default `org-capture` templates, and populate `org-capture` when e.g. `org-journal-setup-org-capture-templates` is `t`. If we use `org-capture` we would still need to provide a function for re-scheduling, which sole purpose is to move that item to future, either a single entry your the hole marked region.

Those are just some thoughts, I would be very happy about some feedback/suggestion from you guys :-)!


@Ziip-dev If you want scheduled items you must use `org-capture` for now, or maybe forever :-P, see https://github.com/bastibe/org-journal#journal-capture-template.

**Comment by cslux** [comment]
In general we should use the logic from `org` as much as possible, this makes it much easier to maintain.

**Comment by cslux** [comment]
> IMO using `org-capture` for this is clearly feasible but I see it more like a workaround as it can be quite challenging to set up for non-hardcore users and would deviate from the current simple and appreciable functions of `org-journal`.

I agree, but we would create the `org-capture` templates for the user, and either add it be default to `org-capture` or only when a customizeable variable is `t`. Anyway, I need to play around with that idea on separate branch to get a better idea about that.

**Comment by Ziip-dev** [comment]
Thanks for your interest, I am going to follow the evolution of the question.
Please don't hesitate if you need me to test some things related to this issue!

Simple curiosity question though (sorry for my scarce knowledge around elisp): isn't it possible for a modified `org-journal-new-scheduled-entry` to act as a wrapper around `org-schedule` in order to avoid writing a new template?

**Comment by Linerre** [comment]
> **Describe the bug**
> When scheduling a future appointment I run `org-journal-new-scheduled-entry`, select the corresponding day in the calendar view, then type e.g. `14:00+2` (everything seems to be interpreted correctly as the overlay indicates - cf. screenshot 1).
> But the entry that `org-journal` generates when I validate has no `SCHEDULED:` keyword (unlike `org-schedule`), and the time of the appointment has shifted strangely (cf. screenshot 2).
> 
> **To Reproduce**
> 
> * Call `org-journal-new-scheduled-entry`
> * Select a future day in the calendar view
> * Type the time of the appointment manually with its duration
> * Press `RET` to generate the entry
> 
> I doubt something this big really comes from a real bug and will be reproducible, but as I am still a beginner with `org-journal` I hope I can get some help here.
> 
> **Expected behavior**
> A new entry in `org-journal` with the `SCHEDULED:` keyword like with `org-schedule` and the correct time and duration (cf. screenshot 3).
> 
> **Screenshots**
> screenshot 1
> ![screen1](https://user-images.githubusercontent.com/62331138/97717364-ff0ebc00-1ac4-11eb-88f3-03edb1d884b2.png)
> 
> screenshot 2
> ![screen2](https://user-images.githubusercontent.com/62331138/97717372-03d37000-1ac5-11eb-9dea-c856efa90787.png)
> 
> screenshot 3
> ![screen3](https://user-images.githubusercontent.com/62331138/97718982-d982b200-1ac6-11eb-8f44-3a991b2ca040.png)
> 
> **Desktop (please complete the following information):**
> 
> * OS: Ubuntu 18.04
> * Emacs Version 27.1
> 
> **Your Emacs Configuration**
> 
> ```
> (use-package org-journal
>   :custom
>   (org-journal-dir "~/Documents/org/roam/dailies/")
>   (org-journal-file-type 'daily)
>   (org-journal-date-prefix "#+TITLE: ")
>   (org-journal-file-format "%Y-%m-%d.org")
>   (org-journal-date-format "%A, %d %B %Y")
>   :config
>   (setq org-journal-find-file #'find-file-other-window
>         org-journal-enable-agenda-integration t))
> ```

Dear Ziip-Dev,

Hello, this is an off-topic question: what is theme you use? Could you let me know?

I tried to find your repos which unfortunately you don't have any public. I also tried to find your email yet failed again. With no way to contact you I just have to comment on this issue discussion thread. 

The colorscheme is very similar to deus that I'm using for my terminal. Yet I just didn't find any one for Emacs. Really want to know this. Many thanks in advance.

**Comment by Ziip-dev** [comment]
> 
> Dear Ziip-Dev,
> 
> Hello, this is an off-topic question: what is theme you use? Could you let me know?
> 
> I tried to find your repos which unfortunately you don't have any public. I also tried to find your email yet failed again. With no way to contact you I just have to comment on this issue discussion thread.
> 
> The colorscheme is very similar to deus that I'm using for my terminal. Yet I just didn't find any one for Emacs. Really want to know this. Many thanks in advance.

Hi @Linerre,

I have nothing public on the internet yet. As I am still quite a neophyte when it comes to the dotfiles world, system ricing etc. I prefer to build my stuff silently to avoid overloading interested users with medium quality content.
However, releasing everything in a future blog + public repo is something I'd like to do ("future" is very relative here though, more like one day).

By the way, the theme I am using is [gruvbox](https://github.com/Greduan/emacs-theme-gruvbox) :)

**Comment by Linerre** [comment]
> > Dear Ziip-Dev,
> > Hello, this is an off-topic question: what is theme you use? Could you let me know?
> > I tried to find your repos which unfortunately you don't have any public. I also tried to find your email yet failed again. With no way to contact you I just have to comment on this issue discussion thread.
> > The colorscheme is very similar to deus that I'm using for my terminal. Yet I just didn't find any one for Emacs. Really want to know this. Many thanks in advance.
> 
> Hi @Linerre,
> 
> I have nothing public on the internet yet. As I am still quite a neophyte when it comes to the dotfiles world, system ricing etc. I prefer to build my stuff silently to avoid overloading interested users with medium quality content.
> However, releasing everything in a future blog + public repo is something I'd like to do ("future" is very relative here though, more like one day).
> 
> By the way, the theme I am using is [gruvbox](https://github.com/Greduan/emacs-theme-gruvbox) :)

Hi @Ziip-dev 
Thanks so much for your reply. Surprised to know it is indeed gruvbox! I'm using it too, though a bit different from yours. The one I mentioned is in fact a fork of gruvbox. Looking forward to your public repos and other projects in the future. Best wishes. Also thanks go to org-journal.
