### ISSUE TITLE
org-journal-reschedule-scheduled-entry does not update time stamp when there is a properties drawer

### ISSUE THREAD

**Issue by brabalan** [bastibe/org-journal#309]
**To Reproduce**
Here is the entry before calling org-journal-reschedule-scheduled-entry:

```
* TODO test
:PROPERTIES:
:LAST_REVIEW: 2020-10-21 Wed
:NEXT_REVIEW: 2020-11-21 Sat
:END:
 <2020-11-02>
 [2020-11-02 Mon 10:08]
```

and here it is after:

```
* TODO test
:PROPERTIES:
:LAST_REVIEW: 2020-10-21 Wed
:NEXT_REVIEW: 2020-11-21 Sat
:END:
 <2020-11-02>
 [2020-11-02 Mon 10:08]
<2020-11-03 Tue>
```

All work well if there is no property drawer.

**Expected behavior**
The old timestamp would be removed.

**Comment by cslux** [comment]
Thanks for opening another issue for that. I hope I find time today to fix it.

**Comment by cslux** [comment]
I couldn't reproduce it today. Those it still not work for you?

**Comment by brabalan** [comment]
I'm sorry but I no longer use this, so I cannot confirm the problem went away.

**Comment by cslux** [comment]
Thanks for letting me know, closing than!
