### ISSUE TITLE
Provide sample config file

### ISSUE THREAD

**Issue by k0377** [bastibe/org-journal#31]
Hey there, me again! :smiley_cat: 

Would be nice to see a sample configuration in the readme. Most of us dont even know how to write elisp but still want to use the power of emacs and orgmode. This would be really helpful so I just can go here and c/p and change what i want. Maybe from defaults.

Happy easter! :rabbit:

**Comment by bastibe** [comment]
Frankly, there isn't much I can write about configuration, since I don't have anything configured, personally. I like to think that org-journal works pretty well out of the box.

I try to make sure that org-journal is fully configurable through `customize`, though. Please have a look at *Customization* -> *Applications* -> *Org Journal* for more detail on what you can configure. Please let me know if I could improve the descriptions of any of these settings.

**Comment by k0377** [comment]
Oh great, I know this but only from theme settings but didn't thought it is available for org-journal as well. The only thing I change is the `org-journal-dir` and the file format. I think `.org` would be a better default file format, but thats just my opinion.

**Comment by bastibe** [comment]
Funny enough, I actually agree about the file format! 

This started out as a small extension of `journal-mode`, and just continued using `journal-mode`'s file names. It then grew gradually grew bigger, and maybe would have warranted it's own file names at some point. But at that time, it already had too many active users to make such a fundamental change without good justification. 

As much as I would like to change the default file format now, it would break every user's installations--that's just not worth it. So there you have it. Feel free to use the "correct" file name convention. That's what Emacs is for.

Speaking of what Emacs is for: I highly recommend looking around in the customization menu and reading the Emacs manual. There's many a gem hidden there that you wouldn't expect! Happy Easter!

**Comment by k0377** [comment]
I just tried to set with M-x customize and change Org Journal File Format to `%Y%m%d.org`. But when I hit save on the STATE button and choose `Save for future sessions`, the format is still the same. I dont know if I used M-x customize the right way, I just used the search in there and found the Org Journal settings. I dont know why my changes dont affect the file format.

**Comment by bastibe** [comment]
Did you resolve this issue? If not, please open an issue, and I'll look into it.

**Comment by k0377** [comment]
No, `M-x customize` still doesnt solve this issue. Now I configured all in my dotfiles. I dont know if this may cause the issue, because I symlinked all configs to my dotfiles. Also I dont want you to struggle with anymore. :heart_eyes_cat:
