### ISSUE TITLE
Date format used to determine if its a journal - breaks if locale changes

### ISSUE THREAD

**Issue by rileyrg** [bastibe/org-journal#312]
I changed my locale recently which meant that when I create a journal item it is now of this form:-

> * Donnerstag, 19.11.2020
> ** 09:54 no python exxecutable?!?
> ** 09:55 virtualenv allows different python versions?
> 

previously like this:-

> * Thursday, 12/11/20
> ** 06:26 trying to set org refile default used from global org capture :emacs:
> 

When in the first file above I can merrily go to previous journal until I reach the second one then it doesn't work anymore.

Now, I realise the date format change was down to me but I'm wondering if org-journal can be a bit more tolerant here? Or do I need to specify a "org date format" that is nothing to do with locale and stick with that? I'm easy either way but just wonder what would be the best way forward?

**Comment by bastibe** [comment]
I don't quite understand. Org-journal reads dates from the file names, not the file contents. Could you explain your error in a bit more detail?

**Comment by cslux** [comment]
For daily journal files we use the `org-journal-date-format` to search for an existing entry in that file. Hence, it does not find it. For weekly, monthly or yearly journal file we use the CREATED property as an anchor. If you change `org-journal-date-format` or org-journal-created-property-format` to something which is locale independent you are fine.
