### ISSUE TITLE
Weekly journal, creates a new file for each day

### ISSUE THREAD

**Issue by vicrdguez** [bastibe/org-journal#316]
**Describe the bug**
I'm trying to configure my org-journal to work on a weekly basis. I configured the file type accordingly, but I notice that when I create a new entry, a new file is created instead of appending the entry to the last file. 
I end for example with two files:
2020-12-26(52).org
2020-12-27(52).org

In fact if I try to jump to the current journal file, It searches for 2020-12-27(52).org instead of sticking to the first one which should be the only file for all the week.
I'm even thinking how I can get rid of the day number, since I only need the week, but I guess it might cause some problems when searching for the current journal file too.

**To Reproduce**
Set up the file type to weekly, and try to create a new entry in two different days of the same week

**Expected behavior**
Once you add a journal entry (and thus the file is created) keep appending entries to the same file until the end of the week

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOs
 - Emacs Version [e.g. 27.1]

**Your Emacs Configuration**
```elisp
        ;;;;;;;;;;;;;;;;;;;;;;
        ;;Org journal config;;
        ;;;;;;;;;;;;;;;;;;;;;;
        org-journal-dir "~/vaults/org/journal/"
        org-journal-date-format "%B %d, %Y (%A) "
        org-journal-file-format "%Y-%m-%d(W%V).org"
        org-journal-created-property-timestamp-format "%Y%m%V%d"
        org-journal-file-header "#+title: Weekly Journal %B %Y - Week %V\n#+startup: folded\n#+category: Journal"
        org-journal-file-type "weekly"
        org-journal-enable-agenda-integration t
```
`org-extend-today-until` is default (0)
`org-journal-start-on-weekday` is default too (1) which should be Monday if I'm not wrong.

Thanks for the help!

**Comment by vicrdguez** [comment]
As a comment, I've been checking out the code, trying to solve this my self (or at least understand what is happening) but elisp at this moment is difficult to understand for me. I'm used to very different languages.
With this I mean, that a technical explanation (if you think is needed) would be great! since I love to understand how things work under the scenes.

Cheers!

**Comment by vicrdguez** [comment]
Update with more. info:
I've commented the line where I modify the created property format, and commented the agenda integration line.
Seems like using `org-journal-new-entry` creates a new files for this day but searches the CREATED property of a previous day of the week, which cannot find because is in another file.
If I add the entry of the previous file to this new created, everything works

## Debugger output: 
```
(search-failed "[ \11]*:CREATED:[ \11]+20201226[ \11]*$")
  re-search-forward("[ \11]*:CREATED:[ \11]+20201226[ \11]*$" nil nil nil)
  org-journal--search-forward-created((12 26 2020))
  org-journal--goto-entry((12 26 2020))
  org-journal--open-entry(t t)
  org-journal--carryover()
  org-journal-new-entry(nil)
  #<subr funcall-interactively>(org-journal-new-entry nil)
  apply(#<subr funcall-interactively> (org-journal-new-entry nil))
  funcall-interactively(org-journal-new-entry nil)
  #<subr call-interactively>(org-journal-new-entry nil nil)
  apply(#<subr call-interactively> (org-journal-new-entry nil nil))
  explain-pause--wrap-call-interactively(#<subr call-interactively> org-journal-new-entry nil nil)
  apply(explain-pause--wrap-call-interactively #<subr call-interactively> (org-journal-new-entry nil nil))
  call-interactively(org-journal-new-entry nil nil)
  command-execute(org-journal-new-entry)

```

**Comment by cslux** [comment]
Sorry for the late reply! Not sure if your still using org-journal, but if you do, here is the possibly reason. `org-journal-file-type` value should be a symbol not a string. 

``` emacs-lisp
(setq org-journal-file-type 'weekly)
```
If it still doesn't work, please let me know it.
