### ISSUE TITLE
Error: Wrong number of arguments: (3 . 4), 2

### ISSUE THREAD

**Issue by bladrome** [bastibe/org-journal#319]
**Describe the bug**
org-journal.el:400:1: Error: Wrong number of arguments: (3 . 4), 2

**To Reproduce**
make compile

**Expected behavior**
compile pass

**Screenshots**

git:(master c083648) > make compile
emacs -Q -batch -L . -f batch-byte-compile tests/org-journal-test.el org-journal.el
Source file `/home/bladrome/.config/emacs/.local/straight/repos/org-journal/org-journal.el' newer than byte-compiled file; using older file

In toplevel form:
org-journal.el:221:1: Warning: custom-declare-variable
    `org-journal-hide-entries-p' docstring wider than 80 characters
org-journal.el:225:1: Warning: custom-declare-variable
    `org-journal-enable-encryption' docstring wider than 80 characters
org-journal.el:244:1: Warning: custom-declare-variable
    `org-journal-enable-agenda-integration' docstring wider than 80 characters
org-journal.el:254:1: Warning: custom-declare-variable
    `org-journal-carryover-items' docstring wider than 80 characters
org-journal.el:260:1: Warning: custom-declare-variable
    `org-journal-skip-carryover-drawers' docstring wider than 80 characters
org-journal.el:267:1: Warning: custom-declare-variable
    `org-journal-handle-old-carryover' docstring wider than 80 characters
org-journal.el:278:1: Warning: custom-declare-variable
    `org-journal-carryover-delete-empty-journal' docstring wider than 80
    characters
org-journal.el:288:1: Warning: custom-declare-variable
    `org-journal-search-results-order-by' docstring wider than 80 characters
org-journal.el:311:1: Warning: custom-declare-variable
    `org-journal-search-forward-fn' docstring wider than 80 characters
org-journal.el:400:1: Error: Wrong number of arguments: (3 . 4), 2
make: *** [Makefile:10: compile] Error 1

**Desktop (please complete the following information):**
 - Emacs Version [e.g. 25]
arch + GNU Emacs 28.0.50

**Comment by bladrome** [comment]
at line 400:
`
(define-obsolete-function-alias 'org-journal-open-next-entry 'org-journal-next-entry **22.1**)

(define-obsolete-function-alias 'org-journal-open-previous-entry 'org-journal-previous-entry **22.1**)
`

**Comment by CSRaghunandan** [comment]
I'm also running into the same issue. How did you fix this?

**Comment by bladrome** [comment]
@CSRaghunandan,  Since emacs 28.0, the **optional** args of function define-obsolete-function-alias become **ARBITRARY**, just add arg(version) at the last of the call like https://github.com/bastibe/org-journal/issues/319#issuecomment-754541016
before:
```
(define-obsolete-function-alias 'org-journal-open-next-entry 'org-journal-next-entry)
(define-obsolete-function-alias 'org-journal-open-previous-entry 'org-journal-previous-entry)
``` 
after
```
(define-obsolete-function-alias 'org-journal-open-next-entry 'org-journal-next-entry 24.0)
(define-obsolete-function-alias 'org-journal-open-previous-entry 'org-journal-previous-entry 24.0)
```

**Comment by CSRaghunandan** [comment]
I'm getting another error now:
`Invalid version syntax NA (must start with a number). This issue has already been reported.

**Comment by cslux** [comment]
Hmm?

**Comment by cslux** [comment]
> I'm also running into the same issue. How did you fix this?

Got fixed in 4a24184. Already in MELPA but not in Marmalade repo.

**Comment by CSRaghunandan** [comment]
> > I'm also running into the same issue. How did you fix this?
> 
> Got fixed in [4a24184](https://github.com/bastibe/org-journal/commit/4a241846866d1b0de383783a70fdac1023ea6495). Already in MELPA but not in Marmalade repo.

I am using straight.el for package management. But that should have pulled the latest code. Hmm. Dont know why that didn't happen.

**Comment by cslux** [comment]
> > > I'm also running into the same issue. How did you fix this?
> > 
> > 
> > Got fixed in [4a24184](https://github.com/bastibe/org-journal/commit/4a241846866d1b0de383783a70fdac1023ea6495). Already in MELPA but not in Marmalade repo.
> 
> I am using straight.el for package management. But that should have pulled the latest code. Hmm. Dont know why that didn't happen.

I haven't used straight.el so far, so can't tell how often it will pull the latests changes. But I guess it will be checked on each start of Emacs.

**Comment by CSRaghunandan** [comment]
> > > > I'm also running into the same issue. How did you fix this?
> > > 
> > > 
> > > Got fixed in [4a24184](https://github.com/bastibe/org-journal/commit/4a241846866d1b0de383783a70fdac1023ea6495). Already in MELPA but not in Marmalade repo.
> > 
> > 
> > I am using straight.el for package management. But that should have pulled the latest code. Hmm. Dont know why that didn't happen.
> 
> I haven't used straight.el so far, so can't tell how often it will pull the latests changes. But I guess it will be checked on each start of Emacs.

No, I'd have to do it manually by running `straight-check-all`. But I did run that command before runnning emacs. Don't know why it didn't pull the latest code.

**Comment by bladrome** [comment]
For https://github.com/bastibe/org-journal/issues/319#issuecomment-764537758 , bro@CSRaghunandan  , `straight-check-all` rebuild packages modified, what you want is `straight-pull-all`.

**Comment by CSRaghunandan** [comment]
> For [#319 (comment)](https://github.com/bastibe/org-journal/issues/319#issuecomment-764537758) , bro@CSRaghunandan , `straight-check-all` rebuild packages modified, what you want is `straight-pull-all`.

Yes! that's what I meant, sorry for the confusion! 
My brain mixed up both the commands when I was hurry in office.
