### ISSUE TITLE
Emacs version

### ISSUE THREAD

**Issue by rusimody** [bastibe/org-journal#32]
There was a recent question on stackexchange about an error with org-journal.
I suspect that it does not work with emacs version 23.1.
Can you confirm this?

**Comment by bastibe** [comment]
Thank you for the heads-up. Here's the link to the discussion in question: http://emacs.stackexchange.com/questions/10462/viewing-org-journal-entries/

I fixed the problem in d3ff738217b8df8b52c08a69f5759d0e55f45f20 / 1.7.2
