### ISSUE TITLE
Deeper folder structure

### ISSUE THREAD

**Issue by k0377** [bastibe/org-journal#33]
Org Journal File Format: `%Y/%m/%d.org`

When I try to save my journal entry: `No such directory`.

:crying_cat_face:

**Comment by vkazanov** [comment]
I nice idea, really, but currently it simply can't work. File name format IS a file name format, not a path structure. AFAIK, org-journal builds a list of entries using a single directory by design.

Also, search facilities basically grep within a single directory, and do not go down the directory tree recursively.

Nice try, though. :-)

**Comment by bastibe** [comment]
@vkazanov is right: This will probably break org-journal in all kinds of amusing ways. That being said, the error you are seeing *can* be fixed using this code:

```elisp
(defadvice find-file (before make-directory-maybe (filename &optional wildcards) activate)
  "Create parent directory if not exists while visiting file."
  (unless (file-exists-p filename)
    (let ((dir (file-name-directory filename)))
      (unless (file-exists-p dir)
        (make-directory dir)))))
```

**Comment by vkazanov** [comment]
@bastibe +1

@k0377, note that this should not be a problem. I use org-journal daily, for a year approx, and am yet to see any related directory structure-related problems.

**Comment by k0377** [comment]
Oh sorry, I didn't know. The reason I'm asking is, I plan to use org-journal on a daily base and I'm scared there will be many many files in this single directory soon. Also if I put in some file ref's like pictures or other documents I'll get a huge folder. Maybe it is a better way to create an extra folder like `2015-04-13` for such files if there exists at least one.

**Comment by bastibe** [comment]
I've been using org-journal for a long time, too. The only thing that gets slower is agenda searches. But with @vkazanov's search functionality, we don't need that any more.
