### ISSUE TITLE
Carrying over TODO items from daily journal files located in another folder

### ISSUE THREAD

**Issue by EvanFannin** [bastibe/org-journal#331]
I save daily journal files in separate yearly/monthly folders (e.g., ~/org/journal/2021/02), instead of a single folder. To automatically create new journal files in the correct year/month folder, I have created a function that updates the org-journal-file-format variable with the current year and month, like so:  

(defun my/get-org-journal-date-path ()
      (let ((current-year (format-time-string "%Y"))
            (current-month (format-time-string "%m")))
           (concat current-year "/" current-month "/")))

(setq org-journal-dir "~/org/journal/")
(setq org-journal-file-format (concat (my/get-org-journal-date-path) "%Y-%m-%d.org"))

TODO items seem to carryover as expected when the previous journal file is in the same folder as the new file, but not when in different folders. For example, if the previous day's journal file was from 2021/01/31 (i.e., ~/org/journal/2021/01/2021-01-31.org), the TODOs will not carry over to a journal file created on 2021/02/01 (i.e., ~/org/journal/2021/02/2021-02-01.org).

I suspect that the carryover function depends on the path in the org-journal-file-format variable. Is there a better way to automatically create daily journal files in a year/month folder structure, but still retain carryover functionality?

**Comment by cslux** [comment]
Does it work when you set `org-journal-file-format` to "%Y/%m/%Y-%m-%d.org"? If this doesn't work either, than the carryover functionality is bogus.

**Comment by EvanFannin** [comment]
Actually, yes, that does work. Thanks!

I suppose I overcomplicated it by adding the custom function instead of simply using %Y and %m in the path.
Thank you again for your reply and resolution, @cslux.

**Comment by cslux** [comment]
That happens sometimes 🙂
