### ISSUE TITLE
Advice org-journal function to add org drawer?

### ISSUE THREAD

**Issue by borgauf** [bastibe/org-journal#333]
I have a trick where I "advice" org-mode's  `org-insert-heading` to add a PROPERTIES drawer after every creation of a new heading. I was wondering if that could be done with whatever function is creating the org-journal headings for day and hour entries.

```
(defcustom add-org-graph-puhc t
  "Turn on/off auto-add of vertex/edge PROPERTIES drawer."
  :type 'boolean
  :group 'org-graph)

(defadvice org-insert-heading (after add-id-stuff activate)
  (when add-org-graph-puhc (template-puhc)))

(defun template-puhc ()
  (save-excursion
    (insert "\n:PROPERTIES:\n:TIME: "
            (format-time-string "%Y-%m-%dT%H:%M:%S")
            "\n:ID: "
            (org-id-uuid)
            "\n:EDGES:  \n:END:")
    (org-cycle-hide-drawers 'all)))
```

So when I do a C-ret or M-ret a drawer is inserted automatically right below the heading line. It would be nice, I think.

**Comment by cslux** [comment]
You could use the hooks `org-journal-after-header-create-hook` and `org-journal-after-entry-create-hook`.

**Comment by cslux** [comment]
We could or course also save the time for which we have created the new entry. This time could than be used inside the users hook functions.

**Comment by borgauf** [comment]
Where is the best place to just ask general user questions about
org-journal?

**Comment by cslux** [comment]
Good question. But https://emacs.stackexchange.com/ or https://www.reddit.com/r/emacs/ are always good places for general question regarding any package.
