### ISSUE TITLE
org-journal--format->regex: Use FIXEDCASE

### ISSUE THREAD

**Issue by stettberger** [bastibe/org-journal#340]
In some settings, when the format string is uppercase, this function makes replacements uppercase, which makes the character classes invalid:

    (org-journal--format->regex "%B") -> "\\(?4:[A-ZA-Z]\\{3,\\}\\)"

This can be fixed by setting the FIXEDCASE flag on `replace-regexp-in-string` in the [function](https://github.com/bastibe/org-journal/blob/f4b15499135d43e98244dda4606a5b97462b3f39/org-journal.el#L479)

        do (setq format (replace-regexp-in-string (car x) (cdr x) format t))

I'm currently out of time to make a pull request. Therefore, I only drop a bug report here.

**Comment by bastibe** [comment]
Does anyone feel like implementing this? Pull Requests are welcome.

**Comment by cslux** [comment]
Thanks for the report. Fixed via 919abc9. Interesting though is that the case wasn't altered for me. What Emacs version do you use, also the OS you use would interesting?

**Comment by stettberger** [comment]
> Thanks for the report. Fixed via 919abc9. Interesting though is that
> the case wasn't altered for me. What Emacs version do you use, also
> the OS you use would interesting?

I'm using debian 28.0.50 on Debian unstable. The problem occurred after
loading gnus, which seems to mess around with all kinds of variables.
The problem manifested also only in some buffers. In one buffer I could
perform (org-journal--format->regex "%B") without triggering the
problem, while it occurred in other buffers. Really misterious. Probably
there is some kind of buffer-local dynamic-variable default for
FIXEDCASE?
