### ISSUE TITLE
Creating a new day entry overrides the clipboard/latest kill-ring entry

### ISSUE THREAD

**Issue by xeruf** [bastibe/org-journal#355]
**Describe the bug**
When I create a new entry and org-journal creates a new headline for the current day, the last clipboard entry is replaced.

I have only observed this within the last few days.

**To Reproduce**
1. Copy something into the (evil?) clipboard/kill-ring
2. Create a new journal entry on a new day
3. Paste, and you get this:
:PROPERTIES:
:CREATED:  [2021-06-09]
:END:

**Expected behavior**
It doesn't touch my clipboard at all.

**Desktop (please complete the following information):**
 - OS: Arch
 - Emacs Version: 27.2

**Your Emacs Configuration**
doom emacs with `org +journal` and `evil +everywhere`
```
(setq org-journal-file-type 'weekly
      org-journal-file-format "%Y%m%d.org"
      org-journal-created-property-timestamp-format "[%Y-%m-%d]"
      org-journal-carryover-delete-empty-journal 'always
      )
```

**Comment by xeruf** [comment]
Honestly this is one of the most annoying bugs I have consistently experienced in the last weeks, could you please look into it? :)

**Comment by bastibe** [comment]
Thank you for the bug report! I believe that fixing this would merely require replacing all instances of `kill-region` with `delete-region`. Would you like to try out this change on your computer and contribute it as a pull request?
