### ISSUE TITLE
`visual-line-mode` loaded by default but not present in `org-journal-mode-hook`

### ISSUE THREAD

**Issue by quantumgc** [bastibe/org-journal#370]
`visual-line-mode` is loaded by default for any `org-journal-mode` file, but the functions `visual-line-mode` or `turn-on-visual-line-mode` are not present in the variable `org-journal-mode-hook`. Instead, `org-journal-mode` calls `turn-on-visual-line-mode` explicitly [here](https://github.com/bastibe/org-journal/blob/71e8b10088ae52c4ac17f7af87020ea85fbc6ff7/org-journal.el#L389). Looking into the blame, this seems to be behaviour that was present since the [initial import](https://github.com/bastibe/org-journal/blob/22d3912f0d4dc05a1a47f52f8c696367cf6deeec/journal.el#L78) of `org-journal` into git.

Is this behaviour intentional?

**Comment by bastibe** [comment]
Certainly not intentional. Would you like to contribute a fix in a pull request?
