### ISSUE TITLE
Calendar summary (f-w) dead-loops if empty string is searched

### ISSUE THREAD

**Issue by gudesh** [bastibe/org-journal#38]
I wanted to list all items of a week, so I naively entered "return" at the "search:" prompt.

Emacs started to eat all my computer's CPU resources and had to be killed in the end.

I wondered how it is possible to get the full list of entries for a time period
(I work around it now with a search for "**" as it begins each entry...)

**Comment by bastibe** [comment]
Thank you for the suggestion. This is a very good idea!

Should be implemented in da693a0a0718cfa5f20a3c45741f4d6699eeeb7f (published as 1.8.1)
