### ISSUE TITLE
Calendar search (f-w) brings the daily entries in *reverse* order

### ISSUE THREAD

**Issue by gudesh** [bastibe/org-journal#39]
This is annoying because the days are in the *right, chronological* order, see example:

Monday, 04.05.2015	** 16:30 :two::arrow_down:
Monday, 04.05.2015	** 10:00 
Monday, 04.05.2015	** 08:07 :one::arrow_up:
Tuesday, 05.05.2015	** 14:00 :three::arrow_down:
Tuesday, 05.05.2015	** 12:08 
Tuesday, 05.05.2015	** 09:00 
Tuesday, 05.05.2015	** 08:30 :two::arrow_up:
Wednesday, 06.05.2015	** 14:45 :four::arrow_down:
Wednesday, 06.05.2015	** 14:30 
Wednesday, 06.05.2015	** 07:39 :three::arrow_up:
Thursday, 07.05.2015	** 15:00 :five::arrow_down:
Thursday, 07.05.2015	** 14:00 
Thursday, 07.05.2015	** 11:30 
Thursday, 07.05.2015	** 10:00 
Thursday, 07.05.2015	** 08:09 :four::arrow_up:

Follow the numbers and arrows and you'll see what I mean...

It would be much nicer if each day's *first* entry would follow the previous day's *last* entry.

**Comment by bastibe** [comment]
Thank you for the heads-up!

Should be fixed in 11d4a55b9515e0d3af481ad7480e51325dff2685 (published as 1.8.1)
