### ISSUE TITLE
insert new line in org-journal-date-prefix

### ISSUE THREAD

**Issue by k0377** [bastibe/org-journal#40]
How do I insert a new line in `org-journal-date-prefix`? I tried `%n` and `~n` but one of them only works in `org-journal-date-format`. I would like to have following structure in my journal files:

```
#+TITLE: (blank for no title)
#+OPTIONS: num:nil toc:nil

* Sat, 06/06/2015
```

**Comment by bastibe** [comment]
Have you tried `\n` (or possibly `\\n`)?

**Comment by k0377** [comment]
:crying_cat_face:

**Comment by bastibe** [comment]
`(setq org-journal-date-prefix "\n\n\n* ")` works for me.

**Comment by k0377** [comment]
Okey, I set this in `custom.el` manually. Now it works and also `M-x customize` shows me the linebreaks. I guess you can't set linebreaks with `customize` then.

**Comment by bastibe** [comment]
That's sad. I rarely use customize, myself.

**Comment by k0377** [comment]
You can insert line breaks in `M-x customize` with `C-q C-j`.
