### ISSUE TITLE
[help] How can I see all the entries in `org-journal` from a single file?

### ISSUE THREAD

**Issue by avatar-lavventura** [bastibe/org-journal#402]
I am using `org-journal` to keep track of my diary. When I create a new entry using `org-journal-next-entry` I can see the entries I wrote within the day but not the older ones.

I want to see all th entries in org-journal when I  enter a new entry using `org-journal-next-entry`, is it possible? or can we store all the entries in a single file instead of distributing them into multiple.

Basically I want to carry over all the previous entries.

Example of https://github.com/bastibe/org-journal carries over only TODOs, but I was not able to change it to carry over all entries:

> ```lisp (defun my-old-carryover (old_carryover)   (save-excursion
>     (let ((matcher (cdr (org-make-tags-matcher org-journal-carryover-items))))
>       (dolist (entry (reverse old_carryover))
>         (save-restriction
>           (narrow-to-region (car entry) (cadr entry)) 
>           (goto-char (point-min))
>           (org-scan-tags '(lambda ()
>                             (org-set-tags ":carried:"))
>                          matcher org--matcher-tags-todo-only))))))
> 
> (setq org-journal-handle-old-carryover 'my-old-carryover) ```

**Comment by bastibe** [comment]
You can set `org-journal-file-type` to `yearly`. That's not quite the same as *one* file, but at least 356 times closer than `daily`. If you feel it worthwhile, you could also contribute a new `org-journal-file-type` for the entire journal in one file.

That said, I initially implemented org-journal as a way to step away from a one-file solution, as I found it cumbersome once the file got bigger. Perhaps a look at `diary` might also be warranted.

**Comment by avatar-lavventura** [comment]
@bastibe Thanks you setting  `org-journal-file-type` to `yearly`  what I was looking for. After setting `org-journal-file-type` to `yearly` ; `org-journal-new-entry` still shows only daily entries is it normal?
