### ISSUE TITLE
Ability to ask me how my day was on end of the day/week? 

### ISSUE THREAD

**Issue by ReneFroger** [bastibe/org-journal#41]
Hi bastibe! Thanks for sharing this awesome plugin!

However, there is one thing that I still miss. I loved the [Oh life](http://ohlife.com/index.php). What Oh Life was doing, is asking me via mail at the end of every week (or at the end of every day, if you want that) how my week was going. I reply it with the mail, and then on the site I see a log sorted on date where I could look up how I experiened my week on week 27 in 2014 for example. It gave me so much insight.

So I'm wondering if it's something that Emacs could ask in the input buffer, when it's the end of the week and there is no log yet?

It would be so great!

Thanks in advance for your answer.

**Comment by bastibe** [comment]
This is a great idea, and one I would like to use myself!

I'll think about how to include this in org-journal. Do you have an idea of how this could work?

In the meantime, here's a partial solution: http://blog.danielgempesaw.com/post/109767231148/using-emacs-for-daily-reminders-to-write-in-my

**Comment by ReneFroger** [comment]
Thanks for the link. It would partially solve my question. 

Maybe you could consider to [read from the minibuffer](http://www.gnu.org/software/emacs/manual/html_node/elisp/Text-from-Minibuffer.html) feature? So combining it with your link from "elisp solves problems", when there is a date or week number, the user gets a message and confirm to make a log of his daily/weekly activities, the input will be stored in your journal log. 
Then the user could read it back when opening the org journal. For precise configuration in Elisp, you could ask emacs.stackexchange.com

And I added your link to [emacs.zeef.com](https://emacs.zeef.com/). :+1:

**Comment by bastibe** [comment]
I wouldn't want to interrupt the user's current work. Capturing the minibuffer at some pre-defined time is very intrusive and will probably break the user's current work flow.

It seems that there are a couple of alternatives, though:  
https://github.com/jwiegley/alert and http://emacs-fu.blogspot.de/2009/11/showing-pop-ups.html look very promising. 

The more I think about this, the more I come to the conclusion that Emacs is just not the right place for this kind of notification. I think that this would be more useful if it worked via email. Maybe setting up an email reminder would be a more practical solution.

**Comment by ReneFroger** [comment]
Oh life did that same, with the reminders via e-mail. 
But I like to store everything in one thing, Emacs and Org-mode. It is the philiosophy of Emacs, isn't it? :smile:.

It might interrupt the user's current work, so this feature could be *opt-in*, so that the user can decide if they want to turn this feature on.

**Comment by punchagan** [comment]
You could use the appointment infrastructure. 

Something as simple as this `(appt-add "01:04" "Hey! Time to write your org-journal entry" 0)` works. You could have something like this as the default reminder function and allow users to customize it and add more complicated functions, like sending email.

**Comment by ReneFroger** [comment]
Hi Puneeth, thanks for your reply. I knew that option, nevertheless I appreciate your help in this. But I'm asking Bastibe to consider this with the asking on confirmation in the minibuffer. When the user replies with "yes", then he can type their minilog inside the minibuffer which will be stored in the org-journal.This could be opt-in, so that the user could decide if he wanted to be "interrupted" with such messages.                                                                                                                                                                                                                  Van: Puneeth Chaganti‎Verzonden: zondag 21 juni 2015 21:36Aan: bastibe/org-journalBeantwoorden: bastibe/org-journalCc: ReneFrogerOnderwerp: Re: [org-journal] Ability to ask me how my day was on end of the day/week?  (#41)You could use the appointment infrastructure. 

Something as simple as this (appt-add "01:04" "Hey! Time to write your org-journal entry" 0) works. You could have something like this as the default reminder function and allow users to customize it and add more complicated functions, like sending email.  

—Reply to this email directly or view it on GitHub.

**Comment by bastibe** [comment]
I don't think that org-journal is the right place for this. At least I can't think of a good way to do this in org-journal. But please let me know if you find a good solution for this.

**Comment by ReneFroger** [comment]
I guess I need to invent a package to do this. Thanks for replying anyway.

**Comment by bastibe** [comment]
Yes, sorry. But org-journal is not set up to do things like this.

**Comment by Aneeqasif** [comment]
> I guess I need to invent a package to do this. Thanks for replying anyway.

did you write this ?
