### ISSUE TITLE
open-current-journal-file does not respect org-extend-today-until

### ISSUE THREAD

**Issue by xeruf** [bastibe/org-journal#410]
**Describe the bug**
`org-journal-open-current-journal-file` does not respect `org-extend-today-until`, unlike `org-journal-new-entry`
Which means that for a monthly journal file, when `org-extend-today-until` is set, for the first hours of the first of the month the former will complain about a missing file, because the latter still journals to the old file.

**Expected behavior**
`org-journal-open-current-journal-file` opens the old file if the appropriate day boundary has not been crossed.

**Comment by bastibe** [comment]
This was implemented in 0bcefa5c371b2a344729c56efc012c08ff82c168. Are you using an outdated version of org-journal, or did something break?

**Comment by casch-at** [comment]
@xeruf Should have been fixed with #428.


Missed this issue 🙈
