### ISSUE TITLE
Switch from travis to github actions

### ISSUE THREAD

**Issue by casch-at** [bastibe/org-journal#426]
See e.g.:
https://github.com/tkf/emacs-request/blob/master/.github/workflows/test.yml
https://github.com/alphapapa/org-ql/blob/master/.github/workflows/test.yml
https://github.com/purcell/setup-emacs/blob/master/.github/workflows/test.yml
https://github.com/purcell/package-lint/blob/master/run-tests.sh

**Comment by bastibe** [comment]
That's probably a good idea.
