### ISSUE TITLE
Forum -- a issue open for general discussion about `org-journal`

### ISSUE THREAD

**Issue by casch-at** [bastibe/org-journal#434]

**Comment by bastibe** [comment]
How do you use org-journal?

I must confess, all I ever use is opening today's journal, navigating to the next and previous day, and searching the journal.

**Comment by casch-at** [comment]
@bastibe I`ll will answer your question on the builtin discussions  feature ❤️  Please enable it 🥺, see https://docs.github.com/en/discussions/quickstart 

Thanks

-chris

**Comment by casch-at** [comment]
@bastibe  This issue can than be closed 👍🏽
