### ISSUE TITLE
installation warnings

### ISSUE THREAD

**Issue by k0377** [bastibe/org-journal#44]
Just installed on a new machine, org journal works but got some warnings during installation from elpa:

```
In org-journal-update-auto-mode-alist:
org-journal.el:62:27:Warning: reference to free variable
    `org-journal-file-pattern'

In org-journal-read-or-display-entry:
org-journal.el:412:23:Warning: assignment to free variable `view-exit-action'
```

**Comment by bastibe** [comment]
I fixed the first issue, but I can't find a solution for the second one. Do you have any idea?

**Comment by bastibe** [comment]
There should be no more compiler warnings in 1.9.6.

Thank you for pointing these out.
