### ISSUE TITLE
New month, and all my TODOs are gone

### ISSUE THREAD

**Issue by collinarnett** [bastibe/org-journal#450]
**Describe the bug**
I think this is triggerred by the new month since I just started using org-journal last month, but suddenly I can't find any of my TODOs. I can see DONEs but all my TODOs are gone. 

**To Reproduce**
Here is my configuration.
```elisp
(use-package org-journal
  :defer t
  :init
  ;; Change default prefix key; needs to be set before loading org-journal
  (setq org-journal-prefix-key "C-c j ")
  :config
  (setq org-journal-dir "~/org/journal/"
        org-journal-date-format "%A, %d %B %Y"))
```

I normally just use `org-journal-new-entry` and `:wq` with evil keybinds. 

**Expected behavior**
TODOs carried over from the previous month to this month just as they had been carrying over 

**Desktop (please complete the following information):**
 - OS: NixOS unstable
 - Emacs Version GNU Emacs 30.0.92

**Comment by bastibe** [comment]
They must have been carried over to a new entry, and then that new entry was discarded somehow.

**Comment by collinarnett** [comment]
@bastibe If I open a new entry but don't save it eg `org-journal-new-entry` then `:q` would that discard the TODOs?

**Comment by bastibe** [comment]
Yes. It carries over TODOs to the new file. If you then delete the new file, it is gone.

**Comment by collinarnett** [comment]
Ok I understand better how this works now. Thank you for taking the time to answer this issue.
