### ISSUE TITLE
void function org-journal-get-list

### ISSUE THREAD

**Issue by ianbarton** [bastibe/org-journal#46]
I have just started to get this error on an Ubuntu Trusty machine. My Arch computers work fine. I can trigger the error by trying to schedule a date in an org file (Ctrl-S). Backtrace appended:

Debugger entered--Lisp error: (void-function org-journal-get-list)
  org-journal-get-list()
  run-hooks(calendar-initial-window-hook)
  calendar-basic-setup(nil)
  calendar()
  org-read-date(nil to-time nil nil nil nil)
  byte-code("\306>\203L	\203	;\203L\307\310	\"\203L\212\311\312!\210\212\313 \210`)\314\315\316=\203/\f\2020
\312#\203K\317\320!\321\322\323\n!\"3\n\205I\324\n!4+\203t	;\203d\321\322\325	3\3263!#\"\202s	\206s\327\314\330\314\21134&\212\214~\210\311\312!\210\314y\210n\204\206\331c\2105\3126\332!)\262\203*\333\314w\210\203\2437B\202\2457\3148\2119\203&9@8\212\315\334\3358\336\"\203\303:\202\340\3358\337\"\203\317
\202\340\3358\316\"\203\333\f\202\340\340\3418\"P\342 \312#\203\343\344!\210\332\345!\203\366\343\344!\210\2048\336=\203\212\346 \210\332\347!\203`\350\351!|\210))\332\352!\203\343\344!\2109A\2119\204\256*\202H\2046\353\354\314\"\210\202H\355\331!\210\356u\210;\203H\357\360 T!\210\205\233\335\336\"\203X<\202t\335\337\"\203d=\202t\335\316\"\203p>\202t\340\341\"\361\261\210\362	?\206\207\336=\205\207@\336=\314\211AC&l\204\231\361c\210\n)*\207" [what time ts end org-scheduled-time-regexp org-deadline-time-regexp (scheduled deadline) string-match "^[-+]+[0-9]" org-back-to-heading t outline-next-heading nil re-search-forward scheduled match-string 1 apply encode-time org-parse-time-string org-get-compact-tod org-read-date-analyze decode-time org-read-date to-time "\n" looking-at " 	" " *" eql closed deadline error "Invalid planning type: %s" line-end-position replace-match "" "--+<[^>]+>" beginning-of-line "[ 	]*$" line-beginning-position 2 "[ 	]+" throw exit insert-before-markers -1 org-indent-to-column org-outline-level " " ...] 8)
  org-add-planning-info(scheduled nil closed)
  org-schedule(nil)
  call-interactively(org-schedule nil nil)

**Comment by bastibe** [comment]
I am so sorry! I forgot to remove that hook yesterday.
The bug is fixed in 1.9.4 (available now on marmalade, and soon on melpa and melpa-stable)

**Comment by geekinthesticks** [comment]
Thanks for fixing it s quickly. I use org-journal a lot and was suffering withdrawal symptoms:)
