### ISSUE TITLE
Encryption still not working when not using default config

### ISSUE THREAD

**Issue by dingmingxin** [bastibe/org-journal#49]
Encryption still not working . Here is my configuration:

```
(setq org-journal-dir "~/wb/journal")
(setq org-journal-file-format "%Y%m%d.org") 
(setq org-journal-enable-encryption t)    
```

If I just added 

```
(setq org-journal-enable-encryption t) 
```

and do not change other settings , Encryption worked well. 
Version Info:

```
GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.0)  
Org-mode version 8.2.10 (release_8.2.10 @ /opt/local/share/emacs/24.5/lisp/org/)
Mac OSX 10.10.3  with gnupg (gpg) command installed
```

**Comment by bastibe** [comment]
What about it is not working?

**Comment by dingmingxin** [comment]
It  won`t encrypt when I changed default configuration.

**Comment by bastibe** [comment]
Does it add the `crypt` tag?

**Comment by dingmingxin** [comment]
How to add `crypt` tag ? Adding to  Headers ?

**Comment by bastibe** [comment]
Can you tell me the value of your `auto-mode-alist`? This seems to be related to another bug, where journal files are not opened in the right mode.

**Comment by bastibe** [comment]
I uploaded a new version that should fix this bug. I'm still not entirely sure what causes this behavior.

**Comment by bastibe** [comment]
Is the bug fixed now?

**Comment by bastibe** [comment]
Can't reproduce and didn't get an more feedback, so I'm closing this. If you still have this issue, please reopen.

**Comment by ZzAntares** [comment]
Hi @bastibe, I think I'm getting the exact problem in this issue, when adding `(setq org-journal-enable-encryption t)` then the journal opens up in Fundamental mode. If I remove that setting, it opens in the right mode.

**Comment by cslux** [comment]
Closing this, as org-journal has been improved in many ways.

**Comment by bastibe** [comment]
Please reopen if you still experience this issue!
