### ISSUE TITLE
new journal entry buffer ignores .dir-locals.el

### ISSUE THREAD

**Issue by wilx** [bastibe/org-journal#51]
I am using `org-journal-mode`. I have created `.dir-locals.el` in my `~/Documents/journal` directory and it gets correctly applied if I open a file the usual way. However, if I hit the <kbd>C-x</kbd><kbd>C-j</kbd> to add a new entry and the entry is in a new day, the opened buffer does not have the modifications I apply through `.dir-locals.el`.

Can I make it recognize and process `.dir-locals.el` for new day journal entry buffers?

My `.dir-locals.el`:

    ((nil
      (fill-column . 79)
      (indent-tabs-mode)
      (show-trailing-whitespace . t)
      (whitespace-style face trailing lines-tail space-before-tab indentation empty)
      (whitespace-newline . t))
     (org-journal-mode
      (typo-language . "Czech")
      (typo-mode . t)
      (ispell-local-dictionary . "czech")
      (flyspell-mode . t)
      (whitespace-action warn-read-only auto-cleanup)))

(cf. <http://emacs.stackexchange.com/questions/14247/org-journal-mode-new-entry-ignores-dir-locals-el>)

**Comment by bastibe** [comment]
What are the modifications you would expect to see?

The problem is probably, that org-journal-mode simply "types" a few fixed strings into the journal file. Org-mode, or any other customization really doesn't have much say in this process. In other words, your settings *should* be active, but they probably won't affect org-journal much.

**Comment by wilx** [comment]
@bastibe : Well, I want the `typo-mode` active with the appropriate language and also spell checking with the same language active. That works if I just <kbd>C-x</kbd><kbd>C-f</kbd> open the file but it does not work when I just create new entry.

Sorry, if this is not the right forum for this issue. I am not sure where else to take it.

**Comment by bastibe** [comment]
Please tell me what you expect to be seeing and what you are seeing. I still don't know what your problem is.

**Comment by wilx** [comment]
Please see this screencast: https://www.youtube.com/watch?v=ExGhwoQVqOg

**Comment by bastibe** [comment]
In your screencast, the syntax of `.dir-locals` seems to be wrong (as per [the manual](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html)).

In the screencast, you use

    ...
      (org-journal-mode
        (typo-mode . t)
        ...
        (flyspell-mode . t))
      ...

But according to the manual, the syntax should be

    ...
      (org-journal-mode .
        ((typo-mode . t)
        ...
         (flyspell-mode . t)))
      ...

**Comment by bastibe** [comment]
Did this fix your issue?

**Comment by wilx** [comment]
You were right. Sorry, I forgot about this. I am closing this.
