### ISSUE TITLE
Can't use org-agenda before opening a journal file

### ISSUE THREAD

**Issue by Titan-C** [bastibe/org-journal#53]
I followed the instructions to add all those calendar/journal files to org-agenda. But for some reason I need to have previously have opened one. If I call org-agenda as soon as I start emacs I get the message
```org-agenda-get-day-entries: Agenda file /home/oscar/Dropbox/org/journal/20150819 is not in `org-mode'```

**Comment by bastibe** [comment]
Yes, `org-journal` is autoloaded only once it is interacted with. You could try `(add-hook 'org-mode-hook (lambda () (require 'org-journal)))` in your `init.el` and see if that fixes it.

**Comment by bastibe** [comment]
Did this fix your problem?

**Comment by Titan-C** [comment]
It didn't help or I didn't do it right at that time. But nowadays I have moved into a much more simplified workflow. I just use an org-mode capture template and put it all my journal notes in one same org file. So I have stopped using the features of this project, as my simple way is fine for now.
Thank you for your concern.
