### ISSUE TITLE
append .txt 

### ISSUE THREAD

**Issue by x61** [bastibe/org-journal#54]
Is it possible to append a .txt file format at the end of each journal file? How do one go about doing that?

**Comment by bastibe** [comment]
As noted in https://github.com/bastibe/org-journal/issues/9#issuecomment-139229180, `(setq org-journal-file-format "%Y%m%d.txt")` should do the trick.

**Comment by x61** [comment]
It should open. But I am having a different issue. When I install org-journal through the emacs package repository everything works fine. But when I download the org-journal file from github and try to run it from there, I get the following error: "Symbol's value as variable is void: org-journal-file-format". This error occurs without making any changes to the org-journal file. Any suggestions?

**Comment by bastibe** [comment]
That's because you are missing org-journal's autoloads. You can generate the autoloads using `M-x update-file-autoloads`. The melpa-stable/marmalade versions of org-journal are always up-to-date, though, so I would recommend to install it from there.

**Comment by x61** [comment]
Thank you. When I installed from melpa and changed the directory to the journal files to a location I want the files to be, it still asks me to save files in the default folder. It seems to not work when I changed the keybinding from C-c C-j to C-c j. It seems the changes I make to the file don't take effect. This is for melpa installation.

**Comment by bastibe** [comment]
Can you show me your `org-journal-*` customizations?

**Comment by x61** [comment]
Got it working. Thanks for the help.

**Comment by bastibe** [comment]
I fixed your startup issue in 1b866dbc3e95543a34d9c7915f9617c027d116c3. The file should now load correctly even if no autoloads are present.

**Comment by x61** [comment]
Great. This solves it.
