### ISSUE TITLE
Starting emacs with a journal.

### ISSUE THREAD

**Issue by Nsheppard01** [bastibe/org-journal#56]
Right now when I use C-c C-j the journal opens up in a new split window. The ability to get a journal entry with one keystroke is convenient, but I don't really need a new window, and honestly it would be even more convenient if emacs opened straight into a journal instead of displaying the scratch buffer.

Is this feature supported, and if not, how would I go about adding it?

**Comment by bastibe** [comment]
There is a customization option `org-journal-find-file` that you can change for this. Use `M-x customize` to change it.

**Comment by Nsheppard01** [comment]
What about getting org-journal to open automatically when Emacs starts?

**Comment by vkazanov** [comment]
@Nsheppard01 This is something you should do in your .emacs. For example, you can add (org-journal-new-entry) in the end of the file.

**Comment by Nsheppard01** [comment]
That gives me the following

Warning (initialization): An error occurred while loading `/home/yuki/.emacs':

Wrong number of arguments: #[(prefix &optional time) \306 \210\307!
?	!\210\310 \210db\210\311 d\312\232\203'\313"\261\210\203?eb\210\314 \235\204<\315!\210db\210\203ei\316=\204L\317c\210\317\320\321 !\320!U\203a\313!\202b\322\261\210\323 \210\203u\324\325 !\210\202x\326 \210\204\327 \210\330
!+\207 [time entry-path prefix should-add-entry-p org-journal-find-file unsaved org-journal-dir-check-or-create org-journal-get-entry-path org-journal-decrypt buffer-modified-p 1 format-time-string org-get-tags org-set-tags-to 0 
 time-to-days current-time  org-journal-mode hide-sublevels org-journal-time-entry-level show-all show-entry set-buffer-modified-p org-journal-date-prefix org-journal-date-format org-journal-enable-encryption org-crypt-tag-matcher org-journal-time-prefix org-journal-time-format org-journal-hide-entries-p] 5 (/home/yuki/.emacs.d/elpa/org-journal-1.10.2/org-journal.elc . 8718) P], 0

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.

**Comment by vkazanov** [comment]
@Nsheppard01 Oh, sorry, I should have given a precise answer.

By doing `C-h f org-journal-new-entry` you can see that the function has the following signature:

(org-journal-new-entry PREFIX &optional TIME)

Here you can see a single required argument, `PREFIX` and a single optional one, `TIME`. When functions are called interactively (as a keybinding, or a `M-x` command) the prefix is supplied automatically. But you wanted to call it from a file, so you do need an argument:

(org-journal-new-entry nil)

Change `nil` to `t` if you just want to open a file, without starting a new journal entry.

**Comment by Nsheppard01** [comment]
Sweet that works!

On Wed, Dec 16, 2015 at 12:44 AM, Vladimir Kazanov <notifications@github.com
