### ISSUE TITLE
New entry from an org-mode buffer

### ISSUE THREAD

**Issue by arsaber101** [bastibe/org-journal#58]
I can't enter a new entry from a org-mode buffer, as in org-mode `C-c-C-j` is bind to `org-goto`. Defining `(global-set-key (kbd "C-c-C-j") 'org-journal-new-entry)` in my `.emacs` file does not work.
(I might missing something as I am an emacs newbie...)

**Comment by bastibe** [comment]
There is a typo in your command. There should be no hyphen between `C-c` and `C-j`. Does this solve your issue?

**Comment by arsaber101** [comment]
Sorry, typo was in my post...
But I found that  typing _twice_ `C-c C-j` open first `org-goto` buffer, then a new entry.
