### ISSUE TITLE
Option to make TODOs carry over from the previous day?

### ISSUE THREAD

**Issue by Nsheppard01** [bastibe/org-journal#60]
I know org mode has a global todo list, but that's kind of messy*. Is there a way to get new journal entries to carry over TODOs from the previous day? IE, when a new journal entry is created, it checks the last journal entry, and copies any headers marked TODO. Because it only checks the previous day, marking the entry as done or removing it on the current day would prevent it from being carried over.

*I'm having trouble with the (\\`[^.].*\\.org'\\|[0-9]+) regex example mentioned on the wiki. It keeps finding my autosaves and thus listing every TODO entry twice.

**Comment by bastibe** [comment]
There is no automated way to do that at the moment. If you are comfortable with writing some elisp, you could implement it as an advice for `org-journal-new-entry`. If you find this useful, I could add a hook that runs after a new file has been created.

On the other hand, it is easy to search for TODOs in a date range. You can search the current week, month, or year for `TODO` to find all the TODO headlines.

As for the regex, you can exclude temp files by excluding files starting with `~` from the regex like so: `\\`[^~.].*\\.org'\\|[0-9]+`

**Comment by Nsheppard01** [comment]
Ugh, now it's not finding anything for some reason. Regular expressions are such a pain.

**Comment by bastibe** [comment]
Oh, my bad. I confused autosave files with backup files. I guess ``\\`[^#~.].*\\.org'\\|[0-9]+`` should work for both backup and autosave files. Personally, I `(setq auto-save-default nil)` and `(setq backup-directory-alist '(("." . "~/.emacs.d/backups/")))`, so there are neither backup nor autosave files in the current directory.

**Comment by Nsheppard01** [comment]
The problem is this is filtering everything and my global todo list is
showing up blank now.

I think using the original setting and then just moving my autosaves and
backups is a better choice though.
