### ISSUE TITLE
If the directory org-journal-dir does not exist (is not mounted), I'm no longer able to use the calendar.

### ISSUE THREAD

**Issue by Cornel-Craveta** [bastibe/org-journal#62]
The reason for this is that `org-journal` calls

`(add-hook 'calendar-today-visible-hook 'org-journal-mark-entries)`
`(add-hook 'calendar-today-invisible-hook 'org-journal-mark-entries)`

when it is loaded.

Then `org-journal-mark-entries` calls (indirectly) `org-journal-dir-check-or-create`, which asks me if I want to create the directory. Since I don't want (it's loaded when I need it only), then the whole call to calendar fails.

My workaround is to have my own function which calls

`(remove-hook 'calendar-today-visible-hook 'org-journal-mark-entries)`
`(remove-hook 'calendar-today-invisible-hook 'org-journal-mark-entries)`

when I don't have the `org-journal-dir` loaded, but it would be nice if org-journal would not overwrite my preferences regarding the calendar hooks.

**Comment by bastibe** [comment]
Org-journal's behavior is very much by design. If the journal directory does not exist, org-journal will ask to create it. For most people, this is the right behavior. (Why don't you want to keep your journal directory mounted?)

To make this problem go away in your case, I would advise you to re-define `org-journal-dir-check-or-create` to the following:

```elisp
(defun org-journal-dir-check-or-create ()
  "Check existence of `org-journal-dir'. If it doesn't exist, fail with an error."
  (unless (file-exists-p org-journal-dir)
    (error "Journal directory is necessary to use org-journal."))
  t)
```

This will raise an error any time `org-journal-dir-check-or-create` is called and your journal directory is not present. The error is necessary to prevent the code that calls `org-journal-dir-check-or-create` from continuing.

I hope this solved your problem.

**Comment by Cornel-Craveta** [comment]
> Why don't you want to keep your journal directory mounted?

Because sometimes I'm in an environment where I don't want to mount that directory that is supposed to contain items of a sensitive nature to me.

> I hope this solved your problem.

Unfortunately it does not. It's true that I'm no longer being asked to create that directory, but still get the error "Journal directory is necessary to use org-journal." The thing is, in that moment I want to use the calendar, not the org-journal, so this error comes out of blue sky and I had to debug to see where it comes from. What I want, I guess, is that org-journal ignores silently that I don't have that directory and let me proceed with my calendar, even if it is not marking the days for which I may have entries in the journal.

Maybe the add-hook should not be called automatically at load, but later, explicitely, or better, maybe there could be a customizable opt-out variable which would prevent calling the add-hook?

**Comment by bastibe** [comment]
I'm sorry but you will have to solve this problem on your end. I don't see an way of reconciling 

- asking the user to create the directory when it's not there (a useful default)
- silently ignoring the directory when it's not there.

If anyone else needs this feature, I'll look into it some more.

That said, if you find a solution that does not disturb the default work flow, I'd be happy to merge it.
