### ISSUE TITLE
just stopped working on emacs 25.2

### ISSUE THREAD

**Issue by paynito** [bastibe/org-journal#66]
I can no longer make new journal entries

`Debugger entered--Lisp error: (void-function org-journal-new-entry)
  (org-journal-new-entry)
    debugger-may-continue = t
    inhibit-redisplay = nil
    inhibit-debugger = t
    inhibit-changing-match-data = nil
  eval((org-journal-new-entry) nil)
    [no locals]
  eval-expression((org-journal-new-entry))
    debug-on-error = t
`

I get these warnings if I byte-compile the .el 
`Compiling file /Users/AbuDavid/personal/dotFiles/privatEmacsLayrs/org-journal/org-journal.el at Sun Oct  2 01:59:57 2016

In org-journal-new-entry:
org-journal.el:286:12:Warning: ‘hide-sublevels’ is an obsolete function (as of
    25.1); use ‘outline-hide-sublevels’ instead.
org-journal.el:287:10:Warning: ‘show-all’ is an obsolete function (as of
    25.1); use ‘outline-show-all’ instead.
org-journal.el:291:10:Warning: ‘show-entry’ is an obsolete function (as of
    25.1); use ‘outline-show-entry’ instead.

In org-journal-search-follow-link-action:
org-journal.el:706:6:Warning: ‘show-all’ is an obsolete function (as of 25.1);
    use ‘outline-show-all’ instead.
`

**Comment by paynito** [comment]
Huh, this is the second private layer I have to explicitly load. .  . works now
`(defun dotspacemacs/user-config ()
  ;; load private 
  (load "/Users/A/.emacs.d/private/org-journal/org-journal.el")
  (load "~/.emacs.d/private/my-mu4e-setup/packages.el")`

**Comment by bastibe** [comment]
Please close the issue if it is fixed.
