### ISSUE TITLE
Emacs 25.1 issue

### ISSUE THREAD

**Issue by svsmailus** [bastibe/org-journal#67]
Getting the following in my compile-log:

`Leaving directory ‘~/’`

`Compiling file /Users/Simon/.emacs.d/elpa/org-journal-20160907.621/org-journal.el at Sun Oct 16 13:31:28 2016`
`Entering directory ‘/Users/Simon/.emacs.d/elpa/org-journal-20160907.621/’`

`Compiling no file at Sun Oct 16 13:31:29 2016`
`Warning (bytecomp): ‘hide-sublevels’ is an obsolete function (as of 25.1); use ‘outline-hide-sublevels’ instead.`
`Warning (bytecomp): ‘show-all’ is an obsolete function (as of 25.1); use ‘outline-show-all’ instead.`
`Warning (bytecomp): ‘show-entry’ is an obsolete function (as of 25.1); use ‘outline-show-entry’ instead.`
`Warning (bytecomp): ‘show-all’ is an obsolete function (as of 25.1); use ‘outline-show-all’ instead.
`

**Comment by bastibe** [comment]
Do you know when the new function names became originally available? I don't want to exclude recent versions of Emacs by changing the names prematurely.

**Comment by bastibe** [comment]
I changed it in eba1dd9e05aa5c18845c5411b7550f684ad0b824. I haven't uploaded the changes to Melpa or Marmalade yet, because I am not sure how much breakage this is going to entail.

**Comment by franburstall** [comment]
This breaks things in 24.4.1 which still has show-all and hide-sublevels.

**Comment by bastibe** [comment]
I don't think I can keep compatibility with Emacs 24, and silence the deprecation warning at the same time. Do you know any solution to this?

I suppose I could write a macro that selects the appropriate function at compile time, but that seems overkill just to silence a deprecation warning.

**Comment by bastibe** [comment]
I reverted the changes in d0868e1. You Emacs should now work again.

**Comment by franburstall** [comment]
Many thanks!

---Fran
