### ISSUE TITLE
What would be necessary to work with more than one journal?

### ISSUE THREAD

**Issue by quigonjeff** [bastibe/org-journal#69]
Hi. I appreciate `org-journal` and have been using it on a regular bases for about 6 months now. Very good package. I would like to have separate journals, one for my personal stuff and another for work stuff. What would be necessary to make it happen?

**Comment by bastibe** [comment]
I guess you could change `org-journal-dir` depending on your current context. That *should* be sufficient, although you might need to refresh the calendar.

**Comment by bastibe** [comment]
Please reopen if your issue has not been resolved.
