### ISSUE TITLE
Reorganise README

### ISSUE THREAD

**Issue by vkazanov** [bastibe/org-journal#70]
I've been using org-journal for quite a long time now. Recently I realised that it has a fancy new feature I really missed ("carry over", to be precise) mostly because current README is a bit messy.

How about cleaning things up a bit? I can do it myself in a PR if @bastibe agrees here with me.

**Comment by bastibe** [comment]
I would be grateful!

For reference, what things would you like to change?

Also, I grew to really love the carry over feature as well. It should definitely be featured more prominently in the README.

**Comment by vkazanov** [comment]
Oh, BTW, do you use the search feature? At some point I realised I use it as a way to build reports on things done, not done etc, but it's a bit lacking here. 

So, I started wondering if some kind of a reporting framework might be interesting, similar to the org-mode agenda, but concentrating on the journal side of things.

**Comment by vkazanov** [comment]
Great, let's see what I can do here! I'll come up with a PR within a few days.

**Comment by vkazanov** [comment]
One more thing. How about choosing a license..? :-)

**Comment by bastibe** [comment]
Silly me, I have indeed forgotten to chose a license. Thank you for pointing that out. 

If I remember correctly, this goes back to JournalMode not having a license except for 
> Feel free to use, modify and improve the code! - mtvoid

Keeping with the spirit of this line, I added a BSD 3-clause license file in 008ef45.
