### ISSUE TITLE
Export / publishing options

### ISSUE THREAD

**Issue by thari** [bastibe/org-journal#73]
Is there any way I can create a pdf or html of all the entries ?
I am using this for keeping track of my meeting, it is very useful, but at some point, I have to 
export it.

**Comment by bastibe** [comment]
You can export the individual files or subtrees thereof as you would any org-mode file. Hit M-x `org-export-dispatch` to get started.

**Comment by thari** [comment]
This will create a pdf for each day, is there any way I can get a single pdf with all the entries?

**Comment by bastibe** [comment]
There is no code in org-journal to automate this task. 
However, you can easily append all daily journal files to one big org-mode file and export that.
