### ISSUE TITLE
org-makes-tags-matcher  expects todo-only to be scoped int (frustration)

### ISSUE THREAD

**Issue by MBuchaus** [bastibe/org-journal#76]
Using this package with the latest spacemacs and using the private layer to glue it together.  I yet keep getting this error:

org-makes-tags-matcher expects todo-only to be scoped in

I'm not having luck finding an answer to this one.

**Comment by bastibe** [comment]
When exactly are you getting this error? What is the exact spelling of the error? Google doesn't seem to know about `org-makes-tags-matcher` at all.

**Comment by vkazanov** [comment]
I think he means `org-make-tags-matcher`

**Comment by bastibe** [comment]
Thank you for that hint! 

I think this is either
- something to do with carryover, although that doesn't typically touch tags at all, or
- something with org-crypt.

To triage this, could you (@MBuchaus) check if you are using `org-journal-enable-encryption`?

**Comment by MBuchaus** [comment]
crap your right   org-make-tags-matcher

**Comment by MBuchaus** [comment]
I believe the entire issue is with Spacemacs and it using the contrib version of org,  and it's conflict with the built in version  (depending on how the config is setup)   I made sure all org config was wrapped in  (with-eval-after-load 'org  as outlined  http://spacemacs.org/layers/+emacs/org/README.html  and we're in business  all issues solved..
