### ISSUE TITLE
org-agenda-files matching lock files

### ISSUE THREAD

**Issue by dmgm** [bastibe/org-journal#77]
I had a problem with emacs lockfiles in the org-journal and org-directory being matched, but not being recognised as org files. This would then prevent org-agenda from generating a todo list (c-c a t)

My solution,    (setq org-agenda-file-regexp "\\`[^.].*\\.org$\\|[0-9]+$\\'")

If this works for you, perhaps update the readme.md file to show this. the $ avoids matching anything that includes a # after the end of the file.

**Comment by bastibe** [comment]
Thank you for your bug report. I thought that this behavior was already implemented by the `\\'` at the end of the expression. From the documentation of [`\'`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Backslash.html) and [`$`](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Special.html) I can't figure out the difference between the two operators.

At any rate, I believe that only one of them should be necessary. Could you check which one of the two operators works (and possibly explain, why?).

**Comment by dmgm** [comment]
I'm not expert on [regexp](http://www.gnu.org/software/emacs/manual/html_node/emacs/Regexps.html) but I read in the preceding link that \ indicated a literal match or a special construct. $ is the end of line.
In the regex above I think the \ is simply applying to the '.

Because regexp appears to me such a black art I use the emacs (re-builder) to test, and that is how I produced the string above. 

What I can say is that the regex you had matches #20170101# which is an emacs lock file and therefore undesirable to match as an org file. Adding the $ for end of line limits the match to numbers to the lines end, which seems to me the right result, and solves the problem.

**Comment by bastibe** [comment]
I think I understand it now:

     \`

and

    \'

match beginning and end of *buffer* ([documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Backslash.html)), wereas 

     ^

and

    $

match beginning and end of *line* ([documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Regexp-Special.html)).

For strings, they should be equivalent.

In practice however, only the latter versions seem to work for you. Then again, the default `org-agenda-file-regexp` uses the former variants:

    \`[^.].*\.org\'

In light of this, I believe that the correct regexp is

    \`[^.].*\.org\'\|\`[0-9]+\'

Or in string-form

    "\\`[^.].*\\.org\\'\\|\\`[0-9]+\\'"

Can you check that this actually works?

**Comment by dmgm** [comment]
What's i've subsequently found is that the default \`[^.].*\.org\' is all that's actually required.
I think you explained this in a previous bug report. You said this variable was no longer required.

However I customized the org-agenda-file-regexp variable and \`[^.].*\.org\'\|\`[0-9]+\'  does work.
By work I mean that todos from my journal files appear in the, c-c a t, agenda listing.

**Comment by bastibe** [comment]
I updated the README accordingly in 4876bbc7cd3129f6285f41b9076c178d30720163.

Thank you for investigating this!
