### ISSUE TITLE
C-c C-s clashes with the org scheduling

### ISSUE THREAD

**Issue by spraharsh** [bastibe/org-journal#79]
Hello,
I have been using org journal for some time and I've begun to use TODOs quite a bit within the journal. However scheduling any TODO is a pain considering that the keybinding for search for the journal mode clashes with the org-mode keybinding for leaving a scheduling timestamp

**Comment by bastibe** [comment]
There are only so many key bindings available to a major mode. Major modes are supposed to use key bindings like `C-c C-�`, where � can be any letter. Most of these bindings are already taken by org-mode. There just isn't a good solution to this.

However, this is Emacs, and everything can be changed. If you don't like the default key bindings, change them!

Also, if you can think of a better key binding that does not conflict with org-mode, I'd be very interested.

**Comment by spraharsh** [comment]
I've actually done that, but I thought I'd mention it considering scheduling a to-do ( at least for me) seemed like the first thing I'd do after creating a to-do. Maybe it's just me! 
How about keybindings like C-c C-x C-k or C-c C-x C-j?. Org mode uses C-c C-x C-i for clocking for example(which I also use regularly). 
Then again there might be personal bias here, I've always schedule my to-dos but never really needed the search function. I'm not sure how that extends to people.

**Comment by bastibe** [comment]
Interesting! Personally, I never schedule my to-dos. 

At the very least, I could add a note in the README that the key binding overwrites one of org-mode's key bindings and how to restore the org-mode default binding.

Do you know if org-journal conflicts with another key binding?

**Comment by spraharsh** [comment]
Regarding conflicts, nothing that stood out like this. I know for example that C-c C-j does, but I never really used that in org-mode

I guess that would be nice!

**Comment by bastibe** [comment]
OK, I amended the README. Turns out, every single key binding in org-journal overwrites a key binding in org-mode.

Thank you for bringing this up.
