### ISSUE TITLE
Feature: go to last yeat this day

### ISSUE THREAD

**Issue by psamim** [bastibe/org-journal#81]
Hi,
It would be great to have function to go to last year this day's entry.
Thanks

**Comment by bastibe** [comment]
Interesting idea! Would you be interested in trying to solve it?

**Comment by CeleritasCelery** [comment]
@howardabrams wrote a function to do this in his `org-journal` [config](https://github.com/howardabrams/dot-files/blob/master/emacs-org.org)
```elisp 
(defun journal-last-year-file ()
  "Returns the string corresponding to the journal entry that
happened 'last year' at this same time (meaning on the same day
of the week)."
(let* ((last-year-seconds (- (float-time) (* 365 24 60 60)))
       (last-year (seconds-to-time last-year-seconds))
       (last-year-dow (nth 6 (decode-time last-year)))
       (this-year-dow (nth 6 (decode-time)))
       (difference (if (> this-year-dow last-year-dow)
                       (- this-year-dow last-year-dow)
                     (- last-year-dow this-year-dow)))
       (target-date-seconds (+ last-year-seconds (* difference 24 60 60)))
       (target-date (seconds-to-time target-date-seconds)))
  (format-time-string "%Y%m%d" target-date)))

(defun journal-last-year ()
  "Loads last year's journal entry, which is not necessary the
same day of the month, but will be the same day of the week."
  (interactive)
  (let ((journal-file (concat org-journal-dir (journal-last-year-file))))
    (find-file journal-file)))

  (global-set-key (kbd "C-c f L") 'journal-last-year)
```

**Comment by cslux** [comment]
@bastibe Do you want this to be merged in?

**Comment by howardabrams** [comment]
Didn't realize that any one else would find this interesting. ;-)

I could make a PR if you'd like.

**Comment by cslux** [comment]
In my opinion this is not really useful for general use and shouldn't be merged in, but if @bastibe want's it to be merged, than yes. If not, this issue should be closed.

**Comment by cslux** [comment]
@bastibe Should we create a, section in the readme with org-journal snippets.

**Comment by howardabrams** [comment]
Yeah, perhaps having the code there in this issue is sufficient for
interested parties.

**Comment by bastibe** [comment]
Yes, a README section with code snippets like this would be cool!
