### ISSUE TITLE
Lost journal entries on move + kill buffer

### ISSUE THREAD

**Issue by igoralmeida** [bastibe/org-journal#83]
Hi,

I'm using org-journal on spacemacs and wanted to share a cautionary tale :)
I just happened to lose a few TODO entries that had been moved from the previous day after killing the new buffer. Unfortunately I assumed I was just throwing away a new entry that I didn't care about anyway.

Maybe org-journal could save me from myself, next time? Perhaps this could be done by saving the buffer to today's file (or some other backup place) immediately if it had to move TODO entries...

**Comment by bastibe** [comment]
Good point, and I am very sorry that you lost data! This actually happened to me a few times, too, but never lead to data loss, since I always had some form of backup.

This happens mostly because org-journal preserves the buffer-modified flag even if it adds a new entry. I don't know why I built it that way, but I removed this functionality in the latest commit.

Now, creating a new entry (or moving TODOs) should mark the buffer as modified, and Emacs should prompt you to save it if you close it without saving.

Can you verify that this solves your problem?

**Comment by igoralmeida** [comment]
I did get a notification that the buffer was modified, but I killed it anyway. In my case I'd pr

**Comment by bastibe** [comment]
I am not sure this is something I am comfortable doing. If the user saved his journal a while ago, then edited something, then created a new journal entry, s/he would expect the file to still be unsaved. I don't want to mess with these basic Emacs concepts.

*However*, you can actually fix this particular problem yourself by `(add-hook 'org-journal-after-entry-create-hook save-buffer)`. This should call `save-buffer`, whenever a new journal entry is created.

**Comment by igoralmeida** [comment]
I agree that "save on new entry" is backwards, and I don't think that's what I really need. Rather, my (unusual) use-case seems to require a "save on new file" hook. Is such a thing available? I wouldn't mind adding this to my config file somewhere.

**Comment by igoralmeida** [comment]
I took a quick look at `org-journal-new-entry` and was thinking whether the hook function for `org-journal-after-entry-create-hook` can do it?
My elisp is still on copy-paste-modify level and I don't quite understand how everything works, so here's a handwavy plan that may or may not make sense:

A bit before `(run-hooks 'org-journal-after-entry-create-hook)` you check whether you should call `org-journal-carryover`. If it were possible to externally use that same predicate (?), `(when (and new-file-p org-journal-carryover-items) ...)`, I could conditionally save the buffer.

**Comment by bastibe** [comment]
Since org-journal is dynamically scoped, I believe that `new-file-p` is visible from within the hook. So you should be able to do something like `(add-hook 'org-journal-after-entry-create-hook (lambda () (when new-file-p (save-buffer))))`. (I haven't tested this, though)

**Comment by igoralmeida** [comment]
Ok, so I reproduced the issue today, being careful to make a backup of yesterday's file this time to try it multiple times. I do *not* get the save-before-quit notification (I must have only gotten it the first time due to having created an entry that I later didn't care about), so the fix from your first comment is definitely important (I haven't tested it though).

I also added the hook with the conditional save and it does work fine, so thanks for that as well.

**Comment by bastibe** [comment]
I would be grateful if you could test for the save-before-quit notification, as that seems to be a useful feature ;-)

**Comment by igoralmeida** [comment]
I would be happy to, just have to figure out how to tell spacemacs to look for org-journal somewhere else. My first attempt changing packages.el was unsuccessful, though.

Will try later today, possibly.

**Comment by igoralmeida** [comment]
Tried it, works fine: new entries (regardless of new file or not) change the buffer modified flag.

**Comment by bastibe** [comment]
Cool, thank you!
