### ISSUE TITLE
readme wiki old link doesn't work

### ISSUE THREAD

**Issue by jefferysac** [bastibe/org-journal#85]
org-journal

Adapted from http://www.emacswiki.org/PersonalDiary

 http://www.emacswiki.org/PersonalDiary isn't working anymore 

now link is https://www.emacswiki.org/emacs/PersonalDiary

**Comment by jefferysac** [comment]
and if possible please add wiki of org-journal package in the readme description .
https://www.emacswiki.org/emacs/OrgJournal

**Comment by bastibe** [comment]
Thank you for the notice. I will update both the README and the Wiki entry in the next few days.

**Comment by bastibe** [comment]
Done. I don't want to add the Wiki to the README, since the Wiki is only an outdated copy of the README.
