### ISSUE TITLE
Autoloading variables overwrite user custom data

### ISSUE THREAD

**Issue by rnkn** [bastibe/org-journal#87]
The following variables are autoloaded, which makes them act as hardcoded values that overwrite user custom data:

https://github.com/bastibe/org-journal/blob/06402de02461338503bf034ceca44c3a5a898778/org-journal.el#L112-L113
https://github.com/bastibe/org-journal/blob/06402de02461338503bf034ceca44c3a5a898778/org-journal.el#L122-L123

You may not have caught this in the past because I think it only happens when `(package-initialize)` is run after `(load custom-file)`.

Removing the autoload cookie comments and running `update-directory-autoloads` fixes the issue, but this is likely a roadblock for many users.

**Comment by CeleritasCelery** [comment]
I am unable to reproduce your problem. If I set these variables they don't get overridden. `defcustom` will only apply its value if the variable is unset. Therefore it should not override user data. But I do agree that these autoload cookies should be removed because you can't autoload variables, so they are useless.

**Comment by rnkn** [comment]
Yeah, I assume like me you don’t regularly generate autoload files for your own packages. You can test this out by running `update-directory-autoloads` in your repo directory, then checking the autoload `.el` file. You should see:
~~~elisp
(defvar org-journal-dir "~/Documents/journal/" "\
Directory containing journal entries.
~~~
and
~~~elisp
(defvar org-journal-file-format "%Y%m%d" "\
Format string for journal file names, by default \"YYYYMMDD\".
~~~
I think what’s happening is that, contrary to what Stefan said back in 2007, I think nowadays you can *preemptively* set a variable value before the variable is defined, as long as that variable is defined with `defcustom`, which is of course true for org-journal, except that the autoload file actually defines with `defvar`, thus creating a “hardcoded” type situation.

**Comment by bastibe** [comment]
I am confused. What is the right course of action here?

**Comment by rnkn** [comment]
Only to remove the autoload cookies on lines 112 and 122.

**Comment by bastibe** [comment]
Thank you all for bringing this up!
