### ISSUE TITLE
journal format

### ISSUE THREAD

**Issue by x61** [bastibe/org-journal#9]
Following samspo suggestions in issue #2, I added

(setq org-journal-file-format "%Y%m%d.txt")
(setq org-journal-file-pattern "201[0-9][0-9][0-9][0-9][0-9].txt")

to my .emacs but encounters problems when calendar is called. First, it won't allow you to visit future dates when "]" is pressed. The error message is " There was no year zero". Secondly, when I set journal directory to a folder in my dropbox, only "Fundamental mode" is used and not the "org-mode", however, if I use the default directory (~/Documents/journal/), org-mode as a major mode is used. Interestingly, if I change the directory options directly within the org-journal.el file to point to where I would like it to be in dropbox, org-major mode is used.

Thirdly, is it possible to activate the calendar the moment "C-c j" is pressed? Lastly, when in calendar mode, and you have the cursor anywhere (not on any date) and you try to navigate the journal list with "[" or "]", you'll get an error message "Wrong type argument: number, nil"

**Comment by x61** [comment]
Revisiting my original question. Is it possible to append .txt at the end of each journal files?

**Comment by bastibe** [comment]
Yes, `(setq org-journal-file-format "%Y%m%d.txt")` should do the trick.

**Comment by thinkhuman** [comment]
I'm still an org mode newbie, and am trying to install this package via `use-package`, like so:

```
(use-package org-journal
  :init
    (setq org-journal-dir "~/Dropbox/Writing/Journal/"
    setq org-journal-file-format "%m-%d-%Y.org"))
```

This always results in an error of:
```
Error (use-package): org-journal/:init: Wrong number of arguments: setq, 5
Error (use-package): Cannot load org-journal
```
