### ISSUE TITLE
org-journal TODOs in org-agenda-list for today

### ISSUE THREAD

**Issue by bon** [bastibe/org-journal#90]
I've started using org-journal and find it very useful. I keep a running bunch of TODOs in it that carry over from day to day. They also show up in org-todo-list thanks to the tips in the README. But I would also like them to show up in the org-agenda-list for the current day. Any tips on that?

**Comment by bastibe** [comment]
I don't use org-agenda-list, sorry.

**Comment by cslux** [comment]
@bon The task need a timestamp (scheduled, deadline or active timestamp) to show up in `org-agenda-list`. Also check if you really have set `org-journal-enable-agenda-integration` to `t`.
