### ISSUE TITLE
org-journal-date-format being a function causes error during search

### ISSUE THREAD

**Issue by amitp** [bastibe/org-journal#91]
org-journal-date-format's documentation says it can be either a string or a function.

org-journal-new-entry allows it to be a string or function.

org-journal-search-print-results does not; it only allows it to be a string

This means if you are using a function instead of a string, you cannot use the search functionality.

**Comment by bastibe** [comment]
Thank you for the your bug report!

Should be fixed in ad61dcd. Can you confirm?

**Comment by amitp** [comment]
Looks great! org-journal-new-entry could call the new function too. Thank you!
