### ISSUE TITLE
How to add additional headers to journal file?

### ISSUE THREAD

**Issue by matthjes** [bastibe/org-journal#94]
Hi,

I'd like to export my journals to HTML, but don't need a header numbering, so normally I would add a header `#+OPTIONS: num:nil` to the file.

How can this be done automatically for each newly created journal file? I'm not that experienced with Emacs/Elisp.

**Comment by martinbalfanz** [comment]
You could use the `org-hournal-after-entry-create-hook` and insert your text at the beginning of the buffer, for example like this:

```elisp
(add-hook 'org-journal-after-entry-create-hook
            (lambda ()
              (save-excursion
                (beginning-of-buffer)
                (insert "#+OPTIONS: num:nil\n\n"))))
```

I use something similar to add file example `#+FILETAGS` to my journal files.

**Comment by bastibe** [comment]
Another option is to modify `org-journal-date-prefix`, for example:

```elisp
(setq org-journal-date-prefix "#+OPTIONS: num:nil\n* ")
```

(default is `"* "`)

**Comment by snuffop** [comment]
Is there a way to get a default File template  say 


#+TITLE: Daily Journal for (date-format)'
* Status  yada yada (stuff)
* Entries      {everthing above including this line pulled from a template}
** 00:01  starting entries
** 00:30  adding notes to journal


end

**Comment by bastibe** [comment]
While this would be possible with just org-journal's templates, something like @martinbalfanz' solution is probably easier to maintain.

**Comment by cslux** [comment]
Related to #153
