### ISSUE TITLE
How to carryover all items except those marked "DONE"?

### ISSUE THREAD

**Issue by olegbc1** [bastibe/org-journal#95]
My org tasks are configured to have only 3 states, `TODO`, `STARTED`, and `DONE`, so I've set `(org-journal-carryover-items "TODO=\"TODO\" \"STARTED\"")` via customize menu, although I am not sure this is correct.

Now when I call `org-journal-new-item` I am presented with an empty new file with just a today's date on the top. If I set carryover items correctly, maybe it would be better to configure org-journal to carryover all times not matched with `DONE`? If so, could you help me with the matching string, [org documentation on matching properties](https://orgmode.org/manual/Matching-tags-and-properties.html) is kinda murky..

Appreciate it!

**Comment by olegbc1** [comment]
Just to update. I simplified the carryover string to `(org-journal-carryover-items "TODO="TODO"")` and now, when I press `C-c C-j` (or `just type out org-journal-new-entry`), a am presented with yesterday's file, yet a see that today's file is created with nothing in it but a date on top... I also get the following message in my \*messages\*:

> Error running timer ‘ergoemacs-command-loop--timer’: (error "Before first headline at position 1 in buffer 2018 03 05.org")

**Comment by bastibe** [comment]
I believe the correct version would be `(setq org-journal-carryover-items "TODO=\"TODO\"|TODO=\"STARTED\"")`. Let me know if this works. If so, it might be useful to add this to the README.

**Comment by olegbc1** [comment]
Thanks for responding @bastibe! The issue persists for some reason. I added `(setq org-journal-carryover-items "TODO=\"TODO\"|TODO=\"STARTED\"")` to my .emacs file but when I call `M-x` `org-journal-new-entry`, I see yesterday's file (where I copied everything manually), but I also see a buffer with a new file in the background, which has today's date on the top.

The only relevant message I see in \*Messages\* is this (note, 2018-03-06.org is a yesterday's file) -

> org-back-to-heading: Before first headline at position 1 in buffer 2018-03-06.org 

I tried deleting the yesterday's file to see what would happen and `M-x` `org-journal-new-entry` opened the file from day before that 2018-03-05.org and created 2018-03-07.org in the background again with similar message in \*Messages\*.

**Comment by olegbc1** [comment]
Okay, I have not changed anything but after restarting emacs (again) it suddenly just started working. Not idea why! :-)

One unexpected behavior is that the mode carries over only the items that have TODO or STARTED flags, but doesn't carry over any other notes. Is it possible to configure it such a way that it transfers everything except for items marked "DONE"? Maybe there is a regexp expression?

**Comment by bastibe** [comment]
I believe that should be `(setq org-journal-carryover-items "-TODO=\"DONE\"")` (note the `-`).

**Comment by olegbc1** [comment]
Looks like it worked, although org-journal is again opening an older file, while creating a new one in the background... How does org-journal determine the date of the files, by its name, content, or "last updated" property? Asking because I might be confusing it by editing "old" files to see how tasks get carried over.

**Comment by bastibe** [comment]
Always by filename. The date is extracted from the file name using `org-journal-file-format`. This is why `org-journal-file-format` must contain "%Y", "%m", and "%d".

The carry over is run only when a new file is being created. It then searches backwards from that buffer's name/date to the previous entry, and moves all TODO entries over to the current buffer.

**Comment by olegbc1** [comment]
Thanks. I tweaked my .emacs to not rely on settings set in customize menu. Here is my org-journal configuration - 

```
(use-package org-journal
	:straight t)

 (setq org-journal-carryover-items "-TODO=\"DONE\"")
 (setq org-journal-date-prefix "")
 (setq org-journal-dir "~/Dropbox/Oleg/Org/Journal/")
 (setq org-journal-file-format "%Y-%m-%d.org")
 (setq org-journal-find-file (quote find-file))
 (setq org-journal-hide-entries-p nil)
 (setq org-journal-time-format "")
 (setq org-journal-time-prefix "")

(org-journal-mode)
```

with this config, org-journal creates a new file, shows it to me, but it is empty... Do you think it's the regexp expression that excludes everything?

Thanks so much for your continued help! I am new to emacs, and your help is what keeps me going with tinkering.

**Comment by bastibe** [comment]
Let's start simple, and build from there:

My config contains only one line of customization:
`(setq org-journal-file-format "%Y-%m-%d.org")`

With only this set, both carryover and calendar integration work as intended.

Can you reproduce this on your computer?

**Comment by olegbc1** [comment]
I reduced the config to
```
(use-package org-journal
	:straight t)
(setq org-journal-dir "~/Dropbox/Oleg/Org/Journal/")
(setq org-journal-file-format "%Y-%m-%d.org")
```
and the same issue persists. Let me try setting up the package without "straight t"

**Comment by olegbc1** [comment]
No changes, still the same issue. I am testing on windows 10, not sure if that could be causing an issue (like directory path should use `\\` instead of `/` or something?)

Also, my org file is like this:

```
* Project A                                       
  SCHEDULED: <2018-02-28 Wed>
** TODO Task 1
** STARTED Task 2
** TODO Task 3
** DONE Task 4

* Project B                                           
  DEADLINE: <2018-03-07 Wed>
** TODO Task 1
** TODO Task 2
** TODO Task 3
*** STARTED Task 4
    - notes for task 4
    - in form of a list
*** DONE Task 5
```

**Comment by bastibe** [comment]
You need to set all configuration variables *before* loading org-journal.

**Comment by olegbc1** [comment]
I am probably just an idiot so please forgive me for asking, but do you mean like this: 
```
(setq org-journal-dir "~/Dropbox/Oleg/Org/Journal/")
(setq org-journal-file-format "%Y-%m-%d.org")
(setq org-journal-carryover-items "TODO=\"TODO\"|TODO=\"STARTED\"")

(use-package org-journal
	:straight t)
```
I tried this and when I run `org-journal-new-entry` it opened a new file while moving all items that have TODO and STARTED in them. That was great!

Next, I went ahead and changed the carryover items string to` (setq org-journal-carryover-items "-TODO=\"DONE\"")` as you've suggested before, to move all items except for those that are marked DONE. I reloaded emacs and now the new file is empty and created in the background again.

I rolled back to the previous configuration, restarted emacs but the problem remained - as I run `org-journal-new-entry` an old org file is openned and shown to me while a new and empty one is created in the background...

\*messages\* buffer only shows this message:

> org-back-to-heading: Before first headline at position 1 in buffer 2018-03-05.org
> Auto-saving...

Do you know what could this error mean?

Thanks so much for troubleshooting with me!

**Comment by bastibe** [comment]
> but do you mean like this

Yes.

(Just to be sure, I assume that after trying the carryover, you reset your journal's files, right? Carryover only happens if a new file is created, so if there is an empty file already, nothing will carry over)

I think you should try a really minimal config. Back up your init.el, and start with a clean one that contains only your org-journal customizations. Build up a working org-journal there, and then try to integrate it with your true init.el. I have a feeling that there is some unrelated interaction with your init and org-journal.

**Comment by olegbc1** [comment]
I suspect that you're right. I was planning on redoing my config anyway so this will be a good opportunity. Bear with me for a few days and I'll report any findings. Might be good to include in readme if I find anything.

Thanks again!

**Comment by bastibe** [comment]
I will be very interested in your findings!

**Comment by baogiadoan** [comment]
hi, I'm facing the same issue at the moment, I tried with the config `(setq org-journal-carryover-items "-TODO=\"DONE\"")`. However if I config that way everytime I create new entry it will somehow mess up with the current-date entries and delete the headings. Below is my config:

```
(use-package! org-journal
    :ensure t
    :defer t
    :init
    :config
    (setq org-journal-dir "~/ownCloud/org/journal/"
          org-journal-file-format "%Y.org"
          org-journal-file-type 'yearly
          org-journal-enable-agenda-integration t
          org-journal-date-format "%A, %d/%m/%y"
          org-journal-carryover-items "-TODO=\"DONE\"" ;; set carry over exclude DONE
     ))

```
