### ISSUE TITLE
Set org-journal-file-format to include .org  Search carry-over and other functions fail

### ISSUE THREAD

**Issue by ghost** [bastibe/org-journal#96]
Using Spacemacs (develop) org-journal mode built in.  
https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org
My Journal config

```emacs-lisp
      (setq org-directory "~/Notes/org/")
      (setq org-contacts-files "~/Notes/org/contacts.org")
      (setq org-default-notes-file "~/Notes/org/0mobile.org")
      (setq org-archive-location "~/Notes/org/logbook.org::* Archived") 
      (setq org-id-locations-file "~/.spacemacs.d/local/org-id-locations")
      (setq org-agenda-files '("~/Notes/org"))
      (setq org-ellipsis " ⤵")
      (setq org-tags-column -80)
      (setq org-hide-leading-stars t)
      (setq org-id-track-globally t)
      (setq org-log-done t)
      (setq org-refile-targets '((nil :maxlevel . 9)
                                 (org-agenda-files :maxlevel . 9)))

      (with-eval-after-load 'org-journal 
        (setq org-journal-dir "~/Notes/Journal/")
        (add-to-list 'org-agenda-files (expand-file-name "~/Notes/Journal/"))
        (setq org-journal-file-format "%Y%m%d.org")
        (setq org-journal-date-prefix "#+TITLE: Daily Notes "))
```
```emacs-lisp
-- 
org-journal-file-format is a variable defined in ‘org-journal.el’.
Its value is "%Y%m%d.org"
Original value was "%Y%m%d"

Documentation:
Format string for journal file names, by default "YYYYMMDD".
  This pattern must include ‘%Y‘, ‘%m‘ and ‘%d‘. Setting this
  will update the internal ‘org-journal-file-pattern‘ to a regex
  that matches the format string using
  ‘(org-journal-format-string->regex format-string)‘, and update
  ‘auto-mode-alist‘ using
  ‘(org-journal-update-auto-mode-alist)‘.

You can customize this variable.
```
spacemacs instantiation 
```emacs-lisp
(defun org/init-org-journal ()
  (use-package org-journal
    :defer t
    :commands (org-journal-new-entry org-journal-search-forever)
    :init
    (progn
      (spacemacs/declare-prefix "aoj" "org-journal")
      (spacemacs/set-leader-keys
        "aojj" 'org-journal-new-entry
        "aojs" 'org-journal-search-forever)

      (spacemacs/set-leader-keys-for-major-mode 'calendar-mode
        "r" 'org-journal-read-entry
        "i" 'org-journal-new-date-entry
        "n" 'org-journal-next-entry
        "p" 'org-journal-previous-entry
        "s" 'org-journal-search-forever
        "w" 'org-journal-search-calendar-week
        "m" 'org-journal-search-calendar-month
        "y" 'org-journal-search-calendar-year)

      (spacemacs/set-leader-keys-for-major-mode 'org-journal-mode
        "j" 'org-journal-new-entry
        "n" 'org-journal-open-next-entry
        "p" 'org-journal-open-previous-entry))))
```
When using the default numbers only version of the file-format.  everything org-journal works but agenda wouldn't see the files even with the regex changed and the directory added to agada-files.
yet with the .org extension set in the file-format.  all of agenda works  as well as my orgzly on the android.  but previous, next searching journal <ag and grep work for that<  but the carry over I miss that doesn't work.   org journal starts a new file in the correct directory with the correct filename and with the header as I specified in the config.  Yet the TODO's are still in yesterday's journal.  etc.

Marty

**Comment by bastibe** [comment]
Please try
```elisp
  (with-eval-after-load 'org-journal 
        (setq org-journal-dir "~/Notes/Journal/")
        (add-to-list 'org-agenda-files (expand-file-name "~/Notes/Journal/"))
        (setq org-journal-file-format "%Y%m%d.org")
        (org-journal-update-auto-mode-alist)
        (setq org-journal-date-prefix "#+TITLE: Daily Notes "))
```
and see if that helps.

**Comment by MBuchaus** [comment]
No change I'm afraid.  I'm no lisp dev but seems like org-journal-list-dates function is a place to look .. i'm trying to Troubleshoot this myself as well..  and am trying find the result of the mapcar #'org-journal-file-name->calendar-date  etc..
to try and track it down

**Comment by bastibe** [comment]
I think I have an idea of what the problem might be: You should set `org-journal-file-format` *before* loading `org-journal-mode`. If it is set afterwards, it won't pick up your modification.

Alternatively, try running
`(setq org-journal-file-pattern (org-journal-format-string->regex org-journal-file-format))`
(this is done automatically when org-journal starts up, or when `org-journal-file-pattern` is changed in `customize`)

**Comment by MBuchaus** [comment]
That has promise:   
  Carry-over Search, Prev working  Once loading another journal though it defaults to ORG major mode so the keys are no longer bound for prev next (easily fixed). 

But is there a way to metadata the file to where its seen as org-journal? 
  
  FIX For other spacemacs users:
```emacs-lisp
  spacemacs-configuration-layer '(
  (org   :variables
          org-enable-github-support t
          org-enable-org-journal-support t
          org-journal-file-format "%Y%m%d.org"
          org-journal-dir "~/Notes/Journal"
          org-journal-date-prefix "#+TITLE: Daily Notes "
  )'
```
This loads the variables before spacemacs loads org or org-journal  Thanks Bastibe

**Comment by bastibe** [comment]
The major mode is defined by `auto-mode-alist` and should be set up during load of org-journal. I bet the org-mode entry in `auto-mode-alist` is coming before org-journal-mode's entry on your machine?

**Comment by MBuchaus** [comment]
if the array is used in order of display then it's not..  not sure why there are two either?  looking into that..   Thanks for all the help too..  
```
Value:
(("/home/marty/Dropbox/Notes/Journal/\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\).org\\'" . org-journal-mode)
 ("/home/marty/Dropbox/Notes/Journal/\\(?1:[0-9]\\{4\\}\\)\\(?2:[0-9][0-9]\\)\\(?3:[0-9][0-9]\\)\\'" . org-journal-mode)
 ("\\.as[cp]x\\'" . web-mode)
 ("\\.[agj]sp\\'" . web-mode)
 ("Procfile\\'" . yaml-mode)
 ("\\.\\(yml\\|yaml\\)\\'" . yaml-mode)
....
```

**Comment by bastibe** [comment]
My auto-mode-alist looks the same. Not sure why this would work for me, but not for you.

**Comment by cslux** [comment]
I think this can be closed!
