### ISSUE TITLE
org-journal-new-entry opens new entry plus previous day's

### ISSUE THREAD

**Issue by ejmg** [bastibe/org-journal#98]
hi there,

as of now, the default behavior for `org-journal-new-entry` is to open a new entry as expected. However, it also opens the previous day's entry.

Looking into the source code, the issue was easy to pinpoint to the default behavior of carrying over the previous day's TODO entries. A side-effect of `org-journal-carryover ()`, which is called each time by `org-journal-new-entry()`, is opening a buffer of the previous day's journal via `org-journal-open-previous-entry`. This buffer is never closed afterwards.

Setting `(setq org-journal-carryover-items nil)` per the README solves this behavior and it doesn't bother me personally since I don't keep TODOs in my journals.

That said, I was wondering if this was a desired effect of carrying over and, if not, would a PR be appropriate for fixing this? I would be wiling to check into it. I don't know too much emacs-lisp but would love to contribute where I can :slightly_smiling_face:

**Comment by bastibe** [comment]
Thank you for this bug report! `org-journal-new-entry` is definitely not intended to open the previous journal entry and keep it open.

If you want to take a stab at it, I'd be grateful!

**Comment by ejmg** [comment]
I will definitely take a look at it.

From what I have looked over, I might have a simple fix already in mind.

Assuming `file-name` is the current org-journal entry, do you know of a sane/safe way to decrement a day off the entry's name while also respecting date logic? i.e. decrement 1 from `20180401` gives `20180331`. 

If so, passing that result to `org-journal-file-name->calendar-date()` would give me a way to kill the buffer at the end of `org-journal-carryover ()` after all its work is done. 

Does that sound like a good solution to you? Otherwise, I think I would have to look at a way of extracting the TODO subtree from a previous entry without opening it at all, which would probably require a bit more rewriting whereas my above idea may just be ~4+ LOC or so.
