### ISSUE TITLE
Command to delete a journal?

### ISSUE THREAD

**Issue by phye** [bastibe/org-journal#99]
I can remove a journal by removing the file directly in shell, just wonder if there're any keybings/functions that I can enter/call to remove an accidently inserted journal?

**Comment by bastibe** [comment]
There's no function for this in org-journal, but this is Emacs, and `(delete-file buffer-file-name)` should do the trick.

**Comment by phye** [comment]
This is indeed emacs, anything is possible 👍 
Thanks!
